<x-app-layout :title="$title"><div class="space-y-6">
<section class="rounded-3xl bg-emerald-950 p-6 text-white shadow-sm"><p class="text-sm text-emerald-100">Beranda e-Madrasah</p><h2 class="mt-2 text-2xl font-black">{{ $profile->display_name }}</h2><p class="mt-2 text-sm text-emerald-50">Kelola fondasi data madrasah secara aman dan terstruktur.</p></section>
@if(auth()->user()->can('academic-attendance.view') || auth()->user()->can('academic-grades.view') || auth()->user()->can('academic-reports.view'))<section class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Akademik Hari Ini</h2><div class="mt-4 grid grid-cols-2 gap-4 md:grid-cols-6">@foreach(['recorded'=>'Rombel sudah diabsen','pending'=>'Rombel belum diabsen','present'=>'Hadir','sick'=>'Sakit','permitted'=>'Izin','absent'=>'Alpa'] as $key=>$label)<div><p class="text-xs text-slate-500">{{$label}}</p><p class="text-2xl font-black">{{$academicToday[$key]}}</p></div>@endforeach</div><div class="mt-5 flex flex-wrap gap-2">@can('academic-attendance.view')<a class="btn btn-primary" href="{{route('academic.attendance.index')}}">Input Absensi</a>@endcan @can('academic-grades.view')<a class="btn btn-secondary" href="{{route('academic.grades.index')}}">Input Nilai</a>@endcan @can('academic-reports.view')<a class="btn btn-secondary" href="{{route('academic.reports.index')}}">Laporan Akademik</a>@endcan</div></div></section>@endif
<section class="card"><div class="card-body"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-emerald-950">Profil Madrasah</h2><p class="mt-1 text-sm text-slate-500">Identitas resmi yang digunakan pada aplikasi dan dokumen.</p></div><span class="badge badge-success">Kelengkapan Profil: {{ $profile->completeness_percentage }}%</span></div>
<div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p class="text-xs text-slate-500">Nama madrasah</p><p class="font-semibold">{{ $profile->name }}</p></div><div><p class="text-xs text-slate-500">NSM / NPSN</p><p class="font-semibold">{{ $profile->nsm ?: '-' }} / {{ $profile->npsn ?: '-' }}</p></div><div><p class="text-xs text-slate-500">Kepala madrasah</p><p class="font-semibold">{{ $profile->head_name ?: 'Belum diisi' }}</p></div><div><p class="text-xs text-slate-500">Status kelengkapan</p><div class="progress mt-2"><span style="width: {{ $profile->completeness_percentage }}%"></span></div></div></div>
@can('school-profile.view')<div class="mt-6"><a href="{{ route('school-profile.show') }}" class="btn btn-primary">Lengkapi Profil Madrasah</a></div>@endcan</div></section>
<section class="card"><div class="card-body"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-emerald-950">Periode Akademik</h2>@if($academicPeriod && $academicPeriod->activeSemester)<p class="mt-2 text-xl font-black text-emerald-950">{{ $academicPeriod->name }}</p><p class="font-semibold text-slate-700">{{ $academicPeriod->activeSemester->display_name }}</p><p class="mt-1 text-sm text-slate-500">{{ $academicPeriod->activeSemester->display_period }}</p>@else<p class="mt-2 text-sm text-slate-500">Belum ada periode akademik aktif.</p>@endif</div>@can('academic-periods.view')<a href="{{ route('academic-periods.index') }}" class="btn btn-primary">Atur Periode Akademik</a>@endcan</div></div></section>
@can('personnel.view')<section class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Data Personalia</h2><div class="mt-4 grid gap-4 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Total Personalia</p><p class="text-2xl font-black">{{ $personnelStats['total'] }}</p></div><div><p class="text-xs text-slate-500">Personalia Aktif</p><p class="text-2xl font-black">{{ $personnelStats['active'] }}</p></div><div><p class="text-xs text-slate-500">Belum Memiliki Akun</p><p class="text-2xl font-black">{{ $personnelStats['without_account'] }}</p></div></div><a href="{{ route('personnel.index') }}" class="btn btn-primary mt-5">Buka Data Personalia</a></div></section>@endcan
@can('students.view')<section class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Data Siswa</h2><div class="mt-4 grid gap-4 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Total Siswa</p><p class="text-2xl font-black">{{ $studentStats['total'] }}</p></div><div><p class="text-xs text-slate-500">Siswa Aktif</p><p class="text-2xl font-black">{{ $studentStats['active'] }}</p></div><div><p class="text-xs text-slate-500">Data Orang Tua Belum Lengkap</p><p class="text-2xl font-black">{{ $studentStats['incomplete_parents'] }}</p></div></div><a href="{{ route('students.index') }}" class="btn btn-primary mt-5">Buka Data Siswa</a></div></section>@endcan
@if(auth()->user()->can('classrooms.view') || auth()->user()->can('classrooms.view-own'))<section class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Kelas & Rombel</h2>@if(auth()->user()->can('classrooms.view'))<div class="mt-4 grid gap-4 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Total Rombel</p><p class="text-2xl font-black">{{ $classroomStats['total'] }}</p></div><div><p class="text-xs text-slate-500">Siswa Belum Ditempatkan</p><p class="text-2xl font-black">{{ $classroomStats['unplaced'] }}</p></div><div><p class="text-xs text-slate-500">Rombel Tanpa Wali Kelas</p><p class="text-2xl font-black">{{ $classroomStats['without_homeroom'] }}</p></div></div>@else<h3 class="mt-3 font-bold">Rombel Saya</h3>@forelse($classroomStats['own'] as $room)<p>{{ $room->display_name }} · {{ $room->active_memberships_count }} siswa</p>@empty<p class="text-sm text-slate-500">Anda belum menjadi wali kelas.</p>@endforelse @endif<a href="{{ route('classrooms.index') }}" class="btn btn-primary mt-5">Buka Kelas & Rombel</a></div></section>@endif
</div></x-app-layout>
