<?php
declare(strict_types=1); namespace App\Http\Controllers\Personnel;
use App\Http\Controllers\Controller; use App\Http\Requests\Personnel\{StorePersonnelRequest,UpdatePersonnelRequest}; use App\Models\{Personnel,User}; use App\Services\Personnel\{PersonnelExportService,PersonnelService}; use Illuminate\Database\Eloquent\Builder; use Illuminate\Http\{RedirectResponse,Request}; use Illuminate\View\View;
class PersonnelController extends Controller
{
 public function __construct(private PersonnelService $service){}
 public static function filtered(Request $r):Builder{$q=Personnel::query()->with('user');if($s=$r->string('search')->trim()->toString())$q->where(fn($x)=>$x->where('full_name','like',"%$s%")->orWhere('foundation_employee_number','like',"%$s%")->orWhere('nip','like',"%$s%")->orWhere('external_employee_id','like',"%$s%")->orWhere('position','like',"%$s%")->orWhere('phone','like',"%$s%")->orWhere('email','like',"%$s%"));foreach(['gender','employment_status','position','certification_status'] as $f)if($v=$r->input($f))$q->where($f,$v);if($r->filled('active'))$q->where('is_active',$r->boolean('active'));if($r->input('account')==='connected')$q->whereNotNull('user_id');if($r->input('account')==='none')$q->whereNull('user_id');return $q->orderBy('full_name');}
 public function index(Request $r):View{$base=Personnel::query();$stats=['total'=>(clone $base)->count(),'teachers'=>(clone $base)->where('is_active',true)->where(fn($q)=>$q->where('position','like','%Guru%')->orWhere('position','like','%Kepala Madrasah%'))->count(),'staff'=>(clone $base)->where('is_active',true)->where('position','not like','%Guru%')->where('position','not like','%Kepala Madrasah%')->count(),'inactive'=>(clone $base)->where('is_active',false)->count(),'without_account'=>(clone $base)->whereNull('user_id')->count()];return view('personnel.index',['title'=>'Data Personalia','personnel'=>self::filtered($r)->paginate(15)->withQueryString(),'stats'=>$stats,'positions'=>Personnel::distinct()->pluck('position')]);}
 public function create():View{return view('personnel.form',$this->formData(new Personnel,false));}
 public function store(StorePersonnelRequest $r):RedirectResponse{$data=$r->validated();if(!$r->user()->can('personnel.manage-account'))unset($data['user_id']);$p=$this->service->create($data,$r->user());return redirect()->route('personnel.show',$p)->with('status','Data personalia berhasil ditambahkan.');}
 public function show(Request $r,Personnel $personnel,PersonnelExportService $export):View{$personnel->load(['user.roles','createdBy','updatedBy']);$values=$personnel->toArray();if(!$r->user()->can('personnel.view-sensitive'))foreach(['nip','external_employee_id','bank_name','bank_account_number','phone','email'] as $f)$values[$f]=$export->mask((string)$personnel->$f)?:'—';return view('personnel.show',['title'=>$personnel->full_name,'personnel'=>$personnel,'display'=>$values]);}
 public function edit(Personnel $personnel):View{return view('personnel.form',$this->formData($personnel,true));}
 public function update(UpdatePersonnelRequest $r,Personnel $personnel):RedirectResponse{$data=$r->validated();if(!$r->user()->can('personnel.manage-account'))unset($data['user_id']);$this->service->update($personnel,$data,$r->user());return redirect()->route('personnel.show',$personnel)->with('status','Data personalia berhasil diperbarui.');}
 private function formData(Personnel $p,bool $editing):array{return ['title'=>$editing?'Edit Personalia':'Tambah Personalia','personnel'=>$p,'editing'=>$editing,'accounts'=>User::whereDoesntHave('personnel')->when($p->user_id,fn($q)=>$q->orWhereKey($p->user_id))->orderBy('name')->get()];}
}
