<?php
namespace App\Services\Inventory;
use App\Models\Inventory\{InventoryBalance,InventoryItem,InventoryStockOpname,InventoryTransaction}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class InventoryLedgerService{
 public function post(array $d, ?int $userId=null): InventoryTransaction { return DB::transaction(function() use($d,$userId){ if(($d['quantity']??0)<=0) throw ValidationException::withMessages(['quantity'=>'Jumlah harus lebih dari nol.']); $type=$d['type']; $tx=InventoryTransaction::create($d+['transaction_number'=>$d['transaction_number']??$this->number($type),'status'=>'posted','posted_by'=>$userId,'created_by'=>$userId,'posted_at'=>now()]); match($type){'opening','addition'=> $this->increase($d['inventory_item_id'],$d['to_location_id'],$d['to_condition_id'],$d['quantity']),'reduction'=> $this->decrease($d['inventory_item_id'],$d['from_location_id'],$d['from_condition_id'],$d['quantity']),'transfer'=> $this->transfer($d),'condition_change'=> $this->condition($d),'correction'=> $this->correction($d), default=>throw ValidationException::withMessages(['type'=>'Jenis transaksi tidak valid.'])}; return $tx;});}
 public function transfer(array $d):void{ if((int)$d['from_location_id']===(int)$d['to_location_id']) throw ValidationException::withMessages(['to_location_id'=>'Lokasi tujuan harus berbeda.']); $this->decrease($d['inventory_item_id'],$d['from_location_id'],$d['from_condition_id'],$d['quantity']); $this->increase($d['inventory_item_id'],$d['to_location_id'],$d['from_condition_id'],$d['quantity']);}
 public function condition(array $d):void{ if((int)$d['from_condition_id']===(int)$d['to_condition_id']) throw ValidationException::withMessages(['to_condition_id'=>'Kondisi baru harus berbeda.']); $this->decrease($d['inventory_item_id'],$d['from_location_id'],$d['from_condition_id'],$d['quantity']); $this->increase($d['inventory_item_id'],$d['from_location_id'],$d['to_condition_id'],$d['quantity']);}
 public function correction(array $d):void{ if(blank($d['reason']??null)) throw ValidationException::withMessages(['reason'=>'Koreksi wajib memiliki alasan.']); (($d['quantity']??0)>=0) ? $this->increase($d['inventory_item_id'],$d['to_location_id'],$d['to_condition_id'],$d['quantity']) : $this->decrease($d['inventory_item_id'],$d['from_location_id'],$d['from_condition_id'],abs($d['quantity']));}
 public function reverse(InventoryTransaction $tx,string $reason,?int $userId=null):InventoryTransaction{ if($tx->status!=='posted') throw ValidationException::withMessages(['status'=>'Hanya transaksi diposting yang dapat dibatalkan.']); $map=['opening'=>'reduction','addition'=>'reduction','reduction'=>'addition','transfer'=>'transfer','condition_change'=>'condition_change','correction'=>'correction']; return $this->post(['type'=>$map[$tx->type],'transaction_date'=>now()->toDateString(),'inventory_item_id'=>$tx->inventory_item_id,'from_location_id'=>$tx->to_location_id ?? $tx->from_location_id,'to_location_id'=>$tx->from_location_id ?? $tx->to_location_id,'from_condition_id'=>$tx->to_condition_id ?? $tx->from_condition_id,'to_condition_id'=>$tx->from_condition_id ?? $tx->to_condition_id,'quantity'=>$tx->quantity,'reason'=>'Reversal: '.$reason,'notes'=>'Membatalkan '.$tx->transaction_number,'reversal_of_id'=>$tx->id],$userId);}
 public function createStockOpname(array $d,?int $userId=null):InventoryStockOpname{return DB::transaction(function()use($d,$userId){$op=InventoryStockOpname::create($d+['opname_number'=>$d['opname_number']??$this->number('SO'),'officer_id'=>$userId,'status'=>'checking']); InventoryBalance::where('inventory_location_id',$d['inventory_location_id'])->where('quantity','>',0)->get()->each(fn($b)=>$op->lines()->create(['inventory_item_id'=>$b->inventory_item_id,'inventory_condition_id'=>$b->inventory_condition_id,'system_quantity'=>$b->quantity,'physical_quantity'=>$b->quantity,'difference_quantity'=>0])); return $op;});}
 public function postStockOpname(InventoryStockOpname $op,?int $userId=null):void{ DB::transaction(function()use($op,$userId){ foreach($op->lines as $line){ $diff=$line->physical_quantity-$line->system_quantity; if($diff>0)$this->post(['type'=>'addition','transaction_date'=>$op->opname_date,'inventory_item_id'=>$line->inventory_item_id,'to_location_id'=>$op->inventory_location_id,'to_condition_id'=>$line->inventory_condition_id,'quantity'=>$diff,'reason'=>'Koreksi stock opname '.$op->opname_number],$userId); if($diff<0)$this->post(['type'=>'reduction','transaction_date'=>$op->opname_date,'inventory_item_id'=>$line->inventory_item_id,'from_location_id'=>$op->inventory_location_id,'from_condition_id'=>$line->inventory_condition_id,'quantity'=>abs($diff),'reason'=>'Koreksi stock opname '.$op->opname_number],$userId);} $op->update(['status'=>'completed','posted_at'=>now()]);});}
 private function increase($item,$loc,$cond,$qty):void{$b=InventoryBalance::firstOrCreate(['inventory_item_id'=>$item,'inventory_location_id'=>$loc,'inventory_condition_id'=>$cond],['quantity'=>0]); $b->lockForUpdate(); $b->increment('quantity',$qty); InventoryItem::whereKey($item)->update(['primary_location_id'=>$loc]);}
 private function decrease($item,$loc,$cond,$qty):void{$b=InventoryBalance::where(['inventory_item_id'=>$item,'inventory_location_id'=>$loc,'inventory_condition_id'=>$cond])->lockForUpdate()->first(); if(!$b||$b->quantity<$qty) throw ValidationException::withMessages(['quantity'=>'Saldo tidak mencukupi.']); $b->decrement('quantity',$qty);}
 private function number(string $type):string{return 'INV-'.strtoupper($type).'-'.now()->format('YmdHis').'-'.random_int(100,999);} }
