<x-app-layout title="Profil Madrasah">
<form method="post" action="{{ route('school-profile.update') }}" enctype="multipart/form-data" class="space-y-6">
@csrf @method('put')
<div class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Identitas Madrasah</h2><p class="mb-5 text-sm text-slate-500">Lengkapi identitas resmi madrasah.</p><div class="grid gap-4 md:grid-cols-2">
@foreach([['school_name','Nama madrasah','required'],['nsm','NSM',''],['npsn','NPSN',''],['foundation_name','Yayasan','']] as $f)<div><label for="{{ $f[0] }}">{{ $f[1] }} @if($f[2])<span class="text-rose-600">*</span>@endif</label><input id="{{ $f[0] }}" name="{{ $f[0] }}" value="{{ old($f[0], $profile->{$f[0]}) }}" {{ $f[2] }}><p class="mt-1 text-xs text-rose-600">@error($f[0]){{ $message }}@enderror</p></div>@endforeach
<div><label>Jenjang</label><input value="Madrasah Ibtidaiyah" disabled><p class="mt-1 text-xs text-slate-500">Jenjang ditampilkan sesuai konfigurasi aplikasi.</p></div><div><label>Status</label><input value="Aktif" disabled></div>
</div></div></div>
<div class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Alamat</h2><div class="mt-5 grid gap-4 md:grid-cols-2"><div class="md:col-span-2"><label>Alamat lengkap</label><textarea name="address" rows="3">{{ old('address',$profile->address) }}</textarea></div>@foreach([['village','Desa/Kelurahan'],['district','Kecamatan'],['city','Kabupaten/Kota'],['province','Provinsi'],['postal_code','Kode Pos']] as $f)<div><label>{{ $f[1] }}</label><input name="{{ $f[0] }}" value="{{ old($f[0],$profile->{$f[0]}) }}"></div>@endforeach</div></div></div>
<div class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Kontak dan Kepala Madrasah</h2><div class="mt-5 grid gap-4 md:grid-cols-2">@foreach([['phone','Nomor telepon','tel'],['email','Email','email'],['website','Website','url'],['principal_name','Nama kepala madrasah','text'],['timezone','Timezone','text']] as $f)<div><label>{{ $f[1] }} @if($f[0]==='timezone')<span class="text-rose-600">*</span>@endif</label><input type="{{ $f[2] }}" name="{{ $f[0] }}" value="{{ old($f[0],$profile->{$f[0]}) }}" @required($f[0]==='timezone')><p class="mt-1 text-xs text-rose-600">@error($f[0]){{ $message }}@enderror</p></div>@endforeach<div><label>WhatsApp</label><input value="{{ old('phone',$profile->phone) }}" disabled><p class="mt-1 text-xs text-slate-500">Gunakan nomor telepon yang dapat menerima WhatsApp bila tersedia.</p></div><div><label>Locale</label><input value="id_ID" disabled></div></div></div></div>
<div class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Branding</h2><div class="mt-5 grid gap-6 md:grid-cols-[220px_1fr]"><div><div class="grid h-36 w-36 place-items-center overflow-hidden rounded-2xl border border-slate-200 bg-slate-50">@if($profile->logo_path)<img src="{{ Storage::url($profile->logo_path) }}" class="h-full w-full object-cover" alt="Logo saat ini">@else<span class="text-sm text-slate-500">Belum ada logo</span>@endif<img id="logoPreview" class="hidden h-full w-full object-cover" alt="Preview logo"></div></div><div><label>Upload logo</label><input type="file" name="logo" accept="image/*" onchange="previewImage(event,'logoPreview')"><p class="mt-2 text-xs text-slate-500">Format JPG/PNG, maksimal 2 MB. Gunakan rasio persegi agar logo rapi.</p><p class="mt-1 text-xs text-rose-600">@error('logo'){{ $message }}@enderror</p></div></div></div></div>
<div class="flex flex-wrap justify-end gap-2"><a href="{{ route('dashboard') }}" class="btn btn-secondary">Kembali</a><button type="reset" class="btn btn-secondary">Reset</button><button class="btn btn-primary">Simpan Perubahan</button></div>
</form>
</x-app-layout>
