<x-app-layout :title="$title" :breadcrumbs="['Beranda', 'Data Madrasah', 'Profil Madrasah']">
<div class="mb-6"><p class="text-sm text-slate-600">Kelola identitas resmi dan informasi utama madrasah.</p></div>
<div class="grid min-w-0 gap-6 lg:grid-cols-12">
  <div class="order-2 min-w-0 space-y-6 lg:order-1 lg:col-span-4">
    <section class="card"><div class="card-body text-center"><h2 class="text-left text-lg font-bold text-emerald-950">Logo Madrasah</h2>
      <div class="mx-auto mt-5 grid h-36 w-36 place-items-center overflow-hidden rounded-3xl bg-emerald-950 text-4xl font-black text-white" id="logo-fallback">@if($profile->logo_url)<img id="logo-preview" src="{{ $profile->logo_url }}" class="h-full w-full object-cover" alt="Logo {{ $profile->display_name }}">@else<span id="initials">{{ $profile->initials }}</span><img id="logo-preview" class="hidden h-full w-full object-cover" alt="Pratinjau logo">@endif</div>
      <h3 class="mt-4 font-bold text-slate-900">{{ $profile->name }}</h3><p class="text-sm text-slate-500">{{ $profile->education_level }}</p>
      @can('school-profile.update-logo')<form method="post" action="{{ route('school-profile.logo.update') }}" enctype="multipart/form-data" class="mt-5">@csrf<label for="logo" class="btn btn-primary w-full cursor-pointer">Ganti Logo</label><input id="logo" name="logo" type="file" accept="image/png,image/jpeg,image/webp" class="sr-only" onchange="previewImage(event, 'logo-preview'); document.getElementById('initials')?.classList.add('hidden'); this.form.querySelector('button').classList.remove('hidden')"><button type="submit" class="btn btn-outline mt-3 hidden w-full">Unggah Logo</button></form>
      @if($profile->logo_path)<form method="post" action="{{ route('school-profile.logo.destroy') }}" class="mt-3">@csrf @method('DELETE')<button class="btn btn-danger w-full">Hapus Logo</button></form>@endif @endcan
      <p class="mt-4 text-xs leading-5 text-slate-500">Gunakan logo persegi. PNG, JPG, JPEG, atau WEBP, maksimal 2 MB.</p>
    </div></section>
    <section class="card lg:block"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Ubah Password</h2><form method="post" action="{{ route('password.change.update') }}" class="mt-5 space-y-4">@csrf @method('PUT')
      <div><label for="password">Password Baru</label><div class="relative"><input id="password" name="password" type="password" required autocomplete="new-password"><button type="button" class="absolute right-3 top-2.5 text-xs font-semibold text-emerald-700" onclick="togglePassword('password', this)">Tampilkan</button></div></div>
      <div><label for="password_confirmation">Konfirmasi Password Baru</label><div class="relative"><input id="password_confirmation" name="password_confirmation" type="password" required autocomplete="new-password"><button type="button" class="absolute right-3 top-2.5 text-xs font-semibold text-emerald-700" onclick="togglePassword('password_confirmation', this)">Tampilkan</button></div></div>
      <button class="btn btn-primary w-full">Simpan Password</button></form></div></section>
  </div>
  <div class="order-1 min-w-0 space-y-6 lg:order-2 lg:col-span-8">
    <div class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><h2 class="font-bold">Informasi Data Madrasah</h2><p class="mt-1 text-sm">Pastikan data madrasah diisi sesuai dokumen resmi. Data ini akan digunakan pada tampilan aplikasi dan dokumen yang dibuat oleh e-Madrasah.</p></div>
    <section class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Data Madrasah</h2><form method="post" action="{{ route('school-profile.update') }}" class="mt-6 space-y-7">@csrf @method('PUT')
      @php($fields = [['name','Nama Madrasah'],['short_name','Nama Singkat'],['education_level','Jenjang'],['status','Status'],['nsm','NSM'],['npsn','NPSN']])
      <fieldset><legend class="mb-4 text-xs font-bold tracking-widest text-amber-700">IDENTITAS</legend><div class="grid gap-4 md:grid-cols-2">@foreach($fields as [$name,$label])<div><label for="{{ $name }}">{{ $label }}</label>@if($name==='status')<select id="status" name="status" @disabled(!auth()->user()->can('school-profile.update'))><option value="">Pilih status</option>@foreach(['Negeri','Swasta'] as $status)<option @selected(old('status',$profile->status)===$status)>{{ $status }}</option>@endforeach</select>@else<input id="{{ $name }}" name="{{ $name }}" value="{{ old($name,$profile->{$name}) }}" @required(in_array($name,['name','education_level'])) @readonly(!auth()->user()->can('school-profile.update'))>@endif @error($name)<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>@endforeach</div></fieldset>
      <fieldset><legend class="mb-4 text-xs font-bold tracking-widest text-amber-700">ALAMAT</legend><div class="grid gap-4 md:grid-cols-2"><div class="md:col-span-2"><label for="address">Alamat</label><textarea id="address" name="address" rows="3" @readonly(!auth()->user()->can('school-profile.update'))>{{ old('address',$profile->address) }}</textarea></div>@foreach([['village','Desa/Kelurahan'],['district','Kecamatan'],['city','Kabupaten/Kota'],['province','Provinsi'],['postal_code','Kode Pos']] as [$name,$label])<div><label for="{{ $name }}">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" value="{{ old($name,$profile->{$name}) }}" @readonly(!auth()->user()->can('school-profile.update'))></div>@endforeach</div></fieldset>
      <fieldset><legend class="mb-4 text-xs font-bold tracking-widest text-amber-700">KONTAK</legend><div class="grid gap-4 md:grid-cols-2">@foreach([['phone','Nomor Telepon','text'],['whatsapp','Nomor WhatsApp','text'],['email','Email','email'],['website','Website','url']] as [$name,$label,$type])<div><label for="{{ $name }}">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" type="{{ $type }}" value="{{ old($name,$profile->{$name}) }}" @readonly(!auth()->user()->can('school-profile.update'))></div>@endforeach</div></fieldset>
      @can('school-profile.update')<div class="flex justify-end"><button class="btn btn-primary w-full sm:w-auto">Simpan Data Madrasah</button></div>@endcan
    </form></div></section>
    <section class="card"><div class="card-body"><h2 class="text-lg font-bold text-emerald-950">Kepala Madrasah</h2><p class="mt-1 text-sm text-slate-500">Data kepala madrasah akan digunakan pada dokumen dan laporan resmi.</p><form method="post" action="{{ route('school-profile.leader.update') }}" class="mt-5">@csrf @method('PUT')<div class="grid gap-4 md:grid-cols-2"><div><label for="head_name">Nama Kepala Madrasah</label><input id="head_name" name="head_name" value="{{ old('head_name',$profile->head_name) }}" @readonly(!auth()->user()->can('school-profile.update-leader'))></div><div><label for="head_nip">NIP</label><input id="head_nip" name="head_nip" inputmode="numeric" value="{{ old('head_nip',$profile->head_nip) }}" @readonly(!auth()->user()->can('school-profile.update-leader'))></div></div>@can('school-profile.update-leader')<div class="mt-5 flex justify-end"><button class="btn btn-primary w-full sm:w-auto">Simpan Kepala Madrasah</button></div>@endcan</form></div></section>
  </div>
</div>
<script>window.togglePassword=(id,button)=>{const input=document.getElementById(id);input.type=input.type==='password'?'text':'password';button.textContent=input.type==='password'?'Tampilkan':'Sembunyikan'}</script>
</x-app-layout>
