<?php
declare(strict_types=1);
namespace App\Services\Academic;
use App\Http\Requests\Academic\{SaveAttendanceRequest,SaveGradesRequest};
use App\Models\{ClassroomMembership,StudentAttendance,StudentGrade};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class AcademicEntryService {
 public function __construct(private AcademicAccessService $access){}
 public function saveAttendance(SaveAttendanceRequest $r):void{$this->access->ensureClassroom($r->user(),$r->integer('classroom_id'));$this->validateMembers($r->integer('classroom_id'),collect($r->input('attendances'))->pluck('student_id')->all());DB::transaction(function()use($r){foreach($r->input('attendances') as $row){$existing=StudentAttendance::where(['student_id'=>$row['student_id'],'classroom_id'=>$r->integer('classroom_id'),'attendance_date'=>$r->date('attendance_date')])->first();StudentAttendance::updateOrCreate(['student_id'=>$row['student_id'],'classroom_id'=>$r->integer('classroom_id'),'attendance_date'=>$r->date('attendance_date')],['academic_year_id'=>$r->integer('academic_year_id'),'semester_id'=>$r->integer('semester_id'),'status'=>$row['status'],'notes'=>$row['notes']??null,'recorded_by'=>$existing?->recorded_by??$r->user()->id,'updated_by'=>$existing?$r->user()->id:null]);}activity('akademik')->causedBy($r->user())->withProperties(['classroom_id'=>$r->integer('classroom_id'),'date'=>$r->input('attendance_date')])->log($existing??false?'Mengubah absensi':'Menyimpan absensi');});}
 public function saveGrades(SaveGradesRequest $r):void{$this->access->ensureClassroom($r->user(),$r->integer('classroom_id'));$this->validateMembers($r->integer('classroom_id'),collect($r->input('grades'))->pluck('student_id')->all());DB::transaction(function()use($r){$changed=false;foreach($r->input('grades') as $row){$key=['semester_id'=>$r->integer('semester_id'),'classroom_id'=>$r->integer('classroom_id'),'student_id'=>$row['student_id'],'academic_subject_id'=>$r->integer('academic_subject_id')];$old=StudentGrade::where($key)->first();$changed=$changed||isset($old);StudentGrade::updateOrCreate($key,['academic_year_id'=>$r->integer('academic_year_id'),'score'=>$row['score']??null,'notes'=>$row['notes']??null,'recorded_by'=>$old?->recorded_by??$r->user()->id,'updated_by'=>$old?$r->user()->id:null]);}activity('akademik')->causedBy($r->user())->withProperties(['classroom_id'=>$r->integer('classroom_id'),'subject_id'=>$r->integer('academic_subject_id')])->log($changed?'Mengubah daftar nilai':'Menyimpan daftar nilai');});}
 private function validateMembers(int $room,array $students):void{$valid=ClassroomMembership::where('classroom_id',$room)->where('status','active')->whereIn('student_id',$students)->pluck('student_id');if($valid->count()!==count(array_unique($students)))throw ValidationException::withMessages(['students'=>'Terdapat siswa yang bukan anggota aktif rombel ini.']);}
}
