<?php
declare(strict_types=1); namespace App\Services\Personnel;
use App\Models\{Personnel,PersonnelImportBatch,PersonnelImportRow,User}; use Carbon\Carbon; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\{DB,Storage,Validator};
class PersonnelImportService
{
 public const HEADERS=['NO','NAMA LENGKAP','L/P','TEMPAT TGL LAHIR','STATUS','NOMOR INDUK YAYASAN (NIY)','NIP','PANGKAT/GOLONGAN RUANG','PEG ID','PENDIDIKAN TERAKHIR','JABATAN','SERTIFIKASI IMPASSING','MAPEL SERTIFIKASI','JUMLAH JPL','JENIS REKENING','NO REKENING','NO HP/WA AKTIF','EMAIL AKTIF'];
 public function __construct(private SimpleXlsxService $xlsx,private PersonnelDuplicateService $duplicates){}
 public function preview(UploadedFile $file,string $strategy,User $actor):PersonnelImportBatch{$stored=$file->store('personnel-imports','local');$batch=PersonnelImportBatch::create(['user_id'=>$actor->id,'original_filename'=>$file->getClientOriginalName(),'stored_filename'=>$stored,'status'=>'uploaded','duplicate_strategy'=>$strategy]);try{$sheets=$this->xlsx->read(Storage::disk('local')->path($stored));[$rows,$header]=$this->locate($sheets);foreach($rows as $number=>$raw){if($number<=$header||collect($raw)->filter(fn($v)=>trim((string)$v)!=='')->isEmpty())continue;$mapped=$this->map($rows[$header],$raw);$normalized=$this->normalize($mapped);[$status,$messages,$match]=$this->validate($normalized);PersonnelImportRow::create(['batch_id'=>$batch->id,'row_number'=>$number,'raw_data'=>$mapped,'normalized_data'=>$normalized,'status'=>$status,'messages'=>$messages,'matched_personnel_id'=>$match?->id]);}$this->summarize($batch,'previewed');return $batch->fresh();}catch(\Throwable $e){Storage::disk('local')->delete($stored);$batch->update(['status'=>'failed']);throw $e;}}
 public function confirm(PersonnelImportBatch $batch,User $actor):PersonnelImportBatch{abort_unless($batch->user_id===$actor->id&&$batch->status==='previewed',403);$batch->update(['status'=>'processing','started_at'=>now()]);$counts=['imported_rows'=>0,'updated_rows'=>0,'skipped_rows'=>0,'failed_rows'=>0];$batch->rows()->whereIn('status',['valid','warning','duplicate'])->orderBy('id')->chunk(200,function($rows)use($batch,$actor,&$counts){DB::transaction(function()use($rows,$batch,$actor,&$counts){foreach($rows as $row){try{$data=array_filter($row->normalized_data,fn($v)=>$v!==null&&$v!=='');if($row->matched_personnel_id){if($batch->duplicate_strategy==='skip'){$counts['skipped_rows']++;continue;}unset($data['user_id'],$data['is_active']);$data['updated_by']=$actor->id;Personnel::whereKey($row->matched_personnel_id)->update($data);$counts['updated_rows']++;}else{Personnel::create([...$data,'is_active'=>true,'created_by'=>$actor->id,'updated_by'=>$actor->id]);$counts['imported_rows']++;}}catch(\Throwable){$counts['failed_rows']++;}}});});$batch->update([...$counts,'status'=>'completed','completed_at'=>now(),'summary'=>$counts]);Storage::disk('local')->delete($batch->stored_filename);activity('personnel')->causedBy($actor)->log('Mengimpor '.($counts['imported_rows']+$counts['updated_rows']).' data personalia dari file XLSX.');return $batch->fresh();}
 public function parseBirth(mixed $value):array{$v=trim((string)$value);if($v==='')return [null,null,null];if(is_numeric($v)){try{return [null,Carbon::create(1899,12,30)->addDays((int)$v)->format('Y-m-d'),null];}catch(\Throwable){}}$months=['JANUARI'=>1,'FEBRUARI'=>2,'MARET'=>3,'APRIL'=>4,'MEI'=>5,'JUNI'=>6,'JULI'=>7,'AGUSTUS'=>8,'SEPTEMBER'=>9,'OKTOBER'=>10,'NOVEMBER'=>11,'DESEMBER'=>12];if(preg_match('/^(.*?),\s*(\d{1,2})\s+('.implode('|',array_keys($months)).')\s+(\d{4})$/iu',$v,$m))return [trim($m[1]),sprintf('%04d-%02d-%02d',$m[4],$months[strtoupper($m[3])],$m[2]),null];if(preg_match('/^(.*?),\s*(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/',$v,$m))return [trim($m[1]),sprintf('%04d-%02d-%02d',$m[4],$m[3],$m[2]),null];if(preg_match('/^(.*?),\s*(\d{4}-\d{2}-\d{2})$/',$v,$m))return [trim($m[1]),$m[2],null];return [$v,null,'Format tanggal lahir tidak dapat dibaca.'];}
 private function locate(array $sheets):array{foreach($sheets as $rows)foreach($rows as $n=>$row){$norm=array_map(fn($v)=>$this->header($v),$row);if(count(array_intersect($norm,self::HEADERS))>=8)return [$rows,$n];}throw new \RuntimeException('Header Data Personalia tidak ditemukan.');}
 private function header($v):string{$v=strtoupper(trim(preg_replace('/\s+/',' ',str_replace(["\r","\n",'.','-'],[' ',' ','',' '],(string)$v))));return match($v){'E MAIL AKTIF','EMAIL AKTIF'=>'EMAIL AKTIF','PEGID','PEG ID','PEGAWAI ID'=>'PEG ID','NO HP/WA AKTIF'=>'NO HP/WA AKTIF','TEMPAT, TGL LAHIR','TEMPAT, TGL LAHIR '=>'TEMPAT TGL LAHIR','NO REKENING'=>'NO REKENING','SERTIFIKASI IMPASSING'=>'SERTIFIKASI IMPASSING',default=>$v};}
 private function map(array $headers,array $row):array{$keys=['NAMA LENGKAP'=>'full_name','L/P'=>'gender','TEMPAT TGL LAHIR'=>'birth','STATUS'=>'employment_status','NOMOR INDUK YAYASAN (NIY)'=>'foundation_employee_number','NIP'=>'nip','PANGKAT/GOLONGAN RUANG'=>'rank_grade','PEG ID'=>'external_employee_id','PENDIDIKAN TERAKHIR'=>'last_education','JABATAN'=>'position','SERTIFIKASI IMPASSING'=>'certification_status','MAPEL SERTIFIKASI'=>'certification_subject','JUMLAH JPL'=>'weekly_teaching_hours','JENIS REKENING'=>'bank_name','NO REKENING'=>'bank_account_number','NO HP/WA AKTIF'=>'phone','EMAIL AKTIF'=>'email'];$out=[];foreach($headers as $column=>$value)if(isset($keys[$this->header($value)]))$out[$keys[$this->header($value)]]=$row[$column]??null;return $out;}
 private function normalize(array $d):array{foreach($d as &$v)$v=is_string($v)?trim($v," \t\n\r\0\x0B'"): $v;[$d['birth_place'],$d['birth_date'],$warning]=$this->parseBirth($d['birth']??null);unset($d['birth']);$g=strtoupper((string)($d['gender']??''));$d['gender']=in_array($g,['L','LAKI-LAKI','PRIA'])?'male':(in_array($g,['P','PEREMPUAN','WANITA'])?'female':$g);$d['employment_status']=strtoupper((string)($d['employment_status']??''));$d['email']=strtolower((string)($d['email']??''))?:null;$d['phone']=str_replace(' ','',(string)($d['phone']??''))?:null;foreach(['foundation_employee_number','nip','external_employee_id','bank_account_number'] as $k){$d[$k]=isset($d[$k])?preg_replace('/\.0$/','',(string)$d[$k]):null;}if(isset($d['weekly_teaching_hours'])&&$d['weekly_teaching_hours']!=='')$d['weekly_teaching_hours']=is_numeric($d['weekly_teaching_hours'])?(int)$d['weekly_teaching_hours']:$d['weekly_teaching_hours'];else $d['weekly_teaching_hours']=null;$d['_birth_warning']=$warning;return $d;}
 private function validate(array $d):array{$warning=array_filter([$d['_birth_warning']??null]);unset($d['_birth_warning']);$v=Validator::make($d,['full_name'=>'required|max:200','gender'=>'required|in:male,female','employment_status'=>'required|max:50','position'=>'required|max:150','email'=>'nullable|email|max:200','weekly_teaching_hours'=>'nullable|integer|between:0,100']);$messages=$v->errors()->all();$dup=$this->duplicates->find($d);if($dup['conflict'])$messages[]='Data memiliki beberapa kecocokan berbeda dan harus diperiksa manual.';$status=$messages?'invalid':($dup['match']?'duplicate':($warning?'warning':'valid'));return [$status,[...$messages,...$warning],$dup['match']];}
 private function summarize(PersonnelImportBatch $b,string $status):void{$q=$b->rows();$b->update(['status'=>$status,'total_rows'=>(clone $q)->count(),'valid_rows'=>(clone $q)->where('status','valid')->count(),'warning_rows'=>(clone $q)->where('status','warning')->count(),'invalid_rows'=>(clone $q)->where('status','invalid')->count(),'duplicate_rows'=>(clone $q)->where('status','duplicate')->count()]);}
}
