<?php
declare(strict_types=1); namespace App\Services\Students;
use App\Models\{Student,StudentImportBatch,StudentImportRow,User}; use App\Services\Personnel\SimpleXlsxService; use Carbon\Carbon; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\{DB,Storage,Validator};
class StudentImportService
{
 public function __construct(private SimpleXlsxService $xlsx,private StudentDuplicateService $duplicates){}
 public function preview(UploadedFile $file,string $strategy,User $actor):StudentImportBatch{$stored=$file->store('student-imports','local');$batch=StudentImportBatch::create(['user_id'=>$actor->id,'original_filename'=>$file->getClientOriginalName(),'stored_filename'=>$stored,'status'=>'uploaded','duplicate_strategy'=>$strategy]);try{[$rows,$header]=$this->locate($this->xlsx->read(Storage::disk('local')->path($stored)));foreach($rows as $number=>$raw){if($number<=$header||collect($raw)->filter(fn($v)=>trim((string)$v)!=='')->isEmpty())continue;$mapped=$this->map($rows[$header],$raw);$normalized=$this->normalize($mapped);[$status,$messages,$match]=$this->validate($normalized);StudentImportRow::create(['batch_id'=>$batch->id,'row_number'=>$number,'raw_data'=>$mapped,'normalized_data'=>$normalized,'status'=>$status,'messages'=>$messages,'matched_student_id'=>$match?->id]);}$this->summarize($batch);return $batch->fresh();}catch(\Throwable $e){Storage::disk('local')->delete($stored);$batch->update(['status'=>'failed']);throw $e;}}
 public function confirm(StudentImportBatch $batch,User $actor):StudentImportBatch{abort_unless($batch->user_id===$actor->id&&$batch->status==='previewed',403);$counts=['imported_rows'=>0,'updated_rows'=>0,'skipped_rows'=>0,'failed_rows'=>0];$batch->update(['status'=>'processing','started_at'=>now()]);$batch->rows()->whereIn('status',['valid','warning','duplicate'])->orderBy('id')->chunk(200,function($rows)use($batch,$actor,&$counts){DB::transaction(function()use($rows,$batch,$actor,&$counts){foreach($rows as $row){try{$data=array_filter($row->normalized_data,fn($v)=>$v!==null&&$v!=='');if($row->matched_student_id){if($batch->duplicate_strategy==='skip'){$counts['skipped_rows']++;continue;}$data['updated_by']=$actor->id;Student::whereKey($row->matched_student_id)->update($data);$counts['updated_rows']++;}else{Student::create([...$data,'created_by'=>$actor->id,'updated_by'=>$actor->id]);$counts['imported_rows']++;}}catch(\Throwable){$counts['failed_rows']++;}}});});$batch->update([...$counts,'status'=>'completed','completed_at'=>now(),'summary'=>$counts]);Storage::disk('local')->delete($batch->stored_filename);activity('students')->causedBy($actor)->log('Mengimpor '.($counts['imported_rows']+$counts['updated_rows']).' data siswa dari file XLSX.');return $batch->fresh();}
 public function normalizeHeader(mixed $value):string{$value=mb_strtoupper(trim(preg_replace('/\s+/u',' ',str_replace(["\r","\n",'.','–','—','-','/'],[' ',' ',' ',' ',' ',' ',' '],(string)$value))));return match($value){'NO TELEPON','NOMOR TELEPON','NO HP'=>'NO TELEPON','NOMOR KIP PIP'=>'NOMOR KIP/PIP','TINGKAT ROMBEL'=>'TINGKAT - ROMBEL',default=>$value};}
 public function normalize(array $data):array{foreach($data as $key=>$value){$value=is_string($value)?trim($value," \t\n\r\0\x0B'"):$value;$data[$key]=$this->nullable($value);}$data['nisn']=$this->number($data['nisn']??null);$data['nik']=$this->number($data['nik']??null);$data['phone']=$this->number($data['phone']??null);$data['kip_pip_number']=$this->number($data['kip_pip_number']??null);$gender=mb_strtoupper((string)($data['gender']??''));$data['gender']=in_array($gender,['L','LAKI-LAKI','LAKI LAKI','PRIA'],true)?'male':(in_array($gender,['P','PEREMPUAN','WANITA'],true)?'female':$gender);$status=str_replace(' ','',mb_strtoupper((string)($data['status']??'')));$data['status']=match($status){'','AKTIF'=>'active','NONAKTIF'=>'inactive','LULUS'=>'graduated','PINDAH'=>'transferred','KELUAR'=>'withdrawn','MENINGGAL'=>'deceased',default=>mb_strtolower($status)};$data['birth_date']=$this->date($data['birth_date']??null);return $data;}
 public function date(mixed $value):?string{if(blank($value))return null;if(is_numeric($value))return Carbon::create(1899,12,30)->addDays((int)$value)->format('Y-m-d');$v=trim((string)$value);foreach(['d/m/Y','d-m-Y','Y-m-d','d F Y'] as $format){try{$date=Carbon::createFromLocaleFormat($format,'id',$v);if($date)return $date->format('Y-m-d');}catch(\Throwable){}}try{return Carbon::parse($v)->format('Y-m-d');}catch(\Throwable){return null;}}
 private function locate(array $sheets):array{foreach($sheets as $rows)foreach($rows as $number=>$row){$headers=array_map(fn($v)=>$this->normalizeHeader($v),$row);if(in_array('NAMA LENGKAP',$headers,true)&&count(array_intersect($headers,StudentExportService::HEADERS))>=8)return [$rows,$number];}throw new \RuntimeException('Header Data Siswa tidak ditemukan.');}
 private function map(array $headers,array $row):array{$map=['NAMA LENGKAP'=>'full_name','NISN'=>'nisn','NIK'=>'nik','TEMPAT LAHIR'=>'birth_place','TANGGAL LAHIR'=>'birth_date','TINGKAT - ROMBEL'=>'classroom_label','STATUS'=>'status','JENIS KELAMIN'=>'gender','ALAMAT'=>'address','NO TELEPON'=>'phone','KEBUTUHAN KHUSUS'=>'special_needs','DISABILITAS'=>'disability','NOMOR KIP/PIP'=>'kip_pip_number','NAMA AYAH KANDUNG'=>'father_name','NAMA IBU KANDUNG'=>'mother_name','NAMA WALI'=>'guardian_name'];$out=[];foreach($headers as $column=>$header)if(isset($map[$this->normalizeHeader($header)]))$out[$map[$this->normalizeHeader($header)]]=$row[$column]??null;return $out;}
 private function nullable(mixed $value):?string{if($value===null)return null;$value=trim((string)$value);return $value===''||in_array(mb_strtoupper($value),config('students.empty_placeholders'),true)?null:$value;}
 private function number(mixed $value):?string{$value=$this->nullable($value);return $value===null?null:preg_replace('/\.0$/','',$value);}
 private function validate(array $data):array{$validator=Validator::make($data,['full_name'=>'required|string|max:200','gender'=>'required|in:male,female','status'=>'required|in:'.implode(',',array_keys(config('students.statuses'))),'birth_date'=>'nullable|date|before_or_equal:today']);$messages=$validator->errors()->all();$duplicate=$this->duplicates->find($data);if($duplicate['conflict'])$messages[]=$duplicate['message'];elseif($duplicate['match'])$messages[]='Data sudah tersedia berdasarkan '.match($duplicate['matched_by']){'nisn'=>'NISN','nik'=>'NIK',default=>'nama dan tanggal lahir'}.'.';$status=$validator->fails()||$duplicate['conflict']?'invalid':($duplicate['match']?'duplicate':'valid');return [$status,$messages,$duplicate['match']];}
 private function summarize(StudentImportBatch $batch):void{$q=$batch->rows();$batch->update(['status'=>'previewed','total_rows'=>(clone$q)->count(),'valid_rows'=>(clone$q)->where('status','valid')->count(),'warning_rows'=>(clone$q)->where('status','warning')->count(),'invalid_rows'=>(clone$q)->where('status','invalid')->count(),'duplicate_rows'=>(clone$q)->where('status','duplicate')->count()]);}
}
