<x-app-layout title="Detail Izin">
    <div class="mb-6"><p class="text-sm text-slate-500">Absensi / Perizinan Guru</p><h1 class="text-2xl font-semibold text-emerald-950">Detail Izin</h1></div>
    @if (session('status'))<div class="mb-4 rounded-lg bg-emerald-50 p-4 text-emerald-900">{{ session('status') }}</div>@endif
    <x-ui.card>
        <dl class="grid gap-4 md:grid-cols-2"><div><dt class="text-sm text-slate-500">Pegawai</dt><dd>{{ $leave->employee->name }}</dd></div><div><dt class="text-sm text-slate-500">Status</dt><dd><x-ui.badge>{{ $leave->status->value }}</x-ui.badge></dd></div><div><dt class="text-sm text-slate-500">Tanggal</dt><dd>{{ $leave->starts_at->format('d/m/Y') }} - {{ $leave->ends_at->format('d/m/Y') }}</dd></div><div><dt class="text-sm text-slate-500">Alasan</dt><dd>{{ $leave->reason }}</dd></div></dl>
        @if ($leave->attachment_path)<a class="mt-4 inline-flex text-emerald-800 hover:text-emerald-700" href="{{ route('employee-leaves.download', $leave) }}">Unduh lampiran</a>@endif
        <div class="mt-6 flex flex-wrap gap-3"><form method="post" action="{{ route('employee-leaves.approve', $leave) }}">@csrf @method('patch')<button class="rounded-lg bg-emerald-900 px-4 py-2 text-white hover:bg-emerald-800">Setujui</button></form><form class="flex gap-2" method="post" action="{{ route('employee-leaves.reject', $leave) }}">@csrf @method('patch')<input class="rounded-lg border-slate-300" name="rejection_reason" placeholder="Alasan penolakan" required><button class="rounded-lg bg-red-700 px-4 py-2 text-white hover:bg-red-600">Tolak</button></form><form method="post" action="{{ route('employee-leaves.cancel', $leave) }}">@csrf @method('patch')<button class="rounded-lg border px-4 py-2 hover:bg-slate-50">Batalkan</button></form></div>
    </x-ui.card>
</x-app-layout>
