<?php
declare(strict_types=1);
namespace App\Http\Controllers\Hrd;
use App\Exceptions\AttendanceSecurityException;use App\Http\Controllers\Controller;use App\Http\Requests\Hrd\SelfAttendanceRequest;use App\Models\PersonnelAttendance;use App\Services\Hrd\{AttendanceSecurityService,AttendanceService};use App\Services\Settings\ApplicationSettingService;use Illuminate\Http\{JsonResponse,Request};use Illuminate\View\View;
class PersonnelAttendanceController extends Controller
{
 public function index(Request $r):View{$q=PersonnelAttendance::with('personnel')->latest('attendance_date')->latest('check_in_time');foreach(['status','method','shift_number']as$f)if($r->filled($f))$q->where($f,$r->$f);return view('hrd.attendance.index',['title'=>'Absensi Pegawai','attendances'=>$q->paginate(20)->withQueryString()]);}
 public function mine(Request $r,ApplicationSettingService $settings):View{$p=$this->personnel($r);return view('hrd.attendance.mine',['title'=>'Absensi Saya','personnel'=>$p,'attendance'=>$p->attendances()->whereDate('attendance_date',today())->first(),'security'=>$settings->all()]);}
 public function challenge(Request $r,AttendanceSecurityService $security):JsonResponse{$r->validate(['action'=>['required','in:check_in,check_out'],'device_uuid'=>['nullable','uuid'],'device_name'=>['nullable','string','max:100'],'browser'=>['nullable','string','max:80'],'platform'=>['nullable','string','max:80']]);return response()->json(['data'=>$security->challenge($r->user(),$this->personnel($r),$r->string('action')->toString(),$r)]);}
 public function face(Request $r,AttendanceSecurityService $security):JsonResponse{$r->validate(['challenge_id'=>['required','uuid'],'nonce'=>['required','string','size:64'],'device_uuid'=>['nullable','uuid'],'snapshot'=>['required','image','max:3072']]);$verification=$security->verifyFace($r->user(),$this->personnel($r),$r->string('challenge_id')->toString(),$r->string('nonce')->toString(),$r->file('snapshot'),$r);return response()->json(['data'=>['verified'=>true,'expires_at'=>$verification->expires_at->toIso8601String()]]);}
 public function checkIn(SelfAttendanceRequest $r,AttendanceService $s):JsonResponse{return $this->submit($r,$s,'check_in');}
 public function checkOut(SelfAttendanceRequest $r,AttendanceService $s):JsonResponse{return $this->submit($r,$s,'check_out');}
 private function submit(SelfAttendanceRequest $r,AttendanceService $s,string $action):JsonResponse{$row=$s->submit($this->personnel($r),$r->user(),$action,$r->validated(),$r);return response()->json(['data'=>['message'=>$action==='check_in'?'Check-in berhasil dicatat.':'Check-out berhasil dicatat.','time'=>($action==='check_in'?$row->check_in_time:$row->check_out_time)?->format('H:i'),'distance'=>$action==='check_in'?$row->check_in_distance:$row->check_out_distance]]);}
 private function personnel(Request $r){$p=$r->user()->personnel;if(!$p)throw new AttendanceSecurityException('PERSONNEL_NOT_LINKED','Akun belum terhubung dengan personalia.',403);if(!$p->is_active)throw new AttendanceSecurityException('PERSONNEL_INACTIVE','Status personalia tidak aktif.',403);return$p;}
}
