<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $title }} — {{ $school->display_name }}</title>
<style>
@page{size:A4 portrait;margin:15mm}*{box-sizing:border-box;box-shadow:none!important}html,body{margin:0;background:#e5e7eb;color:#000;font-family:Arial,"Liberation Sans",sans-serif;font-size:10pt;line-height:1.3}.toolbar{width:180mm;margin:10px auto;display:flex;gap:8px}.toolbar a,.toolbar button{border:1px solid #222;background:#fff;color:#000;padding:7px 13px;font:inherit;text-decoration:none;cursor:pointer}.paper{width:210mm;min-height:297mm;margin:0 auto 20px;padding:15mm;background:#fff}.letterhead{position:relative;min-height:27mm;padding:0 18mm 3mm;border-bottom:3px double #000;text-align:center}.letterhead img{position:absolute;left:0;top:0;width:19mm;max-height:23mm;object-fit:contain}.letterhead h1{margin:0;font-size:14pt;text-transform:uppercase}.letterhead p{margin:2px 0}.document-title{margin:8mm 0 4mm;text-align:center}.document-title h2{margin:0 0 2mm;font-size:13pt;text-decoration:underline}.meta{margin:0 auto;width:auto}.meta td{border:0;padding:1px 4px}h3{margin:6mm 0 2mm;font-size:10pt}table{width:100%;border-collapse:collapse}th,td{border:1px solid #000;padding:3px 4px;vertical-align:top}th{text-align:center;font-weight:700}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}.number{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}.center{text-align:center}.attendance{table-layout:fixed;font-size:8pt}.attendance .no{width:5%}.attendance .name{width:16%}.attendance .date{width:10%}.attendance .status{width:10%}.attendance .time{width:8%}.attendance .duration{width:10%}.attendance .minutes{width:8%}.attendance .note{width:17%;overflow-wrap:anywhere}.signatures{margin-top:12mm;break-inside:avoid}.signatures td{width:50%;border:0;padding-right:10mm}.signature-space{height:30mm}.identity{text-decoration:underline;font-weight:bold}@media print{html,body{background:#fff}.no-print{display:none!important}.paper{width:auto;min-height:auto;margin:0;padding:0}}@media screen and (max-width:800px){.toolbar,.paper{width:100%}.paper{min-height:auto;padding:12px}}
</style></head><body>
<nav class="toolbar no-print" aria-label="Tindakan cetak"><a href="{{ route('hrd.reports.index',['start_date'=>$start->format('Y-m-d'),'end_date'=>$end->format('Y-m-d')]) }}">Kembali</a><button type="button" onclick="window.print()">Cetak</button></nav>
<main class="paper">
<header class="letterhead">@if($school->logo_url)<img src="{{ $school->logo_url }}" alt="Logo {{ $school->display_name }}">@endif<h1>{{ $school->name }}</h1>@if($school->nsm||$school->npsn)<p>@if($school->nsm)NSM: {{ $school->nsm }}@endif @if($school->nsm&&$school->npsn) | @endif @if($school->npsn)NPSN: {{ $school->npsn }}@endif</p>@endif @if($school->display_address)<p>{{ $school->display_address }}</p>@endif @if($school->phone||$school->email||$school->website)<p>{{ collect([$school->phone?'Telepon: '.$school->phone:null,$school->email?'Email: '.$school->email:null,$school->website?'Website: '.$school->website:null])->filter()->join(' | ') }}</p>@endif</header>
<section class="document-title"><h2>LAPORAN HRD / KEPEGAWAIAN</h2><table class="meta"><tr><td>Periode</td><td>:</td><td>{{ $start->locale('id')->translatedFormat('j F Y') }} s.d. {{ $end->locale('id')->translatedFormat('j F Y') }}</td></tr>@if($academicYear)<tr><td>Tahun Pelajaran</td><td>:</td><td>{{ $academicYear->name }}</td></tr>@endif @if($semester)<tr><td>Semester</td><td>:</td><td>{{ $semester->type->label() }}</td></tr>@endif</table></section>
<h3>I. RINGKASAN KEPEGAWAIAN</h3><table><thead><tr><th>No.</th><th>Uraian</th><th>Jumlah / Nilai</th></tr></thead><tbody>@foreach(['Jumlah Pegawai Payroll'=>(int)($payrollSummary->employees??0),'Total Gaji Bersih'=>'Rp '.number_format((float)($payrollSummary->net??0),0,',','.'),'Total Kasbon Dicairkan'=>'Rp '.number_format((float)($advanceSummary->disbursed??0),0,',','.'),'Sisa Kasbon'=>'Rp '.number_format((float)($advanceSummary->remaining??0),0,',','.')] as $label=>$value)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $label }}</td><td class="number">{{ $value }}</td></tr>@endforeach</tbody></table>
<h3>II. REKAPITULASI KEHADIRAN</h3><table><thead><tr><th>No.</th><th>Uraian</th><th>Jumlah</th></tr></thead><tbody>@foreach(\App\Enums\Hrd\AttendanceStatus::cases() as $status)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $status->label() }}</td><td class="number">{{ $attendanceSummary[$status->value]??0 }}</td></tr>@endforeach<tr><td class="center">8</td><td>Total Keterlambatan</td><td class="number">{{ (int)($minutes->late??0) }} menit</td></tr><tr><td class="center">9</td><td>Total Lembur</td><td class="number">{{ (int)($minutes->overtime??0) }} menit</td></tr></tbody></table>
<h3>III. RINCIAN KEHADIRAN PEGAWAI</h3><table class="attendance"><thead><tr><th class="no">No.</th><th class="name">Nama Pegawai</th><th class="date">Tanggal</th><th class="status">Status</th><th class="time">Masuk</th><th class="time">Pulang</th><th class="duration">Durasi Kerja</th><th class="minutes">Terlambat</th><th class="minutes">Lembur</th><th class="note">Keterangan</th></tr></thead><tbody>@forelse($attendances as $attendance)@php($worked=$attendance->check_in_time&&$attendance->check_out_time?max(0,(int)$attendance->check_in_time->diffInMinutes($attendance->check_out_time)):null)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $attendance->personnel->full_name }}</td><td class="center">{{ $attendance->attendance_date->format('d-m-Y') }}</td><td>{{ $attendance->status->label() }}</td><td class="center">{{ $attendance->check_in_time?->format('H.i')??'-' }}</td><td class="center">{{ $attendance->check_out_time?->format('H.i')??'-' }}</td><td class="number">{{ $worked===null?'-':intdiv($worked,60).' jam '.($worked%60).' menit' }}</td><td class="number">{{ $attendance->late_minutes?$attendance->late_minutes.' menit':'-' }}</td><td class="number">{{ $attendance->overtime_minutes?$attendance->overtime_minutes.' menit':'-' }}</td><td>{{ $attendance->note?:'-' }}</td></tr>@empty<tr><td colspan="10" class="center">Tidak ada data kehadiran pada periode ini.</td></tr>@endforelse</tbody></table>
@if($leaveSummary->isNotEmpty())<h3>IV. REKAPITULASI CUTI / IZIN PEGAWAI</h3><table><thead><tr><th>No.</th><th>Jenis Cuti / Izin</th><th>Jumlah Pengajuan</th></tr></thead><tbody>@foreach($leaveSummary as $type=>$total)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ \App\Enums\Hrd\LeaveType::from($type)->label() }}</td><td class="number">{{ $total }}</td></tr>@endforeach</tbody></table>@endif
<h3>V. RINGKASAN PENGGAJIAN</h3><table><thead><tr><th>No.</th><th>Uraian</th><th>Nilai</th></tr></thead><tbody>@foreach(['Jumlah Pegawai'=>(int)($payrollSummary->employees??0),'Total Gaji Pokok'=>'Rp '.number_format((float)($payrollSummary->base??0),0,',','.'),'Total Tunjangan'=>'Rp '.number_format((float)($payrollSummary->allowance??0),0,',','.'),'Total Potongan'=>'Rp '.number_format((float)($payrollSummary->deductions??0),0,',','.'),'Potongan Kasbon'=>'Rp '.number_format((float)($payrollSummary->cash_advance??0),0,',','.'),'Total Gaji Bersih'=>'Rp '.number_format((float)($payrollSummary->net??0),0,',','.')] as $label=>$value)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $label }}</td><td class="number">{{ $value }}</td></tr>@endforeach</tbody></table>
<h3>VI. RINGKASAN KASBON PEGAWAI</h3><table><thead><tr><th>No.</th><th>Uraian</th><th>Nilai</th></tr></thead><tbody>@foreach(['Total Dicairkan'=>$advanceSummary->disbursed??0,'Total Dibayar'=>$advanceSummary->paid??0,'Sisa Kasbon'=>$advanceSummary->remaining??0] as $label=>$value)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $label }}</td><td class="number">Rp {{ number_format((float)$value,0,',','.') }}</td></tr>@endforeach</tbody></table>
<table class="signatures"><tr><td>Mengetahui,<br>Kepala Madrasah,<div class="signature-space"></div><span class="identity">{{ $school->head_name?:'........................................' }}</span>@if($school->head_nip)<br>NIP {{ $school->head_nip }}@endif</td><td>{{ $school->city?$school->city.', ':'' }}{{ $end->locale('id')->translatedFormat('j F Y') }}<br>Petugas/Administrator,<div class="signature-space"></div><span class="identity">{{ $officer?->full_name?:'........................................' }}</span>@if($officer?->nip)<br>NIP {{ $officer->nip }}@endif @if($officer?->position)<br>{{ $officer->position }}@endif</td></tr></table>
</main></body></html>
