<div><h2 class="text-lg font-bold text-emerald-950">Integrasi Bank BRI</h2><p class="text-sm text-slate-500">Konfigurasi SNAP BI disimpan secara aman. Secret dan private key tidak pernah ditampilkan kembali.</p></div>
<div class="grid gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm md:grid-cols-4">
 @foreach(['Integrasi BRI'=>$bri->enabled()?'Aktif':'Nonaktif','Environment'=>ucfirst($bri->environment()),'BRIVA'=>$bri->brivaEnabled()?'Aktif':'Nonaktif','Payroll Transfer'=>$bri->payrollEnabled()?'Aktif':'Nonaktif','Client ID'=>$bri->clientId()?'Tersedia':'Belum tersedia','Partner ID'=>$bri->partnerId()?'Tersedia':'Belum tersedia','Private Key'=>$bri->hasPrivateKey()?'Tersedia':'Belum tersedia','Koneksi Terakhir'=>$briSetting?->last_connection_at?->format('d/m/Y H:i')??'Belum diuji'] as $label=>$value)
 <div><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-1 font-bold text-emerald-950">{{ $value }}</p></div>@endforeach
</div>
<div class="grid gap-4 md:grid-cols-2">
 <label class="flex justify-between rounded-xl border p-4"><span>Status Integrasi</span><span><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked(old('enabled',$bri->enabled()))></span></label>
 <div><label>Environment</label><select name="environment"><option value="sandbox" @selected(old('environment',$bri->environment())==='sandbox')>Sandbox</option><option value="production" @selected(old('environment',$bri->environment())==='production')>Production</option></select></div>
 <div class="md:col-span-2"><label>Base URL</label><input type="url" name="base_url" value="{{ old('base_url',$bri->baseUrl()) }}"></div>
 <div><label>Client ID / X-CLIENT-KEY</label><input name="client_id" value="{{ old('client_id',$bri->clientId()) }}"></div><div><label>Partner ID / X-PARTNER-ID</label><input name="partner_id" value="{{ old('partner_id',$bri->partnerId()) }}"></div>
 <div><label>Channel ID</label><input name="channel_id" value="{{ old('channel_id',$bri->channelId()) }}"></div><div><label>Client Secret Baru</label><input type="password" name="client_secret" autocomplete="new-password"><p class="text-xs text-slate-500">Status: {{ $bri->clientSecret()?'Sudah dikonfigurasi':'Belum dikonfigurasi' }}</p></div>
 <div><label>Private Key (PEM)</label><input type="file" name="private_key" accept=".pem"><p class="text-xs text-slate-500">{{ $bri->hasPrivateKey()?'Sudah tersedia':'Belum tersedia' }}</p></div><div><label>Public Key (PEM)</label><input type="file" name="public_key" accept=".pem"><p class="text-xs text-slate-500">{{ $bri->hasPublicKey()?'Sudah tersedia':'Belum tersedia' }}</p></div>
</div>
<div class="border-t pt-5"><h3 class="font-bold text-emerald-950">BRIVA / Virtual Account</h3><div class="mt-3 grid gap-4 md:grid-cols-2">
 <label class="flex justify-between rounded-xl border p-4"><span>Aktifkan BRIVA</span><span><input type="hidden" name="briva_enabled" value="0"><input type="checkbox" name="briva_enabled" value="1" @checked(old('briva_enabled',$bri->brivaEnabled()))></span></label>
 <div><label>Mode VA</label><select name="briva_mode"><option value="per_student" @selected(old('briva_mode',$briSetting?->briva_mode??config('bri.briva.mode'))==='per_student')>per_student</option><option value="per_invoice" @selected(old('briva_mode',$briSetting?->briva_mode)==='per_invoice')>per_invoice</option></select></div>
 <div><label>Partner Service ID</label><input name="partner_service_id" value="{{ old('partner_service_id',$briSetting?->partner_service_id) }}"></div><div><label>Institution/Company Code</label><input name="institution_code" value="{{ old('institution_code',$briSetting?->institution_code??config('bri.briva.institution_code')) }}"></div><div><label>Prefix Customer Number</label><input name="customer_number_prefix" value="{{ old('customer_number_prefix',$briSetting?->customer_number_prefix) }}"></div>
</div></div>
<div class="border-t pt-5"><h3 class="font-bold text-emerald-950">Pembayaran Payroll via BRI</h3><div class="mt-3 grid gap-4 md:grid-cols-2">
 <label class="flex justify-between rounded-xl border p-4"><span>Aktifkan pembayaran payroll BRI</span><span><input type="hidden" name="payroll_enabled" value="0"><input type="checkbox" name="payroll_enabled" value="1" @checked(old('payroll_enabled',$bri->payrollEnabled()))></span></label>
 <div><label>Source Account Baru</label><input type="password" name="source_account" autocomplete="new-password"><p class="text-xs text-slate-500">Nomor rekening terenkripsi dan tidak ditampilkan kembali.</p></div><div><label>Metode</label><select name="payroll_method"><option value="internal_bri" @selected(old('payroll_method',$briSetting?->payroll_method)==='internal_bri')>Transfer Internal BRI</option><option value="interbank" @selected(old('payroll_method',$briSetting?->payroll_method)==='interbank')>Transfer Antar Bank</option></select></div>
</div></div>
<div class="flex flex-wrap gap-2"><button type="submit" formaction="{{ route('application-settings.bri.update') }}" class="btn btn-primary">Simpan Konfigurasi BRI</button><button type="submit" formmethod="POST" formaction="{{ route('application-settings.bri.test') }}" name="_method" value="POST" class="btn btn-secondary">Test Koneksi</button></div>
