<x-layouts.app :title="$title" :breadcrumbs="['Pengaturan', 'Pengaturan Aplikasi']">
<form method="post" action="{{ route('application-settings.update') }}" enctype="multipart/form-data" class="mx-auto max-w-5xl" data-settings-form data-initial-tab="{{ $errors->hasAny(['primary_logo', 'login_logo', 'print_logo', 'favicon']) ? 'branding' : 'general' }}">
  @csrf @method('PUT')
  <div class="mb-5"><p class="text-sm text-slate-500">Kelola konfigurasi umum dan tampilan aplikasi.</p></div>
  <div class="card overflow-hidden">
    <div class="overflow-x-auto border-b border-slate-200 bg-slate-50 px-2 pt-2" role="tablist" aria-label="Kategori pengaturan">
      <div class="flex min-w-max gap-1">@php($tabs = array_filter(['general'=>auth()->user()->can('application-settings.view')?'Umum':null,'branding'=>auth()->user()->can('application-settings.view')?'Branding':null,'appearance'=>auth()->user()->can('application-settings.view')?'Tampilan':null,'localization'=>auth()->user()->can('application-settings.view')?'Lokalisasi':null,'attendance'=>auth()->user()->can('application-settings.view')?'Absensi':null,'hrd'=>auth()->user()->can('hrd-settings.view')?'HRD':null,'finance'=>auth()->user()->can('finance.bri.configure')?'Keuangan & BRI':null,'system'=>auth()->user()->can('application-settings.view')?'Sistem':null]))@foreach($tabs as $tab => $label)<button type="button" class="settings-tab rounded-t-xl px-4 py-3 text-sm font-semibold text-slate-500 hover:bg-white hover:text-emerald-800" data-tab="{{ $tab }}" role="tab">{{ $label }}</button>@endforeach</div>
    </div>
    <div class="p-4 sm:p-6">
      @can('application-settings.view')
      <section data-panel="general" class="settings-panel space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Informasi umum</h2><p class="text-sm text-slate-500">Identitas dasar aplikasi dan instansi.</p></div><div class="grid gap-4 md:grid-cols-2">
        <div><label for="app_name">Nama Aplikasi</label><input id="app_name" name="app_name" value="{{ old('app_name',$settings['app_name']) }}" required maxlength="100"></div>
        <div><label for="app_short_name">Nama Singkat Aplikasi</label><input id="app_short_name" name="app_short_name" value="{{ old('app_short_name',$settings['app_short_name']) }}" required maxlength="50"></div>
        <div class="md:col-span-2"><label for="app_description">Deskripsi Aplikasi</label><textarea id="app_description" name="app_description" rows="2">{{ old('app_description',$settings['app_description']) }}</textarea></div>
        <div class="md:col-span-2"><label for="institution_name">Nama Instansi/Madrasah</label><input id="institution_name" name="institution_name" value="{{ old('institution_name',$settings['institution_name']) }}" required></div>
        <div><label for="app_email">Email Aplikasi</label><input type="email" id="app_email" name="app_email" value="{{ old('app_email',$settings['app_email']) }}"></div><div><label for="app_phone">Nomor Telepon</label><input id="app_phone" name="app_phone" value="{{ old('app_phone',$settings['app_phone']) }}"></div>
        <div class="md:col-span-2"><label for="app_website">Website</label><input type="url" id="app_website" name="app_website" value="{{ old('app_website',$settings['app_website']) }}" placeholder="https://"></div>
      </div></section>
      <section data-panel="branding" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Branding</h2><p class="text-sm text-slate-500">Berkas disimpan aman di storage publik. Maksimal logo 2 MB dan favicon 512 KB.</p></div><div class="grid gap-4 sm:grid-cols-2">
        @foreach(['primary_logo'=>['Logo Utama','PNG, JPG, atau WEBP',2048],'login_logo'=>['Logo Login (opsional)','Jika kosong, Logo Utama digunakan.',2048],'print_logo'=>['Logo Cetak (opsional)','Jika kosong, Logo Utama digunakan.',2048],'favicon'=>['Favicon','PNG atau ICO',512]] as $key => [$label,$help,$size])
        <div class="rounded-xl border border-slate-200 p-4"><label for="{{ $key }}">{{ $label }}</label><p class="mb-3 text-xs text-slate-500">{{ $help }}</p><div class="mb-3 grid h-24 place-items-center overflow-hidden rounded-lg bg-slate-50">@if($settings[$key])<img id="preview-{{ $key }}" src="{{ asset('storage/'.$settings[$key]) }}" class="max-h-20 max-w-full object-contain" alt="Pratinjau {{ $label }}">@else<img id="preview-{{ $key }}" class="hidden max-h-20 max-w-full object-contain" alt="Pratinjau {{ $label }}"><span class="text-xs text-slate-400">Belum ada berkas</span>@endif</div><input type="file" id="{{ $key }}" name="{{ $key }}" accept="{{ $key === 'favicon' ? '.png,.ico' : '.png,.jpg,.jpeg,.webp' }}" data-max-kb="{{ $size }}" data-file-label="{{ $label }}" aria-describedby="error-{{ $key }}" onchange="previewImage(event,'preview-{{ $key }}')"><p id="error-{{ $key }}" class="mt-2 text-xs font-medium text-rose-700" data-file-error>@error($key){{ $message }}@enderror</p></div>
        @endforeach
      </div></section>
      <section data-panel="appearance" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Tampilan</h2><p class="text-sm text-slate-500">Atur aksen visual tanpa mengubah struktur responsif aplikasi.</p></div><div class="grid gap-4 md:grid-cols-2"><div><label for="primary_color">Warna Utama</label><div class="mt-1 flex gap-2"><input type="color" value="{{ old('primary_color',$settings['primary_color']) }}" class="h-10 w-14 p-1" data-color-picker><input id="primary_color" name="primary_color" value="{{ old('primary_color',$settings['primary_color']) }}" pattern="#[0-9A-Fa-f]{6}" data-color-hex></div></div><div><label for="sidebar_mode">Sidebar</label><select id="sidebar_mode" name="sidebar_mode"><option value="expanded" @selected(old('sidebar_mode',$settings['sidebar_mode'])==='expanded')>Expanded</option><option value="compact" @selected(old('sidebar_mode',$settings['sidebar_mode'])==='compact')>Compact</option></select></div><div><label for="default_theme">Mode Tampilan</label><select id="default_theme" name="default_theme"><option value="light">Light</option></select><p class="mt-1 text-xs text-slate-500">Mode gelap belum tersedia pada design system saat ini.</p></div></div></section>
      <section data-panel="localization" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Lokalisasi</h2><p class="text-sm text-slate-500">Format wilayah dan waktu yang digunakan aplikasi.</p></div><div class="grid gap-4 md:grid-cols-2"><div><label>Bahasa Default</label><select name="default_language"><option value="id">Bahasa Indonesia</option></select></div><div><label for="timezone">Zona Waktu</label><select id="timezone" name="timezone">@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected(old('timezone',$settings['timezone'])===$timezone)>{{ $timezone }}</option>@endforeach</select></div><div><label>Format Tanggal</label><select name="date_format">@foreach(['DD/MM/YYYY','DD-MM-YYYY','YYYY-MM-DD'] as $value)<option @selected(old('date_format',$settings['date_format'])===$value)>{{ $value }}</option>@endforeach</select></div><div><label>Format Waktu</label><select name="time_format"><option value="24" @selected(old('time_format',$settings['time_format'])==='24')>24 Jam</option><option value="12" @selected(old('time_format',$settings['time_format'])==='12')>12 Jam</option></select></div><div><label>Hari Pertama Minggu</label><select name="first_day_of_week"><option value="monday" @selected(old('first_day_of_week',$settings['first_day_of_week'])==='monday')>Senin</option><option value="sunday" @selected(old('first_day_of_week',$settings['first_day_of_week'])==='sunday')>Minggu</option></select></div></div></section>
      <section data-panel="attendance" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Absensi</h2><p class="text-sm text-slate-500">Konfigurasi metode pencatatan kehadiran siswa.</p></div><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><input type="hidden" name="attendance_rfid_enabled" value="0"><label class="flex items-start justify-between gap-4"><span><strong class="text-emerald-950">Aktifkan Absensi RFID</strong><small class="mt-1 block text-slate-600">Izinkan siswa melakukan absensi menggunakan kartu RFID.</small></span><input type="checkbox" name="attendance_rfid_enabled" value="1" class="mt-1 h-5 w-5" @checked(old('attendance_rfid_enabled',$settings['attendance_rfid_enabled']))></label></div><div class="rounded-xl border border-slate-200 bg-white p-4"><input type="hidden" name="rfid_writer_enabled" value="0"><label class="flex items-start justify-between gap-4"><span><strong class="text-emerald-950">Aktifkan RFID Writer</strong><small class="mt-1 block text-slate-600">Izinkan admin menerbitkan kartu melalui perangkat writer yang online.</small></span><input type="checkbox" name="rfid_writer_enabled" value="1" class="mt-1 h-5 w-5" @checked(old('rfid_writer_enabled',$settings['rfid_writer_enabled']))></label></div></section>
      @endcan
      @can('hrd-settings.view')
      <section data-panel="hrd" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">HRD / Kepegawaian</h2><p class="text-sm text-slate-500">Atur lokasi, shift, dan kebijakan payroll pegawai.</p></div><div class="grid gap-4 md:grid-cols-3">
@foreach(['hrd_shift_1_start'=>'Mulai Shift 1','hrd_shift_1_end'=>'Selesai Shift 1','hrd_shift_2_start'=>'Mulai Shift 2','hrd_shift_2_end'=>'Selesai Shift 2','hrd_shift_3_start'=>'Mulai Shift 3','hrd_shift_3_end'=>'Selesai Shift 3'] as $key=>$label)<div><label>{{ $label }}</label><input type="time" name="{{ $key }}" value="{{ old($key,$settings[$key]) }}" required></div>@endforeach
<div><label>Jumlah Shift</label><input type="number" name="hrd_shift_count" min="1" max="3" value="{{ old('hrd_shift_count',$settings['hrd_shift_count']) }}"></div><div><label>Latitude</label><input name="hrd_attendance_latitude" value="{{ old('hrd_attendance_latitude',$settings['hrd_attendance_latitude']) }}"></div><div><label>Longitude</label><input name="hrd_attendance_longitude" value="{{ old('hrd_attendance_longitude',$settings['hrd_attendance_longitude']) }}"></div><div><label>Radius (meter)</label><input type="number" name="hrd_attendance_radius_meter" value="{{ old('hrd_attendance_radius_meter',$settings['hrd_attendance_radius_meter']) }}"></div><div><label>Batas Check-in Awal (menit)</label><input type="number" name="hrd_early_checkin_minutes" value="{{ old('hrd_early_checkin_minutes',$settings['hrd_early_checkin_minutes']) }}"></div><div><label>Maksimal Terlambat (jam)</label><input type="number" name="hrd_max_late_checkin_hours" value="{{ old('hrd_max_late_checkin_hours',$settings['hrd_max_late_checkin_hours']) }}"></div></div>
<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><h3 class="font-bold text-emerald-950">Keamanan Absensi</h3><p class="mb-3 text-xs text-slate-600">Menonaktifkan kontrol berikut menurunkan perlindungan absensi mandiri.</p><div class="grid gap-3 md:grid-cols-2">
@foreach(['hrd_attendance_location_enabled'=>'Wajibkan Location Lock','hrd_attendance_face_enabled'=>'Wajibkan Face Recognition','hrd_attendance_device_binding_enabled'=>'Device Binding','hrd_attendance_anti_replay_enabled'=>'Anti Replay','hrd_attendance_new_device_requires_approval'=>'Perangkat Baru Perlu Approval'] as $key=>$label)<label class="flex justify-between rounded-xl border bg-white p-3"><span>{{ $label }}</span><span><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$settings[$key]))></span></label>@endforeach</div>
<div class="mt-4 grid gap-3 md:grid-cols-3">@foreach(['hrd_attendance_max_accuracy_meter'=>'Maksimum Akurasi GPS (m)','hrd_attendance_location_max_age_seconds'=>'Max Age Lokasi (detik)','hrd_attendance_challenge_ttl_seconds'=>'Challenge TTL (detik)','hrd_face_verification_ttl_seconds'=>'Face TTL (detik)','hrd_attendance_max_devices'=>'Maksimum Perangkat','hrd_face_confidence_threshold'=>'Threshold Face (0–1)'] as $key=>$label)<div><label>{{ $label }}</label><input type="number" name="{{ $key }}" value="{{ old($key,$settings[$key]) }}" @if($key==='hrd_face_confidence_threshold') step="0.01" min="0" max="1" @else min="1" @endif required></div>@endforeach</div>
<button type="button" class="btn btn-secondary mt-4" data-current-location>Gunakan Lokasi Saat Ini</button><p class="mt-2 text-xs text-slate-600">Koordinat hanya diisi ke formulir; tekan Simpan Perubahan untuk menyimpannya.</p></div>
@if($faceStatus)
<div class="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5" data-face-status>
  <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 class="font-bold text-emerald-950">Status Face Recognition</h3><p class="mt-1 text-xs text-slate-500">Pemeriksaan berlangsung aman melalui Laravel, bukan dari peramban ke layanan Python.</p></div><span class="badge {{ $faceStatus['active'] ? 'badge-success' : 'badge-danger' }}" data-face-service>{{ $faceStatus['active'] ? 'Aktif' : 'Tidak Tersedia' }}</span></div>
  <div class="mt-4 grid gap-x-6 gap-y-3 text-sm sm:grid-cols-2 lg:grid-cols-3">
    <div><p class="text-xs font-semibold uppercase text-slate-500">Provider</p><p class="mt-1 font-semibold" data-face-provider>{{ $faceStatus['provider'] }}</p></div>
    <div><p class="text-xs font-semibold uppercase text-slate-500">Engine AI</p><p class="mt-1 font-semibold" data-face-engine>{{ $faceStatus['engine'] ?? 'Tidak diketahui' }}</p></div>
    <div><p class="text-xs font-semibold uppercase text-slate-500">Model AI</p><span class="badge {{ $faceStatus['model_loaded'] === true ? 'badge-success' : ($faceStatus['model_loaded'] === false ? 'badge-danger' : 'badge-warning') }} mt-1" data-face-model>{{ $faceStatus['model_loaded'] === true ? 'Siap' : ($faceStatus['model_loaded'] === false ? 'Tidak Dimuat' : 'Tidak diketahui') }}</span></div>
    <div><p class="text-xs font-semibold uppercase text-slate-500">Koneksi Service</p><span class="badge {{ $faceStatus['connected'] ? 'badge-success' : 'badge-danger' }} mt-1" data-face-connection>{{ $faceStatus['connected'] ? 'Terhubung' : 'Terputus' }}</span></div>
    <div><p class="text-xs font-semibold uppercase text-slate-500">Driver</p><p class="mt-1 font-mono text-xs" data-face-driver>{{ $faceStatus['driver'] ?: 'Belum dikonfigurasi' }}</p></div>
    <div><p class="text-xs font-semibold uppercase text-slate-500">Endpoint</p><p class="mt-1 font-mono text-xs" data-face-endpoint>{{ $faceStatus['endpoint'] }}</p></div>
    <div><p class="text-xs font-semibold uppercase text-slate-500">Timeout</p><p class="mt-1 font-semibold"><span data-face-timeout>{{ $faceStatus['timeout'] }}</span> detik</p></div>
  </div>
  <div class="{{ (!$faceStatus['active'] || $faceStatus['detail']) ? '' : 'hidden' }} mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert" data-face-alert><p class="font-bold">Layanan Face Recognition Tidak Tersedia</p><p class="mt-1" data-face-detail>{{ $faceStatus['detail'] ?? 'Layanan Face Recognition tidak dapat dihubungi atau model AI belum siap.' }}</p></div>
  <div class="mt-5 grid gap-3 sm:grid-cols-3">
    <x-ui.stat-card label="Personalia Terdaftar Wajah" :value="$faceStatus['statistics']['registered']" data-face-registered />
    <x-ui.stat-card label="Jumlah Sampel Wajah" :value="$faceStatus['statistics']['samples']" data-face-samples />
    <x-ui.stat-card label="Personalia Belum Terdaftar" :value="$faceStatus['statistics']['unregistered']" data-face-unregistered />
  </div>
  <div class="mt-4 flex flex-col gap-3 border-t border-slate-200 pt-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-slate-500">Terakhir diperiksa: <strong class="text-slate-700" data-face-checked>{{ $faceStatus['checked_at'] }}</strong></p><div class="flex flex-wrap gap-2">@can('personnel.view')<a href="{{ route('personnel.index') }}" class="btn btn-secondary">Lihat Data Personalia</a>@endcan @can('hrd-settings.update')<button type="button" class="btn btn-secondary" data-face-restart>Mulai Ulang Layanan</button>@endcan <button type="button" class="btn btn-primary" data-face-refresh>Periksa Status Sekarang</button></div></div>
  <p class="mt-2 hidden text-sm font-semibold text-emerald-800" aria-live="polite" data-face-message></p>
</div>
@endif<div class="grid gap-3 md:grid-cols-2">@foreach(['hrd_face_recognition_enabled'=>'Face Recognition (opsional)','hrd_payroll_by_attendance_enabled'=>'Payroll berdasarkan absensi','hrd_payroll_auto_late_deduction_enabled'=>'Potongan terlambat otomatis','hrd_payroll_auto_cash_advance_deduction_enabled'=>'Potongan kasbon otomatis'] as $key=>$label)<label class="flex justify-between rounded-xl border p-4"><span>{{ $label }}</span><span><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$settings[$key]))></span></label>@endforeach</div>
      @can('hrd-settings.update')<div class="mt-5"><button type="submit" formaction="{{ route('application-settings.hrd.update') }}" class="btn btn-primary">Simpan Pengaturan HRD</button></div>@endcan
      </section>
      @endcan
      @can('finance.bri.configure')
      <section data-panel="finance" class="settings-panel hidden space-y-6">
        @include('settings.application._bri')
      </section>
      @endcan
      @can('application-settings.view')
      <section data-panel="system" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Sistem</h2><p class="text-sm text-slate-500">Konfigurasi operasional yang berlaku secara global.</p></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-4"><div class="flex items-start justify-between gap-4"><div><label for="maintenance_toggle" class="text-amber-900">Mode Maintenance</label><p class="text-xs text-amber-800">Pengguna biasa akan menerima halaman pemeliharaan. Super Admin tetap dapat mengakses aplikasi.</p></div><input type="checkbox" id="maintenance_toggle" class="mt-1 h-5 w-5" @checked(old('maintenance_mode',$settings['maintenance_mode']))></div><input type="hidden" name="maintenance_mode" value="{{ old('maintenance_mode',$settings['maintenance_mode']) ? '1' : '0' }}" data-maintenance-value></div><div><label for="maintenance_message">Pesan Maintenance</label><textarea id="maintenance_message" name="maintenance_message" rows="3" required>{{ old('maintenance_message',$settings['maintenance_message']) }}</textarea></div><div class="max-w-xs"><label for="pagination_size">Jumlah Data per Halaman</label><select id="pagination_size" name="pagination_size">@foreach([10,20,25,50,100] as $size)<option value="{{ $size }}" @selected((int)old('pagination_size',$settings['pagination_size'])===$size)>{{ $size }}</option>@endforeach</select></div></section>
      @endcan
    </div>
    <div class="flex flex-col-reverse gap-2 border-t border-slate-200 bg-slate-50 p-4 sm:flex-row sm:justify-end"><button type="reset" class="btn btn-secondary">Reset Perubahan</button>@can('application-settings.update')<button type="submit" class="btn btn-primary"><x-ui.icon name="save" /> Simpan Perubahan</button>@endcan</div>
  </div>
</form>
<dialog id="maintenance-confirm" class="subject-dialog"><div class="dialog-panel"><div class="dialog-heading"><h2>Aktifkan mode maintenance?</h2><button type="button" data-maintenance-cancel aria-label="Tutup">×</button></div><p class="text-sm text-slate-600">Pengguna biasa tidak dapat menggunakan aplikasi sampai mode ini dinonaktifkan. Super Admin tetap dapat masuk.</p><div class="dialog-actions"><button type="button" class="btn btn-secondary" data-maintenance-cancel>Batal</button><button type="button" class="btn btn-danger" data-maintenance-confirm>Ya, Aktifkan</button></div></div></dialog>
<script>document.querySelector('[data-current-location]')?.addEventListener('click',()=>navigator.geolocation.getCurrentPosition(p=>{document.querySelector('[name="hrd_attendance_latitude"]').value=p.coords.latitude;document.querySelector('[name="hrd_attendance_longitude"]').value=p.coords.longitude},()=>alert('Lokasi tidak dapat diperoleh.'),{enableHighAccuracy:true,maximumAge:0,timeout:15000}));</script>
@if($faceStatus)<script>
(()=>{const panel=document.querySelector('[data-face-status]'),button=panel?.querySelector('[data-face-refresh]'),restart=panel?.querySelector('[data-face-restart]'),message=panel?.querySelector('[data-face-message]');if(!button)return;
const badge=(selector,ok,yes,no)=>{const element=panel.querySelector(selector);element.textContent=ok?yes:no;element.className=`badge mt-1 ${ok?'badge-success':'badge-danger'}`};
button.addEventListener('click',async()=>{button.disabled=true;message.classList.remove('hidden');message.textContent='Memeriksa layanan Face Recognition...';try{const response=await fetch(@json(route('application-settings.face-recognition.status')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())}});if(!response.ok)throw new Error();const status=await response.json();badge('[data-face-service]',status.active,'Aktif','Tidak Tersedia');badge('[data-face-connection]',status.connected,'Terhubung','Terputus');const model=panel.querySelector('[data-face-model]');model.textContent=status.model_loaded===true?'Siap':status.model_loaded===false?'Tidak Dimuat':'Tidak diketahui';model.className=`badge mt-1 ${status.model_loaded===true?'badge-success':status.model_loaded===false?'badge-danger':'badge-warning'}`;for(const [key,value] of Object.entries({provider:status.provider,engine:status.engine??'Tidak diketahui',driver:status.driver||'Belum dikonfigurasi',endpoint:status.endpoint,timeout:status.timeout,checked:status.checked_at}))panel.querySelector(`[data-face-${key}]`).textContent=value;for(const key of ['registered','samples','unregistered'])panel.querySelector(`[data-face-${key}] p:last-child`).textContent=status.statistics[key];const alert=panel.querySelector('[data-face-alert]');alert.classList.toggle('hidden',status.active&&!status.detail);panel.querySelector('[data-face-detail]').textContent=status.detail??'Layanan Face Recognition tidak dapat dihubungi atau model AI belum siap.';message.textContent='Status diperbarui.';}catch{message.textContent='Status tidak dapat diperbarui. Silakan coba lagi.';}finally{button.disabled=false;}});
restart?.addEventListener('click',async()=>{if(!confirm('Mulai ulang layanan Face Recognition Python sekarang? Proses verifikasi wajah akan berhenti sementara.'))return;restart.disabled=true;button.disabled=true;message.classList.remove('hidden');message.textContent='Memulai ulang layanan Face Recognition...';try{const response=await fetch(@json(route('application-settings.face-recognition.restart')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())}});const result=await response.json();if(!response.ok)throw new Error(result.message??'Layanan gagal dimulai ulang.');message.textContent=result.message;button.disabled=false;setTimeout(()=>button.click(),2000);}catch(error){message.textContent=error.message??'Layanan gagal dimulai ulang. Silakan periksa konfigurasi server.';button.disabled=false;}finally{restart.disabled=false;}});})();
</script>@endif
</x-layouts.app>
