<x-layouts.app :title="$title" :breadcrumbs="['Akun & Akses', 'Pengaturan Aplikasi']">
<form method="post" action="{{ route('application-settings.update') }}" enctype="multipart/form-data" class="mx-auto max-w-5xl" data-settings-form>
  @csrf @method('PUT')
  <div class="mb-5"><p class="text-sm text-slate-500">Kelola konfigurasi umum dan tampilan aplikasi.</p></div>
  <div class="card overflow-hidden">
    <div class="overflow-x-auto border-b border-slate-200 bg-slate-50 px-2 pt-2" role="tablist" aria-label="Kategori pengaturan">
      <div class="flex min-w-max gap-1">@foreach(['general'=>'Umum','branding'=>'Branding','appearance'=>'Tampilan','localization'=>'Lokalisasi','attendance'=>'Absensi','hrd'=>'HRD','system'=>'Sistem'] as $tab => $label)<button type="button" class="settings-tab rounded-t-xl px-4 py-3 text-sm font-semibold text-slate-500 hover:bg-white hover:text-emerald-800" data-tab="{{ $tab }}" role="tab">{{ $label }}</button>@endforeach</div>
    </div>
    <div class="p-4 sm:p-6">
      <section data-panel="general" class="settings-panel space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Informasi umum</h2><p class="text-sm text-slate-500">Identitas dasar aplikasi dan instansi.</p></div><div class="grid gap-4 md:grid-cols-2">
        <div><label for="app_name">Nama Aplikasi</label><input id="app_name" name="app_name" value="{{ old('app_name',$settings['app_name']) }}" required maxlength="100"></div>
        <div><label for="app_short_name">Nama Singkat Aplikasi</label><input id="app_short_name" name="app_short_name" value="{{ old('app_short_name',$settings['app_short_name']) }}" required maxlength="50"></div>
        <div class="md:col-span-2"><label for="app_description">Deskripsi Aplikasi</label><textarea id="app_description" name="app_description" rows="2">{{ old('app_description',$settings['app_description']) }}</textarea></div>
        <div class="md:col-span-2"><label for="institution_name">Nama Instansi/Madrasah</label><input id="institution_name" name="institution_name" value="{{ old('institution_name',$settings['institution_name']) }}" required></div>
        <div><label for="app_email">Email Aplikasi</label><input type="email" id="app_email" name="app_email" value="{{ old('app_email',$settings['app_email']) }}"></div><div><label for="app_phone">Nomor Telepon</label><input id="app_phone" name="app_phone" value="{{ old('app_phone',$settings['app_phone']) }}"></div>
        <div class="md:col-span-2"><label for="app_website">Website</label><input type="url" id="app_website" name="app_website" value="{{ old('app_website',$settings['app_website']) }}" placeholder="https://"></div>
      </div></section>
      <section data-panel="branding" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Branding</h2><p class="text-sm text-slate-500">Berkas disimpan aman di storage publik. Maksimal logo 2 MB dan favicon 512 KB.</p></div><div class="grid gap-4 sm:grid-cols-2">
        @foreach(['primary_logo'=>['Logo Utama','PNG, JPG, atau WEBP',2048],'login_logo'=>['Logo Login (opsional)','Jika kosong, Logo Utama digunakan.',2048],'print_logo'=>['Logo Cetak (opsional)','Jika kosong, Logo Utama digunakan.',2048],'favicon'=>['Favicon','PNG atau ICO',512]] as $key => [$label,$help,$size])
        <div class="rounded-xl border border-slate-200 p-4"><label for="{{ $key }}">{{ $label }}</label><p class="mb-3 text-xs text-slate-500">{{ $help }}</p><div class="mb-3 grid h-24 place-items-center overflow-hidden rounded-lg bg-slate-50">@if($settings[$key])<img id="preview-{{ $key }}" src="{{ asset('storage/'.$settings[$key]) }}" class="max-h-20 max-w-full object-contain" alt="Pratinjau {{ $label }}">@else<img id="preview-{{ $key }}" class="hidden max-h-20 max-w-full object-contain" alt="Pratinjau {{ $label }}"><span class="text-xs text-slate-400">Belum ada berkas</span>@endif</div><input type="file" id="{{ $key }}" name="{{ $key }}" accept="{{ $key === 'favicon' ? '.png,.ico' : '.png,.jpg,.jpeg,.webp' }}" onchange="previewImage(event,'preview-{{ $key }}')"></div>
        @endforeach
      </div></section>
      <section data-panel="appearance" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Tampilan</h2><p class="text-sm text-slate-500">Atur aksen visual tanpa mengubah struktur responsif aplikasi.</p></div><div class="grid gap-4 md:grid-cols-2"><div><label for="primary_color">Warna Utama</label><div class="mt-1 flex gap-2"><input type="color" value="{{ old('primary_color',$settings['primary_color']) }}" class="h-10 w-14 p-1" data-color-picker><input id="primary_color" name="primary_color" value="{{ old('primary_color',$settings['primary_color']) }}" pattern="#[0-9A-Fa-f]{6}" data-color-hex></div></div><div><label for="sidebar_mode">Sidebar</label><select id="sidebar_mode" name="sidebar_mode"><option value="expanded" @selected(old('sidebar_mode',$settings['sidebar_mode'])==='expanded')>Expanded</option><option value="compact" @selected(old('sidebar_mode',$settings['sidebar_mode'])==='compact')>Compact</option></select></div><div><label for="default_theme">Mode Tampilan</label><select id="default_theme" name="default_theme"><option value="light">Light</option></select><p class="mt-1 text-xs text-slate-500">Mode gelap belum tersedia pada design system saat ini.</p></div></div></section>
      <section data-panel="localization" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Lokalisasi</h2><p class="text-sm text-slate-500">Format wilayah dan waktu yang digunakan aplikasi.</p></div><div class="grid gap-4 md:grid-cols-2"><div><label>Bahasa Default</label><select name="default_language"><option value="id">Bahasa Indonesia</option></select></div><div><label for="timezone">Zona Waktu</label><select id="timezone" name="timezone">@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected(old('timezone',$settings['timezone'])===$timezone)>{{ $timezone }}</option>@endforeach</select></div><div><label>Format Tanggal</label><select name="date_format">@foreach(['DD/MM/YYYY','DD-MM-YYYY','YYYY-MM-DD'] as $value)<option @selected(old('date_format',$settings['date_format'])===$value)>{{ $value }}</option>@endforeach</select></div><div><label>Format Waktu</label><select name="time_format"><option value="24" @selected(old('time_format',$settings['time_format'])==='24')>24 Jam</option><option value="12" @selected(old('time_format',$settings['time_format'])==='12')>12 Jam</option></select></div><div><label>Hari Pertama Minggu</label><select name="first_day_of_week"><option value="monday" @selected(old('first_day_of_week',$settings['first_day_of_week'])==='monday')>Senin</option><option value="sunday" @selected(old('first_day_of_week',$settings['first_day_of_week'])==='sunday')>Minggu</option></select></div></div></section>
      <section data-panel="attendance" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Absensi</h2><p class="text-sm text-slate-500">Konfigurasi metode pencatatan kehadiran siswa.</p></div><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><input type="hidden" name="attendance_rfid_enabled" value="0"><label class="flex items-start justify-between gap-4"><span><strong class="text-emerald-950">Aktifkan Absensi RFID</strong><small class="mt-1 block text-slate-600">Izinkan siswa melakukan absensi menggunakan kartu RFID.</small></span><input type="checkbox" name="attendance_rfid_enabled" value="1" class="mt-1 h-5 w-5" @checked(old('attendance_rfid_enabled',$settings['attendance_rfid_enabled']))></label></div><div class="rounded-xl border border-slate-200 bg-white p-4"><input type="hidden" name="rfid_writer_enabled" value="0"><label class="flex items-start justify-between gap-4"><span><strong class="text-emerald-950">Aktifkan RFID Writer</strong><small class="mt-1 block text-slate-600">Izinkan admin menerbitkan kartu melalui perangkat writer yang online.</small></span><input type="checkbox" name="rfid_writer_enabled" value="1" class="mt-1 h-5 w-5" @checked(old('rfid_writer_enabled',$settings['rfid_writer_enabled']))></label></div></section>
      <section data-panel="hrd" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">HRD / Kepegawaian</h2><p class="text-sm text-slate-500">Atur lokasi, shift, dan kebijakan payroll pegawai.</p></div><div class="grid gap-4 md:grid-cols-3">
@foreach(['hrd_shift_1_start'=>'Mulai Shift 1','hrd_shift_1_end'=>'Selesai Shift 1','hrd_shift_2_start'=>'Mulai Shift 2','hrd_shift_2_end'=>'Selesai Shift 2','hrd_shift_3_start'=>'Mulai Shift 3','hrd_shift_3_end'=>'Selesai Shift 3'] as $key=>$label)<div><label>{{ $label }}</label><input type="time" name="{{ $key }}" value="{{ old($key,$settings[$key]) }}" required></div>@endforeach
<div><label>Jumlah Shift</label><input type="number" name="hrd_shift_count" min="1" max="3" value="{{ old('hrd_shift_count',$settings['hrd_shift_count']) }}"></div><div><label>Latitude</label><input name="hrd_attendance_latitude" value="{{ old('hrd_attendance_latitude',$settings['hrd_attendance_latitude']) }}"></div><div><label>Longitude</label><input name="hrd_attendance_longitude" value="{{ old('hrd_attendance_longitude',$settings['hrd_attendance_longitude']) }}"></div><div><label>Radius (meter)</label><input type="number" name="hrd_attendance_radius_meter" value="{{ old('hrd_attendance_radius_meter',$settings['hrd_attendance_radius_meter']) }}"></div><div><label>Batas Check-in Awal (menit)</label><input type="number" name="hrd_early_checkin_minutes" value="{{ old('hrd_early_checkin_minutes',$settings['hrd_early_checkin_minutes']) }}"></div><div><label>Maksimal Terlambat (jam)</label><input type="number" name="hrd_max_late_checkin_hours" value="{{ old('hrd_max_late_checkin_hours',$settings['hrd_max_late_checkin_hours']) }}"></div></div>
<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><h3 class="font-bold text-emerald-950">Keamanan Absensi</h3><p class="mb-3 text-xs text-slate-600">Menonaktifkan kontrol berikut menurunkan perlindungan absensi mandiri.</p><div class="grid gap-3 md:grid-cols-2">
@foreach(['hrd_attendance_location_enabled'=>'Wajibkan Location Lock','hrd_attendance_face_enabled'=>'Wajibkan Face Recognition','hrd_attendance_device_binding_enabled'=>'Device Binding','hrd_attendance_anti_replay_enabled'=>'Anti Replay','hrd_attendance_new_device_requires_approval'=>'Perangkat Baru Perlu Approval'] as $key=>$label)<label class="flex justify-between rounded-xl border bg-white p-3"><span>{{ $label }}</span><span><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$settings[$key]))></span></label>@endforeach</div>
<div class="mt-4 grid gap-3 md:grid-cols-3">@foreach(['hrd_attendance_max_accuracy_meter'=>'Maksimum Akurasi GPS (m)','hrd_attendance_location_max_age_seconds'=>'Max Age Lokasi (detik)','hrd_attendance_challenge_ttl_seconds'=>'Challenge TTL (detik)','hrd_face_verification_ttl_seconds'=>'Face TTL (detik)','hrd_attendance_max_devices'=>'Maksimum Perangkat','hrd_face_confidence_threshold'=>'Threshold Face (0–1)'] as $key=>$label)<div><label>{{ $label }}</label><input type="number" name="{{ $key }}" value="{{ old($key,$settings[$key]) }}" @if($key==='hrd_face_confidence_threshold') step="0.01" min="0" max="1" @else min="1" @endif required></div>@endforeach</div>
<button type="button" class="btn btn-secondary mt-4" data-current-location>Gunakan Lokasi Saat Ini</button><p class="mt-2 text-xs text-slate-600">Koordinat hanya diisi ke formulir; tekan Simpan Perubahan untuk menyimpannya.</p></div>
<div class="rounded-xl border bg-white p-4 text-sm"><h3 class="font-bold text-emerald-950">Status Face Recognition</h3><dl class="mt-2 grid grid-cols-2 gap-2"><dt>Provider</dt><dd>{{ ucfirst($faceService['provider']) }}</dd><dt>Service</dt><dd>{{ ($faceService['status']??'offline')==='ok'?'Online':'Offline' }}</dd><dt>Model</dt><dd>{{ ($faceService['model_loaded']??false)?'Loaded':'Belum siap' }}</dd></dl></div><div class="grid gap-3 md:grid-cols-2">@foreach(['hrd_face_recognition_enabled'=>'Face Recognition (opsional)','hrd_payroll_by_attendance_enabled'=>'Payroll berdasarkan absensi','hrd_payroll_auto_late_deduction_enabled'=>'Potongan terlambat otomatis','hrd_payroll_auto_cash_advance_deduction_enabled'=>'Potongan kasbon otomatis'] as $key=>$label)<label class="flex justify-between rounded-xl border p-4"><span>{{ $label }}</span><span><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$settings[$key]))></span></label>@endforeach</div></section>
      <section data-panel="system" class="settings-panel hidden space-y-5"><div><h2 class="text-lg font-bold text-emerald-950">Sistem</h2><p class="text-sm text-slate-500">Konfigurasi operasional yang berlaku secara global.</p></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-4"><div class="flex items-start justify-between gap-4"><div><label for="maintenance_toggle" class="text-amber-900">Mode Maintenance</label><p class="text-xs text-amber-800">Pengguna biasa akan menerima halaman pemeliharaan. Super Admin tetap dapat mengakses aplikasi.</p></div><input type="checkbox" id="maintenance_toggle" class="mt-1 h-5 w-5" @checked(old('maintenance_mode',$settings['maintenance_mode']))></div><input type="hidden" name="maintenance_mode" value="{{ old('maintenance_mode',$settings['maintenance_mode']) ? '1' : '0' }}" data-maintenance-value></div><div><label for="maintenance_message">Pesan Maintenance</label><textarea id="maintenance_message" name="maintenance_message" rows="3" required>{{ old('maintenance_message',$settings['maintenance_message']) }}</textarea></div><div class="max-w-xs"><label for="pagination_size">Jumlah Data per Halaman</label><select id="pagination_size" name="pagination_size">@foreach([10,20,25,50,100] as $size)<option value="{{ $size }}" @selected((int)old('pagination_size',$settings['pagination_size'])===$size)>{{ $size }}</option>@endforeach</select></div></section>
    </div>
    <div class="flex flex-col-reverse gap-2 border-t border-slate-200 bg-slate-50 p-4 sm:flex-row sm:justify-end"><button type="reset" class="btn btn-secondary">Reset Perubahan</button>@can('application-settings.update')<button type="submit" class="btn btn-primary"><x-ui.icon name="save" /> Simpan Perubahan</button>@endcan</div>
  </div>
</form>
<dialog id="maintenance-confirm" class="subject-dialog"><div class="dialog-panel"><div class="dialog-heading"><h2>Aktifkan mode maintenance?</h2><button type="button" data-maintenance-cancel aria-label="Tutup">×</button></div><p class="text-sm text-slate-600">Pengguna biasa tidak dapat menggunakan aplikasi sampai mode ini dinonaktifkan. Super Admin tetap dapat masuk.</p><div class="dialog-actions"><button type="button" class="btn btn-secondary" data-maintenance-cancel>Batal</button><button type="button" class="btn btn-danger" data-maintenance-confirm>Ya, Aktifkan</button></div></div></dialog>
<script>document.querySelector('[data-current-location]')?.addEventListener('click',()=>navigator.geolocation.getCurrentPosition(p=>{document.querySelector('[name="hrd_attendance_latitude"]').value=p.coords.latitude;document.querySelector('[name="hrd_attendance_longitude"]').value=p.coords.longitude},()=>alert('Lokasi tidak dapat diperoleh.'),{enableHighAccuracy:true,maximumAge:0,timeout:15000}));</script>
</x-layouts.app>
