<x-app-layout :title="$title">
<div class="space-y-6">
@include('payroll.partials.tabs')
<x-ui.page-header title="Profil Gaji" description="Kelola profil gaji pegawai beserta riwayat perubahan berdasarkan tanggal efektif." :breadcrumbs="['Beranda','Keuangan','Payroll Pegawai','Profil Gaji']">
  <x-slot:secondary>@can('salary-profiles.view')<x-ui.button variant="outline" :href="route('payroll.salary-profiles.missing')">Pegawai Belum Memiliki Profil</x-ui.button>@endcan</x-slot:secondary>
  <x-slot:primary>@can('salary-profiles.manage')<x-ui.button :href="route('payroll.salary-profiles.create')">Tambah Profil Gaji</x-ui.button>@endcan</x-slot:primary>
</x-ui.page-header>
<x-ui.card>
<x-ui.table :headers="['Pegawai','Nomor Pegawai','Jenis Pegawai','Jabatan','Tanggal Efektif','Gaji Pokok','Metode Pembayaran','Status','Tindakan']">
@forelse($profiles as $p)<tr><td class="font-semibold text-emerald-950">{{ $p->employee?->fullName() }}</td><td>{{ $p->employee?->employee_number ?? '-' }}</td><td>{{ $p->employee?->employment_type?->label() ?? $p->employee?->employment_type ?? '-' }}</td><td>{{ $p->employee?->position ?? '-' }}</td><td>{{ $p->effective_start_date?->format('d/m/Y') }}</td><td class="text-right font-semibold">Rp {{ number_format((int)$p->base_salary,0,',','.') }}</td><td>{{ str($p->payment_method)->replace('_',' ')->headline() }}</td><td><x-ui.badge :variant="$p->is_active ? 'success' : 'muted'">{{ $p->is_active ? 'Aktif' : 'Nonaktif' }}</x-ui.badge></td><td><div class="table-actions"><x-ui.button variant="secondary" :href="route('payroll.salary-profiles.show',$p)">Detail</x-ui.button>@if($p->employee)<x-ui.button variant="outline" :href="route('payroll.salary-profiles.history',$p->employee)">Lihat Histori</x-ui.button>@endif @can('salary-profiles.manage')<x-ui.button variant="outline" :href="route('payroll.salary-profiles.create',['employee_id'=>$p->employee_id])">Buat Versi Baru</x-ui.button>@endcan</div></td></tr>
@empty<tr><td colspan="9"><x-ui.empty-state icon="₨" title="Belum ada profil gaji" description="Buat profil gaji agar pegawai dapat dimasukkan ke proses payroll."><x-slot:secondary>@can('salary-profiles.view')<x-ui.button variant="outline" :href="route('payroll.salary-profiles.missing')">Lihat Pegawai Belum Memiliki Profil</x-ui.button>@endcan</x-slot:secondary><x-slot:primary>@can('salary-profiles.manage')<x-ui.button :href="route('payroll.salary-profiles.create')">Tambah Profil Gaji</x-ui.button>@endcan</x-slot:primary></x-ui.empty-state></td></tr>@endforelse
</x-ui.table><div class="mt-4">{{ $profiles->links() }}</div></x-ui.card></div></x-app-layout>
