<?php
declare(strict_types=1);
use App\Http\Controllers\Classrooms\{ClassroomController,ClassroomStatusController,ClassroomHomeroomController,ClassroomMemberController,ClassroomMemberMoveController,ClassroomLegacyMappingController,ClassroomCopyController,ClassroomPromotionController,ClassroomGuideController}; use Illuminate\Support\Facades\Route;
Route::middleware(['auth','active','force-password-change'])->prefix('classrooms')->name('classrooms.')->group(function(){
 Route::get('/',[ClassroomController::class,'index'])->name('index'); Route::get('/create',[ClassroomController::class,'create'])->name('create'); Route::post('/',[ClassroomController::class,'store'])->name('store'); Route::get('/guide',ClassroomGuideController::class)->name('guide');
 Route::get('/legacy-mapping',[ClassroomLegacyMappingController::class,'index'])->name('legacy.index'); Route::post('/legacy-mapping/preview',[ClassroomLegacyMappingController::class,'preview'])->name('legacy.preview'); Route::post('/legacy-mapping/confirm',[ClassroomLegacyMappingController::class,'confirm'])->name('legacy.confirm');
 Route::get('/copy',[ClassroomCopyController::class,'form'])->name('copy.form'); Route::post('/copy/preview',[ClassroomCopyController::class,'preview'])->name('copy.preview'); Route::post('/copy/confirm',[ClassroomCopyController::class,'confirm'])->name('copy.confirm');
 Route::get('/promotions',[ClassroomPromotionController::class,'form'])->name('promotions.form'); Route::post('/promotions/preview',[ClassroomPromotionController::class,'preview'])->name('promotions.preview'); Route::post('/promotions/confirm',[ClassroomPromotionController::class,'confirm'])->name('promotions.confirm'); Route::get('/promotions/{batch}',[ClassroomPromotionController::class,'result'])->name('promotions.result');
 Route::get('/{classroom}',[ClassroomController::class,'show'])->name('show'); Route::get('/{classroom}/edit',[ClassroomController::class,'edit'])->name('edit'); Route::put('/{classroom}',[ClassroomController::class,'update'])->name('update'); Route::patch('/{classroom}/activate',[ClassroomStatusController::class,'activate'])->name('activate'); Route::patch('/{classroom}/deactivate',[ClassroomStatusController::class,'deactivate'])->name('deactivate');
 Route::get('/{classroom}/homeroom',[ClassroomHomeroomController::class,'edit'])->name('homeroom.edit'); Route::patch('/{classroom}/homeroom',[ClassroomHomeroomController::class,'update'])->name('homeroom.update'); Route::get('/{classroom}/members',[ClassroomMemberController::class,'index'])->name('members.index'); Route::post('/{classroom}/members',[ClassroomMemberController::class,'store'])->name('members.store'); Route::delete('/{classroom}/members/{membership}',[ClassroomMemberController::class,'destroy'])->name('members.destroy'); Route::get('/{classroom}/members/{membership}/move',[ClassroomMemberMoveController::class,'edit'])->name('members.move.edit'); Route::patch('/{classroom}/members/{membership}/move',[ClassroomMemberMoveController::class,'update'])->name('members.move.update');
});
