<?php
declare(strict_types=1);
use App\Http\Controllers\Finance\{BriReconciliationController,FeeTypeController,FinanceDashboardController,FinanceReportController,SppGenerationController,StudentInvoiceController,StudentPaymentController};use Illuminate\Support\Facades\Route;
Route::prefix('finance')->name('finance.')->middleware(['auth','active','force-password-change'])->group(function():void{
 Route::get('/',FinanceDashboardController::class)->middleware('permission:finance.dashboard.view')->name('dashboard');
 Route::middleware('permission:finance.fee-type.manage')->group(function(){Route::get('fee-types',[FeeTypeController::class,'index'])->name('fee-types.index');Route::get('fee-types/create',[FeeTypeController::class,'create'])->name('fee-types.create');Route::post('fee-types',[FeeTypeController::class,'store'])->name('fee-types.store');Route::get('fee-types/{feeType}/edit',[FeeTypeController::class,'edit'])->name('fee-types.edit');Route::put('fee-types/{feeType}',[FeeTypeController::class,'update'])->name('fee-types.update');Route::patch('fee-types/{feeType}/toggle',[FeeTypeController::class,'toggle'])->name('fee-types.toggle');});
 Route::get('invoices',[StudentInvoiceController::class,'index'])->middleware('permission:finance.invoice.view')->name('invoices.index');Route::get('invoices/create',[StudentInvoiceController::class,'create'])->middleware('permission:finance.invoice.create')->name('invoices.create');Route::post('invoices',[StudentInvoiceController::class,'store'])->middleware('permission:finance.invoice.create')->name('invoices.store');Route::get('invoices/{invoice}',[StudentInvoiceController::class,'show'])->middleware('permission:finance.invoice.view')->name('invoices.show');Route::get('invoices/{invoice}/edit',[StudentInvoiceController::class,'edit'])->middleware('permission:finance.invoice.update')->name('invoices.edit');Route::put('invoices/{invoice}',[StudentInvoiceController::class,'update'])->middleware('permission:finance.invoice.update')->name('invoices.update');Route::post('invoices/{invoice}/cancel',[StudentInvoiceController::class,'cancel'])->middleware('permission:finance.invoice.cancel')->name('invoices.cancel');
 Route::get('spp/generate',[SppGenerationController::class,'create'])->middleware('permission:finance.invoice.create')->name('spp.create');Route::post('spp/preview',[SppGenerationController::class,'preview'])->middleware('permission:finance.invoice.create')->name('spp.preview');Route::post('spp/generate',[SppGenerationController::class,'generate'])->middleware('permission:finance.invoice.create')->name('spp.generate');
 Route::get('payments',[StudentPaymentController::class,'index'])->middleware('permission:finance.payment.view')->name('payments.index');Route::get('payments/create',[StudentPaymentController::class,'create'])->middleware('permission:finance.payment.create-manual')->name('payments.create');Route::post('payments',[StudentPaymentController::class,'store'])->middleware('permission:finance.payment.create-manual')->name('payments.store');Route::get('payments/{payment}',[StudentPaymentController::class,'show'])->middleware('permission:finance.payment.view')->name('payments.show');Route::get('payments/{payment}/receipt',[StudentPaymentController::class,'receipt'])->middleware('permission:finance.payment.view')->name('payments.receipt');
 Route::get('bri/reconciliation',[BriReconciliationController::class,'index'])->middleware('permission:finance.bri.reconcile')->name('bri.reconciliation');Route::get('bri/transactions',[BriReconciliationController::class,'transactions'])->middleware('permission:finance.bri.reconcile')->name('bri.transactions');Route::post('bri/reconciliation/{transaction}',[BriReconciliationController::class,'reconcile'])->middleware('permission:finance.bri.reconcile')->name('bri.reconcile');
 Route::get('reports',FinanceReportController::class)->middleware('permission:finance.report.view')->name('reports.index');
});
