<?php
declare(strict_types=1);
use App\Http\Controllers\Hrd\{HrdDashboardController,HrdReportController,PersonnelAttendanceController,PersonnelCashAdvanceController,PersonnelLeaveController,PersonnelPayrollController};use Illuminate\Support\Facades\Route;
Route::middleware(['auth','active','force-password-change'])->prefix('hrd')->name('hrd.')->group(function(){
 Route::get('/',HrdDashboardController::class)->middleware('permission:hrd.dashboard.view')->name('dashboard');
 Route::get('/attendance',[PersonnelAttendanceController::class,'index'])->middleware('permission:personnel-attendance.view-all')->name('attendance.index');
 Route::get('/attendance/mine',[PersonnelAttendanceController::class,'mine'])->middleware('permission:personnel-attendance.check')->name('attendance.mine');
 Route::middleware(['permission:personnel-attendance.check','throttle:30,1'])->group(function(){Route::post('/attendance/challenge',[PersonnelAttendanceController::class,'challenge'])->name('attendance.challenge');Route::post('/attendance/face-verify',[PersonnelAttendanceController::class,'face'])->name('attendance.face');Route::post('/attendance/check-in',[PersonnelAttendanceController::class,'checkIn'])->name('attendance.check-in');Route::post('/attendance/check-out',[PersonnelAttendanceController::class,'checkOut'])->name('attendance.check-out');});
 Route::get('/leave',[PersonnelLeaveController::class,'index'])->middleware('permission:personnel-leave.view')->name('leave.index');Route::post('/leave',[PersonnelLeaveController::class,'store'])->middleware('permission:personnel-leave.request')->name('leave.store');Route::post('/leave/{l}/approve',[PersonnelLeaveController::class,'approve'])->middleware('permission:personnel-leave.approve')->name('leave.approve');Route::post('/leave/{l}/reject',[PersonnelLeaveController::class,'reject'])->middleware('permission:personnel-leave.approve')->name('leave.reject');Route::post('/leave/{l}/cancel',[PersonnelLeaveController::class,'cancel'])->name('leave.cancel');Route::get('/leave/{l}/attachment',[PersonnelLeaveController::class,'attachment'])->name('leave.attachment');
 Route::get('/payroll',[PersonnelPayrollController::class,'index'])->middleware('permission:personnel-payroll.view|personnel-payroll.view-own')->name('payroll.index');Route::post('/payroll',[PersonnelPayrollController::class,'store'])->middleware('permission:personnel-payroll.create')->name('payroll.store');Route::get('/payroll/{p}',[PersonnelPayrollController::class,'show'])->middleware('permission:personnel-payroll.view|personnel-payroll.view-own')->name('payroll.show');Route::get('/payroll/{p}/print',[PersonnelPayrollController::class,'print'])->middleware('permission:personnel-payroll.print')->name('payroll.print');
 Route::get('/cash-advance',[PersonnelCashAdvanceController::class,'index'])->middleware('permission:personnel-cash-advance.view|personnel-cash-advance.view-own')->name('cash-advance.index');Route::post('/cash-advance',[PersonnelCashAdvanceController::class,'store'])->name('cash-advance.store');Route::post('/cash-advance/{a}/{action}',[PersonnelCashAdvanceController::class,'transition'])->whereIn('action',['approve','reject','disburse'])->name('cash-advance.transition');Route::post('/cash-advance/{a}/payment',[PersonnelCashAdvanceController::class,'payment'])->middleware('permission:personnel-cash-advance.payment')->name('cash-advance.payment');
 Route::get('/reports',[HrdReportController::class,'index'])->middleware('permission:personnel-attendance.report')->name('reports.index');
});
