<?php
declare(strict_types=1);
use App\Http\Controllers\Students\{StudentController,StudentExportController,StudentImportController,StudentRfidCardController,StudentStatusController,StudentTemplateController}; use Illuminate\Support\Facades\Route;
Route::middleware(['auth','active','force-password-change'])->prefix('students')->name('students.')->group(function():void{
 Route::get('/create',[StudentController::class,'create'])->middleware('permission:students.create')->name('create'); Route::post('/',[StudentController::class,'store'])->middleware('permission:students.create')->name('store');
 Route::get('/import',[StudentImportController::class,'form'])->middleware('permission:students.import')->name('import.form'); Route::post('/import/preview',[StudentImportController::class,'preview'])->middleware('permission:students.import')->name('import.preview'); Route::post('/import/confirm',[StudentImportController::class,'confirm'])->middleware('permission:students.import')->name('import.confirm'); Route::get('/import/{batch}',[StudentImportController::class,'result'])->middleware('permission:students.import')->name('import.result'); Route::get('/import/{batch}/errors',[StudentImportController::class,'errors'])->middleware('permission:students.import')->name('import.errors');
 Route::get('/template',StudentTemplateController::class)->middleware('permission:students.export')->name('template'); Route::get('/export',StudentExportController::class)->middleware('permission:students.export')->name('export'); Route::get('/',[StudentController::class,'index'])->middleware('permission:students.view')->name('index');
 Route::get('/{student}/edit',[StudentController::class,'edit'])->middleware('permission:students.update')->name('edit'); Route::post('/{student}/rfid-card',[StudentRfidCardController::class,'store'])->middleware('permission:rfid-cards.manage')->name('rfid-card.store'); Route::delete('/{student}/rfid-card',[StudentRfidCardController::class,'destroy'])->middleware('permission:rfid-cards.manage')->name('rfid-card.destroy'); Route::put('/{student}',[StudentController::class,'update'])->middleware('permission:students.update')->name('update'); Route::get('/{student}/status',[StudentStatusController::class,'edit'])->middleware('permission:students.change-status')->name('status.edit'); Route::patch('/{student}/status',[StudentStatusController::class,'update'])->middleware('permission:students.change-status')->name('status.update'); Route::get('/{student}',[StudentController::class,'show'])->middleware('permission:students.view')->name('show');
});
