<?php
declare(strict_types=1);
use App\Http\Controllers\TeachingAssignments\{TeachingAssignmentActivationController,TeachingAssignmentConflictController,TeachingAssignmentController,TeachingAssignmentDutyController,TeachingAssignmentExceptionController,TeachingAssignmentExportController,TeachingAssignmentGuideController,TeachingAssignmentImportController,TeachingAssignmentReportController,TeachingAssignmentSetController};use Illuminate\Support\Facades\Route;
Route::middleware(['auth','active','force-password-change'])->prefix('teaching-assignments')->name('teaching-assignments.')->group(function():void{
 Route::get('/drafts',TeachingAssignmentReportController::class)->defaults('tab','history')->middleware('permission:teaching-assignments.view')->name('drafts');Route::get('/export',TeachingAssignmentExportController::class)->name('export');Route::get('/guide',TeachingAssignmentGuideController::class)->name('guide');Route::get('/personnel/{personnel}/print',[TeachingAssignmentReportController::class,'print'])->name('personnel.print');
 Route::get('/',TeachingAssignmentReportController::class)->middleware('permission:teaching-assignments.view')->name('index');
 Route::middleware('permission:teaching-assignments.import')->prefix('import')->name('import.')->group(function():void{Route::get('/',[TeachingAssignmentImportController::class,'form'])->name('form');Route::post('/preview',[TeachingAssignmentImportController::class,'preview'])->name('preview');Route::get('/{batch}',[TeachingAssignmentImportController::class,'show'])->name('show');Route::get('/{batch}/errors',[TeachingAssignmentImportController::class,'errors'])->name('errors');});
 Route::post('/import/{batch}/draft',[TeachingAssignmentSetController::class,'confirmImport'])->name('import.draft');
 Route::get('/assignments/create',[TeachingAssignmentController::class,'create'])->name('assignments.create');Route::post('/assignments',[TeachingAssignmentController::class,'store'])->name('assignments.store');Route::get('/assignments/{assignment}/edit',[TeachingAssignmentController::class,'edit'])->name('assignments.edit');Route::put('/assignments/{assignment}',[TeachingAssignmentController::class,'update'])->name('assignments.update');Route::delete('/assignments/{assignment}',[TeachingAssignmentController::class,'destroy'])->name('assignments.destroy');
 Route::post('/sets/{set}/rebuild',[TeachingAssignmentSetController::class,'rebuild'])->name('sets.rebuild');Route::post('/sets/{set}/conflicts/resolve',[TeachingAssignmentConflictController::class,'update'])->name('conflicts.resolve');Route::post('/sets/{set}/exceptions',[TeachingAssignmentExceptionController::class,'store'])->name('exceptions.store');Route::post('/sets/{set}/activate',TeachingAssignmentActivationController::class)->name('sets.activate');
 Route::post('/duties',[TeachingAssignmentDutyController::class,'store'])->name('duties.store');Route::put('/duties/{duty}',[TeachingAssignmentDutyController::class,'update'])->name('duties.update');
});

Route::middleware(['auth','active','force-password-change','permission:teaching-assignments.view-own'])->get('/my-teaching-assignments',\App\Http\Controllers\TeachingAssignments\MyTeachingAssignmentController::class)->name('teaching-assignments.my');
