<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Enums\DayOfWeek; use App\Enums\EmployeeStatus; use App\Enums\EmploymentType; use App\Enums\Gender; use App\Enums\SubjectCategory; use App\Models\AcademicYear; use App\Models\Classroom; use App\Models\Employee; use App\Models\GradeLevel; use App\Models\LessonSchedule; use App\Models\Semester; use App\Models\Subject; use App\Models\TeachingAssignment; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Hash; use Spatie\Activitylog\Models\Activity; use Spatie\Permission\Models\Role; use Tests\TestCase;

class AcademicMasterTest extends TestCase
{
    use RefreshDatabase;
    private User $admin; private AcademicYear $year; private Semester $semester; private GradeLevel $grade; private Employee $employee; private Subject $subject; private Classroom $classroom;
    protected function setUp(): void { parent::setUp(); $this->seed(); $this->admin=User::where('email','admin@example.test')->firstOrFail(); $this->year=AcademicYear::where('is_active',true)->firstOrFail(); $this->semester=Semester::where('academic_year_id',$this->year->id)->firstOrFail(); $this->grade=GradeLevel::firstOrFail(); $this->employee=Employee::firstOrFail(); $this->subject=Subject::firstOrFail(); $this->classroom=Classroom::firstOrFail(); }
    public function test_permissions_and_forbidden(): void { foreach(['grade-levels','classrooms','subjects','employees','teaching-assignments','schedules'] as $m) foreach(['view','create','update','delete'] as $a) $this->assertTrue($this->admin->can("$m.$a")); $user=User::factory()->create(['password'=>Hash::make('password')]); $this->actingAs($user)->get(route('grade-levels.index'))->assertForbidden(); }
    public function test_grade_level_crud_and_unique_validation(): void { $this->actingAs($this->admin)->post(route('grade-levels.store'), ['name'=>'Kelas Uji','code'=>'KU','level'=>6])->assertSessionHasErrors(['level']); $this->post(route('grade-levels.store'), ['name'=>'Kelas 7','code'=>'K7','level'=>1])->assertSessionHasErrors(['level']); $this->put(route('grade-levels.update',$this->grade), ['name'=>'Kelas Satu','code'=>'K1X','level'=>1,'is_active'=>1])->assertRedirect(); $this->assertDatabaseHas('grade_levels',['code'=>'K1X']); }
    public function test_classroom_crud_and_unique_per_year(): void { $this->actingAs($this->admin)->post(route('classrooms.store'), ['academic_year_id'=>$this->year->id,'grade_level_id'=>$this->grade->id,'name'=>'1A','code'=>'DUP'])->assertSessionHasErrors('name'); $this->post(route('classrooms.store'), ['academic_year_id'=>$this->year->id,'grade_level_id'=>$this->grade->id,'name'=>'1C','code'=>'1C','capacity'=>30,'homeroom_teacher_id'=>$this->employee->id,'is_active'=>1])->assertRedirect(); $this->assertDatabaseHas('classrooms',['code'=>'1C']); }
    public function test_subject_crud_and_kkm_validation(): void { $this->actingAs($this->admin)->post(route('subjects.store'), ['code'=>'BAD','name'=>'Bad','category'=>SubjectCategory::General->value,'minimum_passing_grade'=>101])->assertSessionHasErrors('minimum_passing_grade'); $this->post(route('subjects.store'), ['code'=>'IPA','name'=>'IPAS','category'=>SubjectCategory::General->value,'minimum_passing_grade'=>75,'is_active'=>1])->assertRedirect(); $this->assertDatabaseHas('subjects',['code'=>'IPA']); }
    public function test_employee_crud_unique_user_and_invalid_photo(): void { $user=User::factory()->create(); $this->actingAs($this->admin)->post(route('employees.store'), ['user_id'=>$user->id,'employee_number'=>'E2','national_identity_number'=>'N2','name'=>'Pegawai Dua','gender'=>Gender::Male->value,'employment_type'=>EmploymentType::SubjectTeacher->value,'employee_status'=>EmployeeStatus::Contract->value,'photo'=>UploadedFile::fake()->create('bad.pdf',10,'application/pdf')])->assertSessionHasErrors('photo'); $this->post(route('employees.store'), ['user_id'=>$user->id,'employee_number'=>'E2','national_identity_number'=>'N2','name'=>'Pegawai Dua','gender'=>Gender::Male->value,'employment_type'=>EmploymentType::SubjectTeacher->value,'employee_status'=>EmployeeStatus::Contract->value,'is_active'=>1])->assertRedirect(); $this->assertDatabaseHas('employees',['user_id'=>$user->id]); $this->post(route('employees.store'), ['user_id'=>$user->id,'employee_number'=>'E3','national_identity_number'=>'N3','name'=>'Pegawai Tiga','gender'=>Gender::Male->value,'employment_type'=>EmploymentType::SubjectTeacher->value,'employee_status'=>EmployeeStatus::Contract->value])->assertSessionHasErrors('user_id'); }
    public function test_assignment_duplicate_and_semester_year_validation(): void { $this->actingAs($this->admin)->post(route('teaching-assignments.store'), $this->assignmentData())->assertRedirect(); $this->post(route('teaching-assignments.store'), $this->assignmentData())->assertSessionHasErrors('employee_id'); $other=AcademicYear::create(['name'=>'2099/2100','starts_on'=>'2099-07-01','ends_on'=>'2100-06-30']); $this->post(route('teaching-assignments.store'), $this->assignmentData(['academic_year_id'=>$other->id]))->assertSessionHasErrors('semester_id'); }
    public function test_schedule_conflicts_and_active_assignment_required(): void { $this->actingAs($this->admin); TeachingAssignment::create($this->assignmentData()+['is_active'=>true]); $this->post(route('schedules.store'), $this->scheduleData())->assertRedirect(); $otherClass=Classroom::create(['academic_year_id'=>$this->year->id,'grade_level_id'=>$this->grade->id,'name'=>'9Z','code'=>'9Z','is_active'=>true]); TeachingAssignment::create($this->assignmentData(['classroom_id'=>$otherClass->id])+['is_active'=>true]); $this->post(route('schedules.store'), $this->scheduleData(['classroom_id'=>$otherClass->id]))->assertSessionHasErrors('employee_id'); $otherEmployee=Employee::create(['name'=>'Guru Lain','gender'=>Gender::Male->value,'employment_type'=>EmploymentType::SubjectTeacher->value,'employee_status'=>EmployeeStatus::Contract->value,'is_active'=>true]); TeachingAssignment::create($this->assignmentData(['employee_id'=>$otherEmployee->id])+['is_active'=>true]); $this->post(route('schedules.store'), $this->scheduleData(['employee_id'=>$otherEmployee->id]))->assertSessionHasErrors('classroom_id'); $this->post(route('schedules.store'), $this->scheduleData(['starts_at'=>'11:00','ends_at'=>'12:00','subject_id'=>999]))->assertSessionHasErrors(); }
    public function test_activity_log_recorded(): void { $this->actingAs($this->admin)->post(route('subjects.store'), ['code'=>'LOG','name'=>'Log','category'=>SubjectCategory::General->value,'is_active'=>1])->assertRedirect(); $this->assertGreaterThan(0, Activity::where('event','subjects.create')->count()); }
    private function assignmentData(array $over=[]): array { return $over+['academic_year_id'=>$this->year->id,'semester_id'=>$this->semester->id,'employee_id'=>$this->employee->id,'classroom_id'=>$this->classroom->id,'subject_id'=>$this->subject->id,'weekly_hours'=>2]; }
    private function scheduleData(array $over=[]): array { return $over+['academic_year_id'=>$this->year->id,'semester_id'=>$this->semester->id,'employee_id'=>$this->employee->id,'classroom_id'=>$this->classroom->id,'subject_id'=>$this->subject->id,'day_of_week'=>DayOfWeek::Monday->value,'starts_at'=>'08:00','ends_at'=>'09:00']; }
}
