<x-app-layout title="Jurnal Mengajar"><div class="index-stack">
<x-ui.page-header title="Jurnal Mengajar" description="Jurnal guru sesuai format administrasi madrasah dan terintegrasi dengan absensi siswa."/>
<div class="flex flex-wrap gap-2">@can('teaching-journals.manage')<a class="btn btn-primary" href="{{route('academic.teaching-journals.create')}}">Isi Jurnal Mengajar</a>@endcan
<a class="btn btn-secondary" href="{{route('academic.teaching-journals.report',array_merge(request()->query(),['format'=>'pdf']))}}">Unduh PDF</a>
@if($template)<a class="btn btn-secondary" href="{{route('academic.teaching-journals.report',array_merge(request()->query(),['format'=>'docx']))}}">Unduh Word</a>@endif</div>
<form class="filter-bar grid gap-3 md:grid-cols-3"><label>Tahun Ajaran<select class="input" name="academic_year_id">@foreach($years as $x)<option value="{{$x->id}}" @selected($year==$x->id)>{{$x->name}}</option>@endforeach</select></label><label>Semester<select class="input" name="semester_id">@foreach($semesters as $x)<option value="{{$x->id}}" @selected($semester==$x->id)>{{$x->display_name}}</option>@endforeach</select></label><label>Tanggal<input class="input" type="date" name="journal_date" value="{{$date}}"></label><label>Rombel<select class="input" name="classroom_id"><option value="">Semua rombel</option>@foreach($rooms as $x)<option value="{{$x->id}}" @selected(request('classroom_id')==$x->id)>{{$x->display_name}}</option>@endforeach</select></label><label>Mata Pelajaran<select class="input" name="academic_subject_id"><option value="">Semua mata pelajaran</option>@foreach($subjects as $x)<option value="{{$x->id}}" @selected(request('academic_subject_id')==$x->id)>{{$x->name}}</option>@endforeach</select></label>@can('teaching-journals.view-all')<label>Guru<select class="input" name="personnel_id"><option value="">Semua guru</option>@foreach($teachers as $x)<option value="{{$x->id}}" @selected(request('personnel_id')==$x->id)>{{$x->full_name}}</option>@endforeach</select></label>@endcan<button class="btn btn-primary md:col-span-3">Terapkan Filter</button></form>
@can('teaching-journals.manage')<section class="card card-body"><h2 class="font-black text-emerald-900">Template Word Jurnal</h2><p class="text-sm text-slate-600">Unggah DOCX dengan tabel jurnal yang memiliki kolom No, Hari/Tanggal, Uraian Mengajar, dan Keterangan. Sistem akan menggunakan baris data kosong pertama secara otomatis. Untuk pengaturan khusus, baris data dapat berisi placeholder: <code>${no}</code>, <code>${hari_tanggal}</code>, <code>${jam_ke}</code>, <code>${mapel}</code>, <code>${guru}</code>, <code>${uraian_mengajar}</code>, <code>${metode}</code>, <code>${hadir}</code>, <code>${tidak_hadir}</code>, <code>${sakit}</code>, <code>${izin}</code>, <code>${alpa}</code>, dan <code>${keterangan}</code>. Placeholder identitas: <code>${tahun_ajaran}</code>, <code>${semester}</code>, <code>${kelas}</code>, <code>${nama_guru}</code>, dan <code>${bulan}</code>.</p>@if($template)<p class="my-2 text-sm font-semibold">Aktif: {{$template->name}} ({{$template->original_name}})</p>@endif<form method="post" enctype="multipart/form-data" action="{{route('academic.teaching-journals.template.store')}}" class="mt-3 grid gap-3 md:grid-cols-3">@csrf<input class="input" required name="name" placeholder="Nama template"><input class="input" required type="file" accept=".docx" name="template"><button class="btn btn-primary">Unggah dan Aktifkan</button></form></section>@endcan
<div class="grid gap-4 md:grid-cols-2">@forelse($journals as $j)<a href="{{route('academic.teaching-journals.show',$j)}}" class="card p-4"><div class="flex justify-between"><strong>{{$j->subject->name}}</strong><span class="badge badge-success">Tercatat</span></div><p class="mt-1 text-sm"><span class="text-slate-500">Uraian:</span> {{$j->topic}}</p><p class="text-sm text-slate-500">{{$j->journal_date->translatedFormat('d F Y')}} · {{$j->classroom->display_name}} · {{$j->personnel->full_name}}</p><span class="mt-3 block text-right text-sm font-semibold text-emerald-700">Lihat Detail →</span></a>@empty<x-ui.empty-state title="Belum ada jurnal mengajar pada filter ini."/>@endforelse</div>{{$journals->links()}}
</div></x-app-layout>
