<?php

declare(strict_types=1);

namespace App\Http\Controllers\Employee;

use App\Enums\EmployeeDocumentType; use App\Enums\EmployeeStatus; use App\Enums\EmploymentType; use App\Enums\Gender; use App\Http\Controllers\Controller; use App\Http\Requests\Employee\CreateEmployeeAccountRequest; use App\Http\Requests\Employee\EmployeeDocumentRequest; use App\Http\Requests\Employee\ImportEmployeesRequest; use App\Http\Requests\Employee\LinkEmployeeAccountRequest; use App\Http\Requests\Employee\StoreEmployeeRequest; use App\Http\Requests\Employee\UpdateEmployeeRequest; use App\Models\Employee; use App\Models\EmployeeDocument; use App\Models\User; use App\Services\Employee\EmployeeImportService; use App\Services\Employee\EmployeeImportTemplateService; use App\Services\Employee\EmployeeService; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\View\View; use Spatie\Activitylog\Models\Activity; use Spatie\Permission\Models\Role;

class EmployeeController extends Controller
{
    public function index(Request $request): View
    { $this->authorizeViewAny(); $employees=$this->query($request)->with('user')->latest()->paginate(15)->withQueryString(); return view('employees.index',$this->options()+['title'=>'Guru & Pegawai','employees'=>$employees,'filters'=>$request->only(['search','employment_type','employee_status','is_active','position'])]); }
    public function importForm(): View { return view('employees.import', ['title'=>'Import Data Guru & Pegawai']); }
    public function importTemplate(EmployeeImportTemplateService $service) { return response($service->content(), 200, ['Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Content-Disposition' => 'attachment; filename=template-import-personalia.xlsx']); }
    public function import(ImportEmployeesRequest $request, EmployeeImportService $service): RedirectResponse { $result=$service->import($request->file('file')); return redirect()->route('employees.index')->with('status', "Import selesai. Baru: {$result['created']}, diperbarui: {$result['updated']}, dilewati: {$result['skipped']}.")->with('import_errors', array_slice($result['errors'],0,10)); }
    public function create(): View { return view('employees.form',$this->options()+['title'=>'Tambah Guru/Pegawai','employee'=>new Employee,'mode'=>'create','availableUsers'=>$this->availableUsers(),'roles'=>Role::orderBy('name')->get()]); }
    public function store(StoreEmployeeRequest $request, EmployeeService $service): RedirectResponse { $employee=$service->create($request->validated()+['is_active'=>$request->boolean('is_active', true)], $request->file('photo')); return redirect()->route('employees.show',$employee)->with('status','Data guru/pegawai berhasil disimpan.'); }
    public function show(Employee $employee): View { $this->authorizeView($employee); return view('employees.show',$this->options()+['title'=>'Detail Guru & Pegawai','employee'=>$employee->load(['user','documents'=>fn($q)=>$q->latest()]),'availableUsers'=>$this->availableUsers($employee),'roles'=>Role::orderBy('name')->get(),'activities'=>Activity::query()->where('subject_type',Employee::class)->where('subject_id',$employee->id)->latest()->limit(10)->get()]); }
    public function edit(Employee $employee): View { return view('employees.form',$this->options()+['title'=>'Edit Guru/Pegawai','employee'=>$employee,'mode'=>'edit','availableUsers'=>$this->availableUsers($employee),'roles'=>Role::orderBy('name')->get()]); }
    public function update(UpdateEmployeeRequest $request, Employee $employee, EmployeeService $service): RedirectResponse { $service->update($employee,$request->validated(),$request->file('photo')); return redirect()->route('employees.show',$employee)->with('status','Data guru/pegawai berhasil diperbarui.'); }
    public function deactivate(Employee $employee, EmployeeService $service): RedirectResponse { abort_unless(auth()->user()?->can('employees.activate'),403); $service->activate($employee,false); return back()->with('status','Pegawai dinonaktifkan.'); }
    public function activate(Employee $employee, EmployeeService $service): RedirectResponse { abort_unless(auth()->user()?->can('employees.activate'),403); $service->activate($employee,true); return back()->with('status','Pegawai diaktifkan kembali.'); }
    public function storeDocument(EmployeeDocumentRequest $request, Employee $employee, EmployeeService $service): RedirectResponse { $service->storeDocument($employee,$request->validated(),$request->file('file')); return back()->with('status','Dokumen berhasil diunggah.'); }
    public function updateDocument(EmployeeDocumentRequest $request, EmployeeDocument $document, EmployeeService $service): RedirectResponse { $data=$request->validated(); if ($request->hasFile('file')) $service->storeDocument($document->employee,$data,$request->file('file'),$document); else $document->update($data); return back()->with('status','Dokumen berhasil diperbarui.'); }
    public function downloadDocument(EmployeeDocument $document) { abort_unless(auth()->user()?->can('employees.manage-documents') || auth()->id()===$document->employee->user_id,403); return Storage::disk('local')->download($document->file_path, $document->file_name); }
    public function destroyDocument(EmployeeDocument $document, EmployeeService $service): RedirectResponse { abort_unless(auth()->user()?->can('employees.manage-documents'),403); $service->deleteDocument($document); return back()->with('status','Dokumen berhasil dihapus.'); }
    public function linkAccount(LinkEmployeeAccountRequest $request, Employee $employee, EmployeeService $service): RedirectResponse { $service->linkAccount($employee,User::findOrFail($request->integer('user_id'))); return back()->with('status','Akun berhasil dihubungkan.'); }
    public function createAccount(CreateEmployeeAccountRequest $request, Employee $employee, EmployeeService $service): RedirectResponse { $service->createAccount($employee,$request->validated('email'),$request->validated('role')); return back()->with('status','Akun pengguna berhasil dibuat. Password awal dibuat aman oleh sistem.'); }
    public function export(Request $request) { abort_unless(auth()->user()?->can('employees.export'),403); $rows=$this->query($request)->get(); return response()->streamDownload(function() use($rows){ $out=fopen('php://output','w'); fputcsv($out,['Nama','L/P','Tempat Tgl Lahir','Status','NIY','NIP','Pangkat/Golongan','Peg.ID','Pendidikan Terakhir','Jabatan','Sertifikasi','Mapel Sertifikasi','Jumlah JPL','Jenis Rekening','No. Rekening','No. HP/WA','Email Aktif','Status Aktif']); foreach($rows as $e) fputcsv($out,[$e->fullName(),$e->gender?->value==='laki_laki'?'L':'P',trim(($e->birth_place ?: '').', '.($e->birth_date?->translatedFormat('d F Y') ?: ''),', '),$e->employee_status?->label(),$e->employee_number,$e->nip,$e->rank_grade,$e->peg_id,$e->last_education,$e->position,$e->certification_status,$e->certification_subject,$e->weekly_teaching_hours,$e->bank_name,$e->bank_account_number,$e->whatsapp,$e->email,$e->is_active?'Aktif':'Tidak Aktif']); fclose($out); }, 'guru-pegawai.csv', ['Content-Type'=>'text/csv; charset=UTF-8']); }
    public function mine(): View { $employee=auth()->user()?->employee; abort_unless($employee,403); return $this->show($employee); }
    private function query(Request $request) { return Employee::query()->when($request->filled('search'), fn($q)=>$q->where(fn($s)=>$s->where('name','like','%'.$request->search.'%')->orWhere('nip','like','%'.$request->search.'%')->orWhere('nuptk','like','%'.$request->search.'%')->orWhere('employee_number','like','%'.$request->search.'%')->orWhere('whatsapp','like','%'.$request->search.'%')))->when($request->filled('employment_type'), fn($q)=>$q->where('employment_type',$request->employment_type))->when($request->filled('employee_status'), fn($q)=>$q->where('employee_status',$request->employee_status))->when($request->filled('position'), fn($q)=>$q->where('position','like','%'.$request->position.'%'))->when($request->filled('is_active'), fn($q)=>$q->where('is_active',(bool)$request->integer('is_active'))); }
    private function options(): array { return ['types'=>EmploymentType::cases(),'statuses'=>EmployeeStatus::cases(),'genders'=>Gender::cases(),'documentTypes'=>EmployeeDocumentType::cases()]; }
    private function availableUsers(?Employee $employee=null) { return User::query()->where(fn($q)=>$q->whereDoesntHave('employee')->when($employee?->user_id,fn($s)=>$s->orWhere('id', $employee->user_id)))->orderBy('name')->get(); }
    private function authorizeViewAny(): void { abort_unless(auth()->user()?->can('employees.view') || auth()->user()?->can('employees.view-own'),403); if (! auth()->user()?->can('employees.view')) abort(403); }
    private function authorizeView(Employee $employee): void { abort_unless(auth()->user()?->can('employees.view') || (auth()->user()?->can('employees.view-own') && auth()->id()===$employee->user_id),403); }
}
