<x-app-layout title="Absensi Siswa"><div class="index-stack">
@if(session('success'))<x-ui.alert type="success">{{ session('success') }}</x-ui.alert>@endif @if($errors->any())<x-ui.alert type="danger">{{ $errors->first() }}</x-ui.alert>@endif
<form method="get" class="filter-bar grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
@foreach([['Tahun Ajaran','academic_year_id',$years,$year,'name'],['Semester','semester_id',$semesters,$semester,'display_name'],['Rombel','classroom_id',$rooms,$room?->id,'display_name']] as [$label,$name,$items,$selected,$display])<label>{{ $label }}<select name="{{ $name }}" class="input" @if($name==='academic_year_id') onchange="this.form.submit()" @endif>@if($name==='classroom_id')<option value="">Pilih rombel</option>@endif @foreach($items as $item)<option value="{{$item->id}}" @selected($selected==$item->id)>{{$item->{$display} }}</option>@endforeach</select></label>@endforeach
<label>Tanggal<input class="input" type="date" name="attendance_date" value="{{$date}}"></label><button class="btn btn-primary self-end">Tampilkan Siswa</button></form>
@if(!$room)<x-ui.empty-state class="min-h-48 grid place-content-center" title="Pilih rombel untuk mulai mengisi absensi." />@else
<form method="post" action="{{route('academic.attendance.store')}}" class="space-y-3">@csrf<input type="hidden" name="academic_year_id" value="{{$year}}"><input type="hidden" name="semester_id" value="{{$semester}}"><input type="hidden" name="classroom_id" value="{{$room->id}}"><input type="hidden" name="attendance_date" value="{{$date}}">
<section class="card compact-summary"><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-semibold text-emerald-950">{{$room->display_name}}</h2><span class="rounded-full px-2 py-0.5 text-xs font-semibold {{$rfidEnabled ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-500'}}">{{$rfidEnabled ? '● RFID Aktif' : 'RFID Nonaktif'}}</span>@if($rfidEnabled && $date===today()->toDateString())<span data-reader-status class="text-xs font-semibold text-slate-500">● Memeriksa reader...</span><span data-live-status class="text-xs font-semibold text-slate-500">● Menghubungkan live...</span><span data-live-synced class="text-xs text-slate-400"></span>@endif</div><p class="text-sm text-slate-500">{{ \Illuminate\Support\Carbon::parse($date)->translatedFormat('d F Y') }}</p></div><div class="flex flex-wrap gap-x-5 gap-y-1 text-sm"><span><b>{{$students->count()}}</b> Siswa</span>@foreach(['present'=>'Hadir','sick'=>'Sakit','permitted'=>'Izin','absent'=>'Alpa'] as $key=>$label)<span><b data-attendance-count="{{$key}}">{{$saved->where('status.value',$key)->count()}}</b> {{$label}}</span>@endforeach</div><button type="button" id="all-present" class="btn btn-secondary">Hadir Semua</button></section>
<section class="card overflow-hidden"><div class="hidden overflow-x-auto md:block"><table class="data-table attendance-table min-w-[900px]"><colgroup><col class="w-12"><col class="w-80"><col class="w-[380px]"><col></colgroup><thead><tr><th>No</th><th>Siswa</th><th>Status</th><th>Catatan</th></tr></thead><tbody>@forelse($students as $student)@php($entry=$saved->get($student->id))<tr data-attendance-student="{{$student->id}}"><td>{{$loop->iteration}}</td><td><strong class="font-semibold text-slate-900">{{$student->full_name}}</strong><small class="block text-slate-500">NIS/NISN {{$student->nis ?? $student->nisn ?? '—'}}</small><small data-attendance-source class="block text-slate-400">{{ ($entry?->source?->value ?? $entry?->source) === 'rfid' ? 'RFID • '.($entry?->scanned_at?->format('H:i') ?? '—') : ($entry ? 'Manual' : 'Belum disimpan') }}</small></td><td><input type="hidden" name="attendances[{{$loop->index}}][student_id]" value="{{$student->id}}"><div class="attendance-segments">@foreach(['present'=>'Hadir','sick'=>'Sakit','permitted'=>'Izin','absent'=>'Alpa'] as $value=>$label)<label class="segment segment-{{$value}}"><input class="peer attendance-radio sr-only" type="radio" name="attendances[{{$loop->parent->index}}][status]" value="{{$value}}" @checked(($entry?->status?->value??'present')===$value)><span>{{$label}}</span></label>@endforeach</div></td><td><input class="input h-10" name="attendances[{{$loop->index}}][notes]" value="{{$entry?->notes}}" placeholder="Catatan opsional"></td></tr>@empty<tr><td colspan="4" class="text-center">Belum ada siswa aktif pada rombel ini.</td></tr>@endforelse</tbody></table></div>
<div class="divide-y md:hidden">@foreach($students as $student)@php($entry=$saved->get($student->id))<article class="p-4" data-attendance-student="{{$student->id}}"><strong class="font-semibold">{{$student->full_name}}</strong><p class="text-sm text-slate-500">NIS/NISN {{$student->nis ?? $student->nisn ?? '—'}}</p><p data-attendance-source class="text-xs text-slate-400">{{ ($entry?->source?->value ?? $entry?->source) === 'rfid' ? 'RFID • '.($entry?->scanned_at?->format('H:i') ?? '—') : ($entry ? 'Manual' : 'Belum disimpan') }}</p><input type="hidden" name="attendances[{{$loop->index}}][student_id]" value="{{$student->id}}"><div class="attendance-segments mt-3 grid grid-cols-2">@foreach(['present'=>'Hadir','sick'=>'Sakit','permitted'=>'Izin','absent'=>'Alpa'] as $value=>$label)<label class="segment segment-{{$value}}"><input class="peer attendance-radio sr-only" type="radio" name="attendances[{{$loop->parent->index}}][status]" value="{{$value}}" @checked(($entry?->status?->value??'present')===$value)><span>{{$label}}</span></label>@endforeach</div><input class="input mt-3 h-10" name="attendances[{{$loop->index}}][notes]" value="{{$entry?->notes}}" placeholder="Catatan opsional"></article>@endforeach</div></section>
<div class="flex flex-col-reverse justify-between gap-2 sm:flex-row"><a class="btn btn-secondary" href="{{route('academic.attendance.history',['classroom_id'=>$room->id])}}">Riwayat Absensi</a><button class="btn btn-primary sm:min-w-44">Simpan Absensi</button></div></form>@endif
</div><div id="rfid-live-toasts" class="fixed inset-x-3 top-3 z-50 flex flex-col items-end gap-3 sm:left-auto sm:right-5 sm:w-[26rem]" aria-live="polite" aria-atomic="false"></div>
<style>
.rfid-toast{position:relative;width:100%;overflow:hidden;border:1px solid #e2e8f0;border-left-width:5px;border-radius:1rem;background:#fff;padding:1rem 1rem 1rem .875rem;box-shadow:0 18px 45px -18px rgb(15 23 42/.35);animation:rfid-toast-in .24s ease-out}
.rfid-toast--success{border-left-color:#059669}.rfid-toast--warning{border-left-color:#d97706}.rfid-toast--error{border-left-color:#dc2626}
.rfid-toast__layout{display:grid;grid-template-columns:2.5rem minmax(0,1fr) 1.75rem;gap:.75rem;align-items:start}.rfid-toast__icon{display:grid;height:2.5rem;width:2.5rem;place-items:center;border-radius:.75rem;font-size:1.25rem;font-weight:800}.rfid-toast--success .rfid-toast__icon{background:#d1fae5;color:#065f46}.rfid-toast--warning .rfid-toast__icon{background:#fef3c7;color:#92400e}.rfid-toast--error .rfid-toast__icon{background:#fee2e2;color:#991b1b}.rfid-toast__title{font-size:.75rem;font-weight:800;letter-spacing:.08em}.rfid-toast--success .rfid-toast__title{color:#065f46}.rfid-toast--warning .rfid-toast__title{color:#92400e}.rfid-toast--error .rfid-toast__title{color:#991b1b}.rfid-toast__name{margin-top:.25rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:1.125rem;font-weight:750;color:#0f172a}.rfid-toast__meta,.rfid-toast__message{margin-top:.2rem;font-size:.8125rem;line-height:1.35;color:#475569}.rfid-toast__message{margin-top:.55rem;color:#334155}.rfid-toast__chip{display:inline-flex;margin-top:.65rem;border-radius:999px;background:#f1f5f9;padding:.25rem .6rem;font-size:.75rem;font-weight:700;color:#334155}.rfid-toast__close{display:grid;height:1.75rem;width:1.75rem;place-items:center;border-radius:999px;color:#64748b;font-size:1.2rem;line-height:1}.rfid-toast__close:hover{background:#f1f5f9;color:#0f172a}.rfid-toast--leaving{animation:rfid-toast-out .18s ease-in forwards}.rfid-live-highlight-success{animation:rfid-highlight-success 1.8s ease-out}.rfid-live-highlight-warning{animation:rfid-highlight-warning 1.8s ease-out}.rfid-live-highlight-error{animation:rfid-highlight-error 1.8s ease-out}
@keyframes rfid-toast-in{from{opacity:0;transform:translate3d(1rem,-.25rem,0)}to{opacity:1;transform:none}}@keyframes rfid-toast-out{to{opacity:0;transform:translateX(1rem)}}@keyframes rfid-highlight-success{0%,35%{background:#d1fae5}100%{background:transparent}}@keyframes rfid-highlight-warning{0%,35%{background:#fef3c7}100%{background:transparent}}@keyframes rfid-highlight-error{0%,35%{background:#fee2e2}100%{background:transparent}}@media(max-width:640px){.rfid-toast{padding:.875rem}.rfid-toast__layout{grid-template-columns:2.25rem minmax(0,1fr) 1.5rem;gap:.625rem}.rfid-toast__icon{height:2.25rem;width:2.25rem}}
</style>
<script>
(() => {
 const allPresent=document.getElementById('all-present');
 const dirty=new Set();
 document.querySelectorAll('.attendance-radio,input[name$="[notes]"]').forEach(input=>input.addEventListener('input',()=>{const holder=input.closest('[data-attendance-student]');if(holder)dirty.add(holder.dataset.attendanceStudent)}));
 allPresent?.addEventListener('click',()=>document.querySelectorAll('.attendance-radio[value="present"]').forEach(el=>{el.checked=true;const holder=el.closest('[data-attendance-student]');if(holder)dirty.add(holder.dataset.attendanceStudent)}));
 const enabled=@json($rfidEnabled && (bool) $room && $date === today()->toDateString());
 if(!enabled)return;
 const url=@json(route('academic.attendance.live',[],false)); let cursor=@json((int)$liveCursor),busy=false,timer=null,consecutiveFailures=0,visibleToasts=0;
 const status=document.querySelector('[data-live-status]'),readerStatus=document.querySelector('[data-reader-status]'),synced=document.querySelector('[data-live-synced]'),toasts=document.getElementById('rfid-live-toasts');
 const handledEventIds=new Set(),toastQueue=[],successCodes=['ATTENDANCE_CREATED','ATTENDANCE_RECORDED'],warningCodes=['ALREADY_ATTENDED','MANUAL_STATUS_LOCKED'];
 const toastVariant=event=>warningCodes.includes(event.code)?'warning':successCodes.includes(event.code)?'success':'error';
 const showNextToast=()=>{while(visibleToasts<3&&toastQueue.length){const event=toastQueue.shift(),variant=toastVariant(event),titles={ATTENDANCE_CREATED:'ABSENSI BERHASIL',ATTENDANCE_RECORDED:'ABSENSI BERHASIL',ALREADY_ATTENDED:'SUDAH ABSEN',MANUAL_STATUS_LOCKED:'STATUS SUDAH DITETAPKAN'},icons={success:'✓',warning:'!',error:'×'};const el=document.createElement('div');el.className=`rfid-toast rfid-toast--${variant}`;el.setAttribute('role',variant==='error'?'alert':'status');el.innerHTML='<div class="rfid-toast__layout"><div class="rfid-toast__icon" aria-hidden="true"></div><div><p class="rfid-toast__title"></p><p class="rfid-toast__name"></p><p class="rfid-toast__meta"></p><p class="rfid-toast__message"></p><span class="rfid-toast__chip"></span></div><button type="button" class="rfid-toast__close" aria-label="Tutup notifikasi">×</button></div>';el.querySelector('.rfid-toast__icon').textContent=icons[variant];el.querySelector('.rfid-toast__title').textContent=titles[event.code]??'ABSENSI GAGAL';const name=el.querySelector('.rfid-toast__name');name.textContent=event.student_name??'';name.hidden=!event.student_name;const meta=el.querySelector('.rfid-toast__meta');meta.textContent=event.nis?`NIS/NISN: ${event.nis}`:'';meta.hidden=!event.nis;const message=el.querySelector('.rfid-toast__message');message.textContent=event.code==='ALREADY_ATTENDED'?'Siswa sudah melakukan absensi hari ini. Tidak perlu melakukan absensi lagi.':(variant==='error'||event.code==='MANUAL_STATUS_LOCKED'?event.message??'Permintaan absensi tidak dapat diproses.':'');message.hidden=!message.textContent;const chip=el.querySelector('.rfid-toast__chip'),time=event.attendance_time??event.scanned_at;chip.textContent=time?`${event.status_label??'Hadir'} • ${time}`:'';chip.hidden=!time;let closed=false,timeout;const close=()=>{if(closed)return;closed=true;el.classList.add('rfid-toast--leaving');setTimeout(()=>{el.remove();visibleToasts--;showNextToast()},180)};const startTimer=()=>{timeout=setTimeout(close,4000)};el.querySelector('button').onclick=close;el.addEventListener('mouseenter',()=>clearTimeout(timeout));el.addEventListener('mouseleave',startTimer);toasts.append(el);visibleToasts++;startTimer()}};
 const enqueueToast=(event)=>{toastQueue.push(event);showNextToast()};
 const highlight=(id,type)=>{if(!id)return;document.querySelectorAll(`[data-attendance-student="${CSS.escape(id)}"]`).forEach(row=>{row.classList.remove('rfid-live-highlight-success','rfid-live-highlight-warning','rfid-live-highlight-error');void row.offsetWidth;row.classList.add(`rfid-live-highlight-${type}`)})};
 const apply=(event)=>{const eventId=String(event.id);if(!event.id||handledEventIds.has(eventId))return;handledEventIds.add(eventId);const id=String(event.student_id??''),variant=toastVariant(event);if(successCodes.includes(event.code)&&dirty.has(id)){enqueueToast({...event,code:'MANUAL_STATUS_LOCKED',message:'Kartu terbaca, tetapi perubahan manual belum disimpan; tampilan tidak ditimpa.'});highlight(id,'warning');return;}enqueueToast(event);highlight(id,variant);if(!successCodes.includes(event.code))return;document.querySelectorAll(`[data-attendance-student="${CSS.escape(id)}"]`).forEach(row=>{const present=row.querySelector('.attendance-radio[value="present"]'),source=row.querySelector('[data-attendance-source]');if(present)present.checked=true;if(source)source.textContent=`RFID • ${event.scanned_at}`})};
 const schedule=()=>{clearTimeout(timer);timer=setTimeout(poll,document.visibilityState==='hidden'?10000:2500)};
 async function poll(){if(busy){schedule();return}busy=true;try{const query=new URLSearchParams({classroom_id:@json((string)$room?->id),attendance_date:@json($date),cursor:String(cursor)});const response=await fetch(`${url}?${query}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.events)||!data.counts||!data.reader)throw new Error('Payload live tidak valid');cursor=Number(data.cursor)||cursor;data.events.forEach(apply);Object.entries(data.counts).forEach(([key,value])=>{const el=document.querySelector(`[data-attendance-count="${key}"]`);if(el)el.textContent=value});consecutiveFailures=0;status.textContent='● Live tersambung';status.className='text-xs font-semibold text-emerald-700';readerStatus.textContent=data.reader.online?'● Reader Online':'● Reader Offline';readerStatus.className=`text-xs font-semibold ${data.reader.online?'text-emerald-700':'text-red-600'}`;synced.textContent=`Terakhir sinkron: ${new Date().toLocaleTimeString('id-ID')}`}catch(e){consecutiveFailures++;status.textContent=consecutiveFailures<3?'● Live menyambungkan ulang...':'● Live terputus';status.className=`text-xs font-semibold ${consecutiveFailures<3?'text-amber-600':'text-red-600'}`}finally{busy=false;schedule()}}
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){clearTimeout(timer);poll()}});poll();
})();
</script></x-app-layout>
