<x-app-layout title="Absensi Siswa"><div class="index-stack">
@if(session('success'))<x-ui.alert type="success">{{ session('success') }}</x-ui.alert>@endif @if($errors->any())<x-ui.alert type="danger">{{ $errors->first() }}</x-ui.alert>@endif
<form method="get" class="filter-bar grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
@foreach([['Tahun Ajaran','academic_year_id',$years,$year,'name'],['Semester','semester_id',$semesters,$semester,'display_name'],['Rombel','classroom_id',$rooms,$room?->id,'display_name']] as [$label,$name,$items,$selected,$display])<label>{{ $label }}<select name="{{ $name }}" class="input" @if($name==='academic_year_id') onchange="this.form.submit()" @endif>@if($name==='classroom_id')<option value="">Pilih rombel</option>@endif @foreach($items as $item)<option value="{{$item->id}}" @selected($selected==$item->id)>{{$item->{$display} }}</option>@endforeach</select></label>@endforeach
<label>Tanggal<input class="input" type="date" name="attendance_date" value="{{$date}}"></label><button class="btn btn-primary self-end">Tampilkan Siswa</button></form>
@if(!$room)<x-ui.empty-state class="min-h-48 grid place-content-center" title="Pilih rombel untuk mulai mengisi absensi." />@else
<form method="post" action="{{route('academic.attendance.store')}}" class="space-y-3">@csrf<input type="hidden" name="academic_year_id" value="{{$year}}"><input type="hidden" name="semester_id" value="{{$semester}}"><input type="hidden" name="classroom_id" value="{{$room->id}}"><input type="hidden" name="attendance_date" value="{{$date}}">
<section class="card compact-summary"><div><div class="flex items-center gap-2"><h2 class="font-semibold text-emerald-950">{{$room->display_name}}</h2><span class="rounded-full px-2 py-0.5 text-xs font-semibold {{$rfidEnabled ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-500'}}">{{$rfidEnabled ? '● RFID Aktif' : 'RFID Nonaktif'}}</span>@if($rfidEnabled && $date===today()->toDateString())<span data-live-status class="text-xs font-semibold text-slate-500">● Menghubungkan live...</span><span data-live-synced class="text-xs text-slate-400"></span>@endif</div><p class="text-sm text-slate-500">{{ \Illuminate\Support\Carbon::parse($date)->translatedFormat('d F Y') }}</p></div><div class="flex flex-wrap gap-x-5 gap-y-1 text-sm"><span><b>{{$students->count()}}</b> Siswa</span>@foreach(['present'=>'Hadir','sick'=>'Sakit','permitted'=>'Izin','absent'=>'Alpa'] as $key=>$label)<span><b data-attendance-count="{{$key}}">{{$saved->where('status.value',$key)->count()}}</b> {{$label}}</span>@endforeach</div><button type="button" id="all-present" class="btn btn-secondary">Hadir Semua</button></section>
<section class="card overflow-hidden"><div class="hidden overflow-x-auto md:block"><table class="data-table attendance-table min-w-[900px]"><colgroup><col class="w-12"><col class="w-80"><col class="w-[380px]"><col></colgroup><thead><tr><th>No</th><th>Siswa</th><th>Status</th><th>Catatan</th></tr></thead><tbody>@forelse($students as $student)@php($entry=$saved->get($student->id))<tr data-attendance-student="{{$student->id}}"><td>{{$loop->iteration}}</td><td><strong class="font-semibold text-slate-900">{{$student->full_name}}</strong><small class="block text-slate-500">NIS/NISN {{$student->nis ?? $student->nisn ?? '—'}}</small><small data-attendance-source class="block text-slate-400">{{ ($entry?->source?->value ?? $entry?->source) === 'rfid' ? 'RFID • '.($entry?->scanned_at?->format('H:i') ?? '—') : ($entry ? 'Manual' : 'Belum disimpan') }}</small></td><td><input type="hidden" name="attendances[{{$loop->index}}][student_id]" value="{{$student->id}}"><div class="attendance-segments">@foreach(['present'=>'Hadir','sick'=>'Sakit','permitted'=>'Izin','absent'=>'Alpa'] as $value=>$label)<label class="segment segment-{{$value}}"><input class="peer attendance-radio sr-only" type="radio" name="attendances[{{$loop->parent->index}}][status]" value="{{$value}}" @checked(($entry?->status?->value??'present')===$value)><span>{{$label}}</span></label>@endforeach</div></td><td><input class="input h-10" name="attendances[{{$loop->index}}][notes]" value="{{$entry?->notes}}" placeholder="Catatan opsional"></td></tr>@empty<tr><td colspan="4" class="text-center">Belum ada siswa aktif pada rombel ini.</td></tr>@endforelse</tbody></table></div>
<div class="divide-y md:hidden">@foreach($students as $student)@php($entry=$saved->get($student->id))<article class="p-4" data-attendance-student="{{$student->id}}"><strong class="font-semibold">{{$student->full_name}}</strong><p class="text-sm text-slate-500">NIS/NISN {{$student->nis ?? $student->nisn ?? '—'}}</p><p data-attendance-source class="text-xs text-slate-400">{{ ($entry?->source?->value ?? $entry?->source) === 'rfid' ? 'RFID • '.($entry?->scanned_at?->format('H:i') ?? '—') : ($entry ? 'Manual' : 'Belum disimpan') }}</p><input type="hidden" name="attendances[{{$loop->index}}][student_id]" value="{{$student->id}}"><div class="attendance-segments mt-3 grid grid-cols-2">@foreach(['present'=>'Hadir','sick'=>'Sakit','permitted'=>'Izin','absent'=>'Alpa'] as $value=>$label)<label class="segment segment-{{$value}}"><input class="peer attendance-radio sr-only" type="radio" name="attendances[{{$loop->parent->index}}][status]" value="{{$value}}" @checked(($entry?->status?->value??'present')===$value)><span>{{$label}}</span></label>@endforeach</div><input class="input mt-3 h-10" name="attendances[{{$loop->index}}][notes]" value="{{$entry?->notes}}" placeholder="Catatan opsional"></article>@endforeach</div></section>
<div class="flex flex-col-reverse justify-between gap-2 sm:flex-row"><a class="btn btn-secondary" href="{{route('academic.attendance.history',['classroom_id'=>$room->id])}}">Riwayat Absensi</a><button class="btn btn-primary sm:min-w-44">Simpan Absensi</button></div></form>@endif
</div><div id="rfid-live-toasts" class="fixed inset-x-3 top-3 z-50 flex flex-col items-end gap-2 sm:left-auto sm:right-5 sm:w-96" aria-live="polite"></div>
<style>.rfid-live-highlight{animation:rfid-highlight 2.5s ease-out}@keyframes rfid-highlight{0%,35%{background:#d1fae5}100%{background:transparent}}</style>
<script>
(() => {
 const allPresent=document.getElementById('all-present');
 const dirty=new Set();
 document.querySelectorAll('.attendance-radio,input[name$="[notes]"]').forEach(input=>input.addEventListener('input',()=>{const holder=input.closest('[data-attendance-student]');if(holder)dirty.add(holder.dataset.attendanceStudent)}));
 allPresent?.addEventListener('click',()=>document.querySelectorAll('.attendance-radio[value="present"]').forEach(el=>{el.checked=true;const holder=el.closest('[data-attendance-student]');if(holder)dirty.add(holder.dataset.attendanceStudent)}));
 const enabled=@json($rfidEnabled && (bool) $room && $date === today()->toDateString());
 if(!enabled)return;
 const url=@json(route('academic.attendance.live',[],false)); let cursor=@json((int)$liveCursor),busy=false,timer=null,showingToast=false;
 const status=document.querySelector('[data-live-status]'),synced=document.querySelector('[data-live-synced]'),toasts=document.getElementById('rfid-live-toasts');
 const handledEventIds=new Set(),toastQueue=[];
 const showNextToast=()=>{if(showingToast||toastQueue.length===0)return;showingToast=true;const event=toastQueue.shift();const duplicate=['ALREADY_ATTENDED','MANUAL_STATUS_LOCKED'].includes(event.code);const styles=event.success&&!duplicate?'border-emerald-300 bg-emerald-50':duplicate?'border-amber-300 bg-amber-50':'border-red-300 bg-red-50';const titles={ATTENDANCE_CREATED:'✓ ABSENSI BERHASIL',ALREADY_ATTENDED:'! SUDAH ABSEN',MANUAL_STATUS_LOCKED:'! STATUS SUDAH DITETAPKAN'};const el=document.createElement('div');el.className=`w-full rounded-2xl border p-5 shadow-2xl ${styles}`;el.setAttribute('role',event.success?'status':'alert');el.innerHTML=`<div class="flex justify-between gap-3"><div class="min-w-0"><p class="text-sm font-extrabold tracking-wide"></p><p class="mt-2 truncate text-xl font-bold text-emerald-950"></p><p class="mt-1 text-sm text-slate-600"></p><p class="mt-2 font-semibold text-slate-800"></p></div><button type="button" class="h-8 w-8 rounded-full text-xl hover:bg-white/70" aria-label="Tutup">×</button></div>`;const lines=el.querySelectorAll('p');lines[0].textContent=titles[event.code]??(event.success?'✓ ABSENSI BERHASIL':'✕ ABSENSI GAGAL');lines[1].textContent=event.student_name??'';lines[1].classList.toggle('hidden',!event.student_name);lines[2].textContent=event.nis?`NIS/NISN: ${event.nis}`:'';lines[2].classList.toggle('hidden',!event.nis);lines[3].textContent=event.success&&!duplicate?`${event.status_label??'Hadir'} • ${event.scanned_at}`:`${event.message}${event.attendance_time?` • ${event.status_label??'Hadir'} pukul ${event.attendance_time}`:(event.scanned_at?` • ${event.scanned_at}`:'')}`;let closed=false;const close=()=>{if(closed)return;closed=true;el.remove();showingToast=false;showNextToast()};el.querySelector('button').onclick=close;toasts.append(el);setTimeout(close,3200)};
 const enqueueToast=(event)=>{toastQueue.push(event);showNextToast()};
 const apply=(event)=>{const eventId=String(event.id);if(handledEventIds.has(eventId))return;handledEventIds.add(eventId);const id=String(event.student_id??'');if(event.code==='ATTENDANCE_CREATED'&&dirty.has(id)){enqueueToast({...event,code:'MANUAL_STATUS_LOCKED',message:'Kartu terbaca, tetapi perubahan manual belum disimpan; tampilan tidak ditimpa.'});return;}enqueueToast(event);if(event.code!=='ATTENDANCE_CREATED')return;document.querySelectorAll(`[data-attendance-student="${CSS.escape(id)}"]`).forEach(row=>{row.querySelector('.attendance-radio[value="present"]').checked=true;row.querySelector('[data-attendance-source]').textContent=`RFID • ${event.scanned_at}`;row.classList.remove('rfid-live-highlight');void row.offsetWidth;row.classList.add('rfid-live-highlight')})};
 const schedule=()=>{clearTimeout(timer);timer=setTimeout(poll,document.visibilityState==='hidden'?10000:2500)};
 async function poll(){if(busy){schedule();return}busy=true;try{const query=new URLSearchParams({classroom_id:@json((string)$room?->id),attendance_date:@json($date),cursor:String(cursor)});const response=await fetch(`${url}?${query}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();cursor=data.cursor;data.events.forEach(apply);Object.entries(data.counts).forEach(([key,value])=>{const el=document.querySelector(`[data-attendance-count="${key}"]`);if(el)el.textContent=value});status.textContent='● Live tersambung';status.className='text-xs font-semibold text-emerald-700';synced.textContent=`Terakhir sinkron: ${new Date().toLocaleTimeString('id-ID')}`}catch(e){status.textContent='● Live RFID terputus';status.className='text-xs font-semibold text-red-600'}finally{busy=false;schedule()}}
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){clearTimeout(timer);poll()}});poll();
})();
</script></x-app-layout>
