<?php

declare(strict_types=1);
namespace App\Services\Pmbm;

use App\Enums\Pmbm\ApplicantStatus;
use App\Models\Pmbm\{PmbmApplicant,PmbmDecision,PmbmFitting,PmbmInterview,PmbmInterviewAnswer,PmbmInterviewQuestion,PmbmObservation,PmbmSetting};
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class PmbmWorkflowService
{
    public function __construct(private readonly PmbmRegistrationService $registration) {}
    private function setting(PmbmApplicant $applicant): PmbmSetting { return PmbmSetting::where('academic_year_id', $applicant->academic_year_id)->firstOrFail(); }
    public function scheduleFitting(PmbmApplicant $applicant, array $data, User $actor): PmbmFitting { return DB::transaction(function () use ($applicant,$data,$actor) { $this->requireStatus($applicant, ApplicantStatus::Verified); $fitting=PmbmFitting::updateOrCreate(['applicant_id'=>$applicant->id], $data+['officer_id'=>$data['officer_id']??$actor->id,'attendance_status'=>'scheduled']); $this->registration->transition($applicant,ApplicantStatus::FittingScheduled,$actor,'Fitting seragam dijadwalkan.'); $this->log($applicant,$actor,'Fitting seragam dijadwalkan.'); return $fitting; }); }
    public function completeFitting(PmbmApplicant $applicant,array $data,User $actor): void { DB::transaction(function()use($applicant,$data,$actor){$this->requireStatus($applicant,ApplicantStatus::FittingScheduled);$fitting=$applicant->fitting()->firstOrFail();$fitting->update($data+['attendance_status'=>'present','completed_at'=>now(),'completed_by'=>$actor->id]);$this->registration->transition($applicant,ApplicantStatus::FittingCompleted,$actor,'Fitting seragam selesai.');$this->advanceAfterFitting($applicant,$actor);$this->log($applicant,$actor,'Fitting seragam diselesaikan.');}); }
    public function scheduleInterview(PmbmApplicant $applicant,array $data,User $actor):PmbmInterview { return DB::transaction(function()use($applicant,$data,$actor){$this->requireStatus($applicant,ApplicantStatus::Verified,ApplicantStatus::FittingCompleted);$interview=PmbmInterview::updateOrCreate(['applicant_id'=>$applicant->id],$data+['interviewer_id'=>$data['interviewer_id']??$actor->id]);$this->registration->transition($applicant,ApplicantStatus::InterviewScheduled,$actor,'Wawancara orang tua dijadwalkan.');$this->log($applicant,$actor,'Wawancara orang tua dijadwalkan.');return $interview;}); }
    public function completeInterview(PmbmApplicant $applicant,array $data,User $actor):void { DB::transaction(function()use($applicant,$data,$actor){$this->requireStatus($applicant,ApplicantStatus::InterviewScheduled);$interview=$applicant->interview()->firstOrFail();foreach($data['answers']??[] as $questionId=>$answer) PmbmInterviewAnswer::updateOrCreate(['interview_id'=>$interview->id,'question_id'=>$questionId],['answer'=>is_array($answer)?$answer:[$answer]]);$missing=PmbmInterviewQuestion::where('active',true)->where('required',true)->whereNotIn('id',array_keys($data['answers']??[]))->exists();if($missing)throw ValidationException::withMessages(['answers'=>'Semua pertanyaan wajib harus diisi.']);$interview->update(['started_at'=>$interview->started_at??now(),'completed_at'=>now(),'summary'=>$data['summary']??null,'public_note'=>$data['public_note']??null,'internal_note'=>$data['internal_note']??null]);$this->registration->transition($applicant,ApplicantStatus::Interviewed,$actor,'Wawancara orang tua selesai.');$this->advanceAfterInterview($applicant,$actor);$this->log($applicant,$actor,'Wawancara orang tua diselesaikan.');}); }
    public function completeObservation(PmbmApplicant $applicant,array $data,User $actor):void { DB::transaction(function()use($applicant,$data,$actor){$this->requireStatus($applicant,ApplicantStatus::Interviewed);$applicant->observation()->updateOrCreate(['applicant_id'=>$applicant->id],$data+['observer_id'=>$actor->id,'completed_at'=>now()]);$this->registration->transition($applicant,ApplicantStatus::DecisionPending,$actor,'Observasi anak selesai; menunggu keputusan.');$this->log($applicant,$actor,'Observasi anak diselesaikan.');}); }
    public function recommendDecision(PmbmApplicant $applicant,array $data,User $actor):PmbmDecision { return DB::transaction(function()use($applicant,$data,$actor){$this->requireStatus($applicant,ApplicantStatus::DecisionPending);$decision=PmbmDecision::updateOrCreate(['applicant_id'=>$applicant->id],['decision'=>$data['decision'],'public_note'=>$data['public_note']??null,'internal_note'=>$data['internal_note']??null,'decided_by'=>$actor->id,'decided_at'=>now()]);if(!$this->setting($applicant)->require_headmaster_approval)$this->approveDecision($applicant,$actor);$this->log($applicant,$actor,'Rekomendasi keputusan PMBM dibuat.');return $decision;}); }
    public function approveDecision(PmbmApplicant $applicant,User $actor):void { DB::transaction(function()use($applicant,$actor){$this->requireStatus($applicant,ApplicantStatus::DecisionPending);$decision=$applicant->decision()->lockForUpdate()->firstOrFail();$decision->update(['approved_by'=>$actor->id,'approved_at'=>now()]);$status=ApplicantStatus::from($decision->decision);if($status===ApplicantStatus::Waitlisted)$decision->update(['waitlist_order'=>PmbmDecision::where('decision','waitlisted')->whereHas('applicant',fn($q)=>$q->where('academic_year_id',$applicant->academic_year_id))->max('waitlist_order')+1]);$this->registration->transition($applicant,$status,$actor,'Keputusan PMBM disetujui.');if($status===ApplicantStatus::Accepted)$this->registration->transition($applicant,ApplicantStatus::RegistrationPaymentPending,$actor,'Menunggu pembayaran daftar ulang.');$this->log($applicant,$actor,'Keputusan PMBM disetujui.');}); }
    public function promoteWaitlist(PmbmApplicant $applicant,string $reason,User $actor):void { DB::transaction(function()use($applicant,$reason,$actor){$this->requireStatus($applicant,ApplicantStatus::Waitlisted);$applicant->decision()->update(['decision'=>'accepted','promoted_by'=>$actor->id,'promoted_at'=>now(),'promotion_reason'=>$reason]);$this->registration->transition($applicant,ApplicantStatus::Accepted,$actor,'Daftar cadangan dipromosikan: '.$reason);$this->registration->transition($applicant,ApplicantStatus::RegistrationPaymentPending,$actor,'Menunggu pembayaran daftar ulang.');$this->log($applicant,$actor,'Daftar cadangan dipromosikan.');}); }
    private function advanceAfterFitting(PmbmApplicant $a,User $u):void{$s=$this->setting($a);if($s->require_parent_interview)$this->scheduleInterview($a,['scheduled_at'=>now()],$u);else $this->registration->transition($a,ApplicantStatus::DecisionPending,$u,'Tahap wawancara tidak diwajibkan.');}
    private function advanceAfterInterview(PmbmApplicant $a,User $u):void{if(!$this->setting($a)->require_child_observation)$this->registration->transition($a,ApplicantStatus::DecisionPending,$u,'Tahap observasi tidak diwajibkan.');}
    private function requireStatus(PmbmApplicant $a,ApplicantStatus ...$statuses):void{if(!in_array($a->status,$statuses,true))throw ValidationException::withMessages(['status'=>'Aksi tidak tersedia pada tahap PMBM saat ini.']);}
    private function log(PmbmApplicant $a,User $u,string $message):void{activity('pmbm')->causedBy($u)->performedOn($a)->log($message);}
}
