<?php

declare(strict_types=1);

namespace App\Services\OperationalFinance;

use App\Enums\OperationalFinance\OperationalTransactionStatus as Status;
use App\Enums\OperationalFinance\OperationalTransactionType as Type;
use App\Models\Finance\CashAccount;
use App\Models\Finance\StudentPayment;
use App\Models\OperationalFinance\BudgetAllocation;
use App\Models\OperationalFinance\CashClosing;
use App\Models\OperationalFinance\CashReconciliation;
use App\Models\OperationalFinance\CashTransfer;
use App\Models\OperationalFinance\FinanceDocumentSequence;
use App\Models\OperationalFinance\OperationalTransaction;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class OperationalFinanceService
{
    public function number(string $type, ?string $date = null): string
    {
        $date = $date ?: now()->toDateString(); $year=(int)date('Y', strtotime($date)); $month=(int)date('m', strtotime($date));
        return DB::transaction(function () use ($type, $year, $month): string { $seq=FinanceDocumentSequence::query()->lockForUpdate()->firstOrCreate(['document_type'=>$type,'year'=>$year,'month'=>$month], ['last_number'=>0]); $seq->increment('last_number'); return sprintf('%s/%04d/%02d/%06d', $type, $year, $month, $seq->last_number); });
    }
    public function storeTransaction(array $data, string $type, bool $post = false): OperationalTransaction
    {
        return DB::transaction(function () use ($data, $type, $post): OperationalTransaction {
            $cash=CashAccount::query()->lockForUpdate()->findOrFail($data['cash_account_id']);
            if (! $cash->is_active) { throw ValidationException::withMessages(['cash_account_id'=>'Akun kas tidak aktif.']); }
            $trx=OperationalTransaction::create(['transaction_number'=>$this->number($type === Type::Income->value ? 'BKM' : 'BKK', $data['transaction_date']),'transaction_date'=>$data['transaction_date'],'transaction_type'=>$type,'cash_account_id'=>$cash->id,'finance_category_id'=>$data['finance_category_id'] ?? null,'amount'=>$data['amount'],'description'=>$data['description'],'reference_number'=>$data['reference_number'] ?? null,'budget_allocation_id'=>$data['budget_allocation_id'] ?? null,'status'=>Status::Draft->value,'created_by'=>auth()->id(),'updated_by'=>auth()->id(),'notes'=>$data['notes'] ?? null]);
            if ($post) { $this->post($trx); }
            activity('operational-finance')->performedOn($trx)->causedBy(auth()->user())->withProperties(['nomor'=>$trx->transaction_number,'nominal'=>$trx->amount])->log('transaksi dibuat');
            return $trx->refresh();
        });
    }
    public function submit(OperationalTransaction $transaction): OperationalTransaction { return DB::transaction(function () use ($transaction) { $trx=OperationalTransaction::query()->lockForUpdate()->findOrFail($transaction->id); if (! in_array($trx->status, [Status::Draft->value, Status::Rejected->value], true)) throw ValidationException::withMessages(['status'=>'Transaksi tidak dapat diajukan.']); $trx->update(['status'=>Status::Submitted->value,'submitted_by'=>auth()->id(),'submitted_at'=>now()]); activity('operational-finance')->performedOn($trx)->causedBy(auth()->user())->log('transaksi diajukan'); return $trx; }); }
    public function approve(OperationalTransaction $transaction, ?string $notes=null): OperationalTransaction { return DB::transaction(function () use ($transaction,$notes) { $trx=OperationalTransaction::query()->lockForUpdate()->findOrFail($transaction->id); if ($trx->submitted_by === auth()->id()) throw ValidationException::withMessages(['approval'=>'Pengaju tidak dapat menyetujui transaksi sendiri.']); if ($trx->status !== Status::Submitted->value) throw ValidationException::withMessages(['status'=>'Transaksi tidak menunggu persetujuan.']); $trx->update(['status'=>Status::Approved->value,'approved_by'=>auth()->id(),'approved_at'=>now(),'approval_notes'=>$notes]); $this->post($trx); activity('operational-finance')->performedOn($trx)->causedBy(auth()->user())->log('transaksi disetujui dan dibukukan'); return $trx->refresh(); }); }
    public function reject(OperationalTransaction $transaction, string $reason): OperationalTransaction { return DB::transaction(function () use ($transaction,$reason) { $trx=OperationalTransaction::query()->lockForUpdate()->findOrFail($transaction->id); if ($trx->status !== Status::Submitted->value) throw ValidationException::withMessages(['status'=>'Transaksi tidak menunggu persetujuan.']); $trx->update(['status'=>Status::Rejected->value,'rejected_by'=>auth()->id(),'rejected_at'=>now(),'rejection_reason'=>$reason]); activity('operational-finance')->performedOn($trx)->causedBy(auth()->user())->log('transaksi ditolak'); return $trx; }); }
    public function post(OperationalTransaction $trx): void { if ($trx->posted_at) throw ValidationException::withMessages(['status'=>'Transaksi sudah dibukukan.']); $cash=CashAccount::query()->lockForUpdate()->findOrFail($trx->cash_account_id); $delta=in_array($trx->transaction_type,[Type::Income->value,Type::TransferIn->value],true) ? $trx->amount : -$trx->amount; if ($delta < 0 && !($cash->allow_negative_balance ?? false) && ((float)$cash->current_balance + (float)$delta) < 0) throw ValidationException::withMessages(['amount'=>'Saldo kas tidak mencukupi.']); $cash->update(['current_balance'=>DB::raw('current_balance + '.$delta)]); $trx->update(['status'=>Status::Posted->value,'posted_at'=>now()]); if ($trx->budget_allocation_id && $trx->transaction_type === Type::Expense->value) BudgetAllocation::whereKey($trx->budget_allocation_id)->lockForUpdate()->increment('realized_amount', $trx->amount); }
    public function cancel(OperationalTransaction $transaction, string $reason): OperationalTransaction { return DB::transaction(function () use ($transaction,$reason) { $trx=OperationalTransaction::query()->lockForUpdate()->findOrFail($transaction->id); if ($trx->status !== Status::Posted->value) throw ValidationException::withMessages(['status'=>'Hanya transaksi dibukukan yang dapat dibatalkan.']); $cash=CashAccount::query()->lockForUpdate()->findOrFail($trx->cash_account_id); $delta=in_array($trx->transaction_type,[Type::Income->value,Type::TransferIn->value],true) ? -$trx->amount : $trx->amount; $cash->update(['current_balance'=>DB::raw('current_balance + '.$delta)]); if ($trx->budget_allocation_id && $trx->transaction_type === Type::Expense->value) BudgetAllocation::whereKey($trx->budget_allocation_id)->lockForUpdate()->decrement('realized_amount', $trx->amount); $trx->update(['status'=>Status::Cancelled->value,'cancelled_by'=>auth()->id(),'cancelled_at'=>now(),'cancellation_reason'=>$reason]); activity('operational-finance')->performedOn($trx)->causedBy(auth()->user())->log('transaksi dibatalkan'); return $trx; }); }
    public function transfer(array $data): CashTransfer { return DB::transaction(function () use ($data) { if ((int)$data['source_cash_account_id']===(int)$data['destination_cash_account_id']) throw ValidationException::withMessages(['destination_cash_account_id'=>'Akun tujuan harus berbeda.']); $source=CashAccount::query()->lockForUpdate()->findOrFail($data['source_cash_account_id']); $dest=CashAccount::query()->lockForUpdate()->findOrFail($data['destination_cash_account_id']); if (!($source->allow_negative_balance ?? false) && (float)$source->current_balance < (float)$data['amount']) throw ValidationException::withMessages(['amount'=>'Saldo akun asal tidak mencukupi.']); $number=$this->number('TRF',$data['transfer_date']); $transfer=CashTransfer::create(['transfer_number'=>$number,'transfer_date'=>$data['transfer_date'],'source_cash_account_id'=>$source->id,'destination_cash_account_id'=>$dest->id,'amount'=>$data['amount'],'description'=>$data['description'],'reference_number'=>$data['reference_number'] ?? null,'status'=>Status::Posted->value,'submitted_by'=>auth()->id(),'posted_at'=>now()]); $out=OperationalTransaction::create(['transaction_number'=>$number.'-OUT','transaction_date'=>$data['transfer_date'],'transaction_type'=>Type::TransferOut->value,'cash_account_id'=>$source->id,'amount'=>$data['amount'],'description'=>'Transfer keluar: '.$data['description'],'status'=>Status::Posted->value,'created_by'=>auth()->id(),'posted_at'=>now()]); $in=OperationalTransaction::create(['transaction_number'=>$number.'-IN','transaction_date'=>$data['transfer_date'],'transaction_type'=>Type::TransferIn->value,'cash_account_id'=>$dest->id,'amount'=>$data['amount'],'description'=>'Transfer masuk: '.$data['description'],'status'=>Status::Posted->value,'created_by'=>auth()->id(),'posted_at'=>now()]); $source->update(['current_balance'=>DB::raw('current_balance - '.$data['amount'])]); $dest->update(['current_balance'=>DB::raw('current_balance + '.$data['amount'])]); $transfer->update(['out_transaction_id'=>$out->id,'in_transaction_id'=>$in->id]); return $transfer; }); }
    public function summary(): array { $today=today(); return ['totalBalance'=>CashAccount::sum('current_balance'),'todayIncome'=>OperationalTransaction::where('status',Status::Posted->value)->where('transaction_type',Type::Income->value)->whereDate('transaction_date',$today)->sum('amount'),'todayExpense'=>OperationalTransaction::where('status',Status::Posted->value)->where('transaction_type',Type::Expense->value)->whereDate('transaction_date',$today)->sum('amount'),'monthNet'=>OperationalTransaction::where('status',Status::Posted->value)->whereMonth('transaction_date',$today->month)->whereYear('transaction_date',$today->year)->selectRaw("sum(case when transaction_type='income' then amount when transaction_type='expense' then -amount else 0 end) as total")->value('total') ?? 0,'pending'=>OperationalTransaction::where('status',Status::Submitted->value)->count(),'cancelled'=>OperationalTransaction::where('status',Status::Cancelled->value)->count(),'accounts'=>CashAccount::latest()->limit(8)->get(),'latest'=>OperationalTransaction::with('cashAccount','category')->latest()->limit(8)->get(),'differences'=>CashReconciliation::where('difference','!=',0)->count(),'unclosed'=>CashAccount::whereDoesntHave('operationalClosings', fn($q)=>$q->whereDate('closing_date', today()))->count()]; }
}
