<x-layouts.app :title="$title" :breadcrumbs="['Beranda','Data Madrasah','Tahun Ajaran & Semester',$editing?'Edit':'Tambah']"><div class="mx-auto max-w-4xl space-y-6"><x-ui.page-header :title="$title" description="Semester Ganjil dan Semester Genap akan dibuat otomatis."/>
@if($editing && ($academicYear->is_active || $academicYear->semesters->contains('is_active',true)))<x-ui.alert>Periode ini sedang aktif. Perubahan tanggal akan langsung digunakan oleh sistem.</x-ui.alert>@endif
<form method="post" action="{{ $editing ? route('academic-periods.update',$academicYear) : route('academic-periods.store') }}" class="space-y-6" id="academic-period-form">@csrf @if($editing)@method('PUT')@endif
<x-ui.form-section title="Tahun Ajaran" description="Isi nama dan rentang keseluruhan tahun ajaran."><div class="grid gap-4 sm:grid-cols-2"><x-ui.input name="name" label="Nama Tahun Ajaran" placeholder="2026/2027" maxlength="9" :value="$academicYear->name" required/><x-ui.input name="starts_at" label="Tanggal Mulai" type="date" :value="$academicYear->starts_at?->format('Y-m-d')" required/><x-ui.input name="ends_at" label="Tanggal Selesai" type="date" :value="$academicYear->ends_at?->format('Y-m-d')" required/><div class="sm:col-span-2"><x-ui.textarea name="notes" label="Catatan">{{ old('notes',$academicYear->notes) }}</x-ui.textarea></div></div></x-ui.form-section>
<x-ui.form-section title="Semester Ganjil" description="Atur tanggal Semester Ganjil di dalam rentang tahun ajaran."><div class="grid gap-4 sm:grid-cols-2"><x-ui.input name="odd_starts_at" label="Tanggal Mulai Semester Ganjil" type="date" :value="$odd?->starts_at?->format('Y-m-d') ?? null" required/><x-ui.input name="odd_ends_at" label="Tanggal Selesai Semester Ganjil" type="date" :value="$odd?->ends_at?->format('Y-m-d') ?? null" required/></div></x-ui.form-section>
<x-ui.form-section title="Semester Genap" description="Semester Genap harus dimulai setelah Semester Ganjil selesai."><div class="grid gap-4 sm:grid-cols-2"><x-ui.input name="even_starts_at" label="Tanggal Mulai Semester Genap" type="date" :value="$even?->starts_at?->format('Y-m-d') ?? null" required/><x-ui.input name="even_ends_at" label="Tanggal Selesai Semester Genap" type="date" :value="$even?->ends_at?->format('Y-m-d') ?? null" required/></div></x-ui.form-section>
<div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><x-ui.button variant="secondary" href="{{ route('academic-periods.index') }}">Batal</x-ui.button><x-ui.button>{{ $editing ? 'Simpan Perubahan' : 'Simpan Tahun Ajaran' }}</x-ui.button></div></form></div>
@if(!$editing)<script>document.querySelector('[name=name]').addEventListener('change',function(){const m=this.value.match(/^(\d{4})\/(\d{4})$/);if(!m)return;const set=(n,v)=>{const e=document.querySelector(`[name=${n}]`);if(e&&!e.value)e.value=v};set('starts_at',`${m[1]}-07-01`);set('ends_at',`${m[2]}-06-30`);set('odd_starts_at',`${m[1]}-07-01`);set('odd_ends_at',`${m[1]}-12-31`);set('even_starts_at',`${m[2]}-01-01`);set('even_ends_at',`${m[2]}-06-30`);});</script>@endif
</x-layouts.app>
