<x-layouts.app :title="$title" :breadcrumbs="['Beranda','Data Madrasah','Tahun Ajaran & Semester']">
<div class="space-y-6">
<x-ui.page-header title="Tahun Ajaran & Semester" description="Kelola tahun ajaran, semester, dan periode akademik yang sedang digunakan.">
@can('academic-periods.create')<x-ui.button href="{{ route('academic-periods.create') }}"><x-ui.icon name="plus"/>Tambah Tahun Ajaran</x-ui.button>@endcan
</x-ui.page-header>
<x-ui.card class="border-emerald-200 bg-emerald-50/60"><div class="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-wide text-emerald-700">Periode Akademik Aktif</p>
@if($activePeriod && $activePeriod->activeSemester)<h2 class="mt-2 text-2xl font-black text-emerald-950">{{ $activePeriod->name }}</h2><p class="mt-1 font-semibold text-slate-700">{{ $activePeriod->activeSemester->display_name }}</p><p class="mt-1 text-sm text-slate-600">{{ $activePeriod->activeSemester->display_period }}</p><p class="mt-3 text-sm text-slate-600">Periode aktif digunakan sebagai acuan data akademik pada modul e-Madrasah.</p>
@else<h2 class="mt-2 text-xl font-black text-emerald-950">Belum Ada Periode Aktif</h2><p class="mt-2 text-sm text-slate-600">Silakan tambahkan tahun ajaran atau pilih semester yang akan digunakan.</p>@endif</div>
@if($activePeriod && $activePeriod->activeSemester)<span class="badge badge-success">Aktif</span>@elseif(auth()->user()->can('academic-periods.create'))<x-ui.button href="{{ route('academic-periods.create') }}">Tambah Tahun Ajaran</x-ui.button>@endif</div></x-ui.card>
<div class="flex items-center justify-between"><div><h2 class="text-lg font-bold text-emerald-950">Daftar Tahun Ajaran</h2><p class="text-sm text-slate-500">Semester Ganjil dan Genap berada dalam satu tahun ajaran.</p></div></div>
@if($academicYears->isEmpty())<x-ui.empty-state title="Belum ada tahun ajaran." description="Tambahkan tahun ajaran pertama agar e-Madrasah memiliki periode akademik yang digunakan.">@can('academic-periods.create')<x-ui.button href="{{ route('academic-periods.create') }}">Tambah Tahun Ajaran</x-ui.button>@endcan</x-ui.empty-state>@endif
@foreach($academicYears as $year)<x-ui.card><div class="flex flex-col gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h3 class="text-xl font-black text-emerald-950">{{ $year->name }}</h3><span class="badge {{ $year->is_active ? 'badge-success' : '' }}">{{ $year->status_label }}</span></div><p class="mt-1 text-sm text-slate-500">{{ $year->display_period }}</p></div><div class="flex flex-wrap gap-2">@can('academic-periods.update')<x-ui.button variant="outline" href="{{ route('academic-periods.edit',$year) }}">Edit</x-ui.button>@endcan @can('academic-periods.delete')<button type="button" class="btn btn-danger" onclick="openPeriodDialog('delete-{{ $year->id }}')">Hapus</button>@endcan</div></div>
<div class="mt-5 grid gap-4 lg:grid-cols-2">@foreach($year->semesters->sortBy('starts_at') as $semester)<div class="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><h4 class="font-bold text-emerald-950">{{ $semester->display_name }}</h4><p class="mt-1 text-sm text-slate-500">{{ $semester->display_period }}</p></div><span class="badge {{ $semester->is_active ? 'badge-success' : '' }}">{{ $semester->status_label }}</span></div><div class="mt-5">@if($semester->is_active)<span class="font-bold text-emerald-700">Periode Aktif</span>@can('academic-periods.activate')@else<button type="button" class="btn btn-primary w-full sm:w-auto" onclick="openPeriodDialog('activate-{{ $semester->id }}')">Jadikan Periode Aktif</button>@endcan @endif</div></div>
@can('academic-periods.activate')<dialog id="activate-{{ $semester->id }}" class="w-[min(92vw,30rem)] rounded-3xl p-0 shadow-2xl backdrop:bg-slate-950/50"><div class="p-6"><h3 class="text-xl font-black text-emerald-950">Aktifkan periode ini?</h3><dl class="mt-4 space-y-2 text-sm"><div><dt class="text-slate-500">Tahun Ajaran:</dt><dd class="font-bold">{{ $year->name }}</dd></div><div><dt class="text-slate-500">Semester:</dt><dd class="font-bold">{{ $semester->display_name }}</dd></div></dl><p class="mt-4 text-sm text-slate-600">Periode aktif sebelumnya akan dinonaktifkan. Data yang sudah tersimpan tidak akan dihapus.</p><form method="post" action="{{ route('academic-periods.activate',$semester) }}" class="mt-6 flex justify-end gap-2">@csrf @method('PATCH')<button type="button" class="btn btn-secondary" onclick="this.closest('dialog').close()">Batal</button><button class="btn btn-primary">Jadikan Periode Aktif</button></form></div></dialog>@endcan
@endforeach</div>
@can('academic-periods.delete')<dialog id="delete-{{ $year->id }}" class="w-[min(92vw,30rem)] rounded-3xl p-0 shadow-2xl backdrop:bg-slate-950/50"><div class="p-6"><h3 class="text-xl font-black text-emerald-950">Hapus tahun ajaran ini?</h3><p class="mt-3 text-sm text-slate-600">Tahun Ajaran {{ $year->name }} dan dua semesternya akan dihapus. Tindakan ini hanya dapat dilakukan jika periode belum digunakan.</p><form method="post" action="{{ route('academic-periods.destroy',$year) }}" class="mt-6 flex justify-end gap-2">@csrf @method('DELETE')<button type="button" class="btn btn-secondary" onclick="this.closest('dialog').close()">Batal</button><button class="btn btn-danger">Hapus Tahun Ajaran</button></form></div></dialog>@endcan
</x-ui.card>@endforeach
</div><script>window.openPeriodDialog=(id)=>document.getElementById(id)?.showModal();</script>
</x-layouts.app>
