<x-app-layout title="Input Absensi Siswa">
<form method="post" action="{{ route('student-attendances.store') }}" enctype="multipart/form-data" x-data="{submitting:false, markAll(){document.querySelectorAll('[data-status]').forEach(el=>el.value='hadir')}}" @submit="submitting=true">
@csrf
<input type="hidden" name="attendance_date" value="{{ $session->attendance_date->toDateString() }}"><input type="hidden" name="classroom_id" value="{{ $session->classroom_id }}">
<div class="space-y-6"><div class="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p class="text-sm text-slate-500">Absensi Siswa / {{ $session->classroom->name }}</p><h1 class="text-2xl font-semibold text-emerald-950">Input Absensi Siswa</h1><p class="text-sm text-slate-600">{{ $session->attendance_date->format('d/m/Y') }} · {{ $session->academicYear?->name }} · {{ $session->semester?->name ?? 'Semester aktif' }} · Wali kelas {{ $session->classroom->homeroomTeacher?->fullName() ?? '-' }}</p></div><div class="flex flex-wrap gap-2"><button type="button" @click="markAll()" class="rounded-xl border px-4 py-2">Tandai Semua Hadir</button><a href="{{ route('student-attendances.index') }}" class="rounded-xl border px-4 py-2">Kembali</a></div></div>
<div class="grid gap-3 md:grid-cols-5">@foreach($summary as $key=>$total)<div class="card"><div class="card-body"><p class="text-xs text-slate-500">{{ $statuses[$key] ?? $key }}</p><p class="text-xl font-bold text-emerald-950">{{ $total }}</p></div></div>@endforeach</div>
<div class="card"><div class="card-body overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">No</th><th>Siswa</th><th>Status</th><th>Jam</th><th>Keterangan</th><th>Bukti</th></tr></thead><tbody>@forelse($enrollments as $enrollment)@php($attendance=$session->attendances->firstWhere('student_enrollment_id',$enrollment->id))<tr class="border-t"><td class="p-3">{{ $loop->iteration }}</td><td><div class="font-semibold">{{ $enrollment->student->name }}</div><div class="text-xs text-slate-500">NIS {{ $enrollment->student->nis ?? '-' }}</div></td><td><select data-status name="students[{{ $enrollment->id }}][status]" class="rounded-xl border-slate-300">@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected(old("students.{$enrollment->id}.status", $attendance?->status?->value)===$value)>{{ $label }}</option>@endforeach</select>@error("students.{$enrollment->id}.status")<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</td><td><input type="time" name="students[{{ $enrollment->id }}][arrival_time]" value="{{ old("students.{$enrollment->id}.arrival_time", $attendance?->arrival_time) }}" class="w-28 rounded-xl border-slate-300"><input type="number" min="0" name="students[{{ $enrollment->id }}][late_minutes]" value="{{ old("students.{$enrollment->id}.late_minutes", $attendance?->late_minutes ?? 0) }}" class="mt-1 w-28 rounded-xl border-slate-300" placeholder="Menit telat"></td><td><textarea name="students[{{ $enrollment->id }}][notes]" class="rounded-xl border-slate-300" rows="2">{{ old("students.{$enrollment->id}.notes", $attendance?->notes) }}</textarea></td><td><input type="file" name="students[{{ $enrollment->id }}][attachment]" class="text-xs">@if($attendance?->attachment_path)<a class="block text-xs text-emerald-700" href="{{ route('student-attendances.attachments.show',$attendance) }}">Unduh bukti</a>@endif</td></tr>@empty<tr><td colspan="6"><div class="empty-state">Tidak ada siswa aktif pada kelas dan tanggal ini.</div></td></tr>@endforelse</tbody></table></div></div>
<div class="flex flex-wrap justify-end gap-2"><button name="action" value="draft" :disabled="submitting" class="rounded-xl border px-4 py-2 font-semibold">Simpan Draft</button><button name="action" value="finalize" onclick="return confirm('Finalisasi absensi? Data final hanya dapat diubah melalui koreksi.')" :disabled="submitting" class="rounded-xl bg-emerald-900 px-4 py-2 font-semibold text-white">Finalisasi Absensi</button></div></div>
</form>
</x-app-layout>
