<x-layouts.public title="Penerimaan Murid Baru Madrasah">
<main class="bg-[#f8faf8] py-10 sm:py-16"><div class="wrap space-y-6">
<a class="font-semibold text-emerald-800" href="{{ route('public.home') }}">← Website MI Muslimat NU Demak</a>
<section class="rounded-[2rem] bg-emerald-950 p-7 text-white sm:p-12"><p class="font-bold uppercase tracking-widest text-amber-300">{{ $settings?->academicYear?->name ?? 'Tahun ajaran belum ditetapkan' }}</p><h1 class="serif mt-3 text-4xl font-bold sm:text-5xl">Penerimaan Murid Baru Madrasah</h1><p class="mt-4 max-w-2xl text-lg text-emerald-100">MI Muslimat NU Demak menerima pendaftaran calon murid secara tertib, aman, dan transparan.</p><p class="mt-5 inline-block rounded-full bg-white/15 px-4 py-2 font-bold">{{ $statusLabel }}</p><div class="mt-7 flex flex-wrap gap-3">@if($state === 'open')<a class="rounded-xl bg-amber-400 px-6 py-3 font-bold text-emerald-950" href="{{ route('pmbm.public.create') }}">Daftar Online</a>@else<span class="rounded-xl bg-slate-200 px-6 py-3 font-bold text-slate-700">{{ $statusLabel }}</span>@endif<a class="rounded-xl border border-white/50 px-6 py-3 font-bold" href="{{ route('pmbm.status.form') }}">Cek Status Pendaftaran</a></div></section>
<div class="grid gap-6 lg:grid-cols-2"><section class="card p-7"><h2 class="text-2xl font-bold text-emerald-950">Informasi Pendaftaran</h2><dl class="mt-5 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Periode</dt><dd class="font-semibold">{{ $settings?->registration_open_at?->translatedFormat('j F Y') ?? 'Menunggu pengumuman' }} — {{ $settings?->registration_close_at?->translatedFormat('j F Y') ?? 'Menunggu pengumuman' }}</dd></div><div><dt class="text-sm text-slate-500">Kuota</dt><dd class="font-semibold">{{ $settings?->quota_total ? $settings->quota_total.' murid' : 'Sesuai daya tampung' }}</dd></div><div><dt class="text-sm text-slate-500">Kontak Panitia</dt><dd class="font-semibold">{{ $settings?->panitia_phone ?? 'Hubungi madrasah' }}</dd></div><div><dt class="text-sm text-slate-500">Lokasi</dt><dd class="font-semibold">{{ $settings?->location ?? 'MI Muslimat NU Demak' }}</dd></div></dl></section><section class="card p-7"><h2 class="text-2xl font-bold text-emerald-950">Alur Pendaftaran</h2><ol class="mt-5 space-y-3 text-slate-700"><li>1. Isi formulir online dan unggah dokumen.</li><li>2. Panitia memverifikasi kelengkapan berkas.</li><li>3. Ikuti jadwal fitting, wawancara, dan assessment bila ditetapkan.</li><li>4. Pantau keputusan dan daftar ulang melalui status pendaftaran.</li></ol></section></div>
<section class="card p-7"><h2 class="text-2xl font-bold text-emerald-950">Persyaratan</h2><p class="mt-3 text-slate-600">Siapkan dokumen sesuai daftar pada formulir. Dokumen wajib ditandai saat pendaftaran dan disimpan secara privat.</p></section>
@if($fees->isNotEmpty())<section class="card overflow-x-auto p-7"><h2 class="text-2xl font-bold text-emerald-950">Rincian Biaya</h2><table class="mt-5 min-w-full text-left"><thead><tr class="border-b"><th class="p-3">Administrasi</th><th class="p-3">Putra</th><th class="p-3">Putri</th></tr></thead><tbody>@foreach($fees as $fee)<tr class="border-b"><td class="p-3">{{ $fee['name'] }}</td><td class="p-3">{{ $fee['male'] === null ? '—' : 'Rp'.number_format($fee['male'],0,',','.') }}</td><td class="p-3">{{ $fee['female'] === null ? '—' : 'Rp'.number_format($fee['female'],0,',','.') }}</td></tr>@endforeach</tbody></table><p class="mt-4 text-sm text-slate-500">Nominal dapat berubah sesuai kebijakan madrasah.</p></section>@endif
@if($schedules->isNotEmpty())<section class="card p-7"><h2 class="text-2xl font-bold text-emerald-950">Jadwal Kegiatan</h2><div class="mt-5 grid gap-4 md:grid-cols-2">@foreach($schedules as $schedule)<div class="rounded-xl bg-emerald-50 p-4"><strong>{{ $schedule['title'] }}</strong><p class="mt-1 text-sm text-slate-600">{{ $schedule['description'] }}</p></div>@endforeach</div></section>@endif
</div></main></x-layouts.public>
