<x-app-layout title="Mata Pelajaran">
<div class="space-y-6">
  <x-ui.page-header title="Mata Pelajaran" description="Kelola master mata pelajaran formal madrasah, status aktif, dan alokasi jam mingguan.">
    <x-slot:primary>@can('subjects.create')<x-ui.button :href="route('subjects.create')">Tambah Mata Pelajaran</x-ui.button>@endcan</x-slot:primary>
    <x-slot:secondary>@can('subjects.export')<x-ui.button variant="outline" :href="route('subjects.export', request()->query())">Export</x-ui.button>@endcan</x-slot:secondary>
  </x-ui.page-header>
  <x-ui.card><form class="grid gap-3 md:grid-cols-5" method="get"><input name="search" value="{{ request('search') }}" placeholder="Cari kode/nama"><select name="category"><option value="">Semua Kelompok</option>@foreach($categories as $c)<option value="{{ $c->value }}" @selected(request('category')===$c->value)>{{ $c->label() }}</option>@endforeach</select><select name="grade_level_id"><option value="">Semua Tingkat</option>@foreach($gradeLevels as $g)<option value="{{ $g->id }}" @selected(request('grade_level_id')==$g->id)>{{ $g->name }}</option>@endforeach</select><select name="status"><option value="">Semua Status</option><option value="1" @selected(request('status')==='1')>Aktif</option><option value="0" @selected(request('status')==='0')>Nonaktif</option></select><div class="flex gap-2"><x-ui.button>Terapkan</x-ui.button><x-ui.button variant="secondary" :href="route('subjects.index')">Reset</x-ui.button></div></form></x-ui.card>
  <x-ui.card><p class="mb-3 text-sm font-semibold text-slate-600">Jumlah hasil: {{ $subjects->total() }}</p><x-ui.table :headers="['Kode','Nama','Singkat','Kelompok','Tingkat','Jam/Minggu','Status','Tindakan']">@forelse($subjects as $s)<tr><td class="font-semibold">{{ $s->code }}</td><td>{{ $s->name }}</td><td>{{ $s->short_name ?: '-' }}</td><td>{{ $s->category?->label() }}</td><td>{{ $s->gradeLevels->pluck('name')->join(', ') ?: '-' }}</td><td class="text-right">{{ $s->default_weekly_hours ?: '-' }}</td><td><x-ui.badge :variant="$s->is_active ? 'success' : 'muted'">{{ $s->is_active?'Aktif':'Nonaktif' }}</x-ui.badge></td><td><div class="table-actions"><x-ui.button variant="secondary" :href="route('subjects.show',$s)">Detail</x-ui.button>@can('subjects.update')<x-ui.button variant="outline" :href="route('subjects.edit',$s)">Edit</x-ui.button>@endcan @can('subjects.activate')<form method="post" action="{{ route('subjects.toggle',$s) }}">@csrf @method('patch')<x-ui.button variant="{{ $s->is_active ? 'danger' : 'outline' }}">{{ $s->is_active?'Nonaktifkan':'Aktifkan' }}</x-ui.button></form>@endcan</div></td></tr>@empty<tr><td colspan="8"><x-ui.empty-state title="Belum ada Mata Pelajaran" description="Tambahkan mata pelajaran untuk mulai menyusun jadwal dan penugasan." /></td></tr>@endforelse</x-ui.table><div class="mt-4">{{ $subjects->links() }}</div></x-ui.card>
</div>
</x-app-layout>
