<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('guardian_profiles', function (Blueprint $t): void { $t->id(); $t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('phone_number', 30)->nullable(); $t->string('relationship', 30)->nullable(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); });
        Schema::create('student_guardians', function (Blueprint $t): void { $t->id(); $t->foreignId('guardian_id')->constrained('guardian_profiles')->cascadeOnDelete(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->string('relationship', 30); $t->boolean('is_primary')->default(false); $t->boolean('can_view_academic')->default(true); $t->boolean('can_view_finance')->default(true); $t->boolean('can_request_leave')->default(true); $t->timestamps(); $t->unique(['guardian_id','student_id']); });
        Schema::create('lesson_schedules', function (Blueprint $t): void { $t->id(); $t->foreignId('academic_year_id')->constrained()->restrictOnDelete(); $t->foreignId('semester_id')->constrained()->restrictOnDelete(); $t->foreignId('classroom_id')->constrained()->restrictOnDelete(); $t->foreignId('academic_subject_id')->constrained()->restrictOnDelete(); $t->foreignId('personnel_id')->nullable()->constrained('personnel')->nullOnDelete(); $t->unsignedTinyInteger('day_of_week'); $t->time('start_time'); $t->time('end_time'); $t->string('room')->nullable(); $t->boolean('active')->default(true); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->index(['semester_id','classroom_id','day_of_week','active'], 'lesson_schedule_lookup'); });
        Schema::create('student_leave_requests', function (Blueprint $t): void { $t->id(); $t->foreignId('student_id')->constrained()->restrictOnDelete(); $t->foreignId('guardian_id')->constrained('guardian_profiles')->restrictOnDelete(); $t->string('leave_type', 20); $t->date('start_date'); $t->date('end_date'); $t->text('reason'); $t->string('attachment_path')->nullable(); $t->string('status', 20)->default('pending')->index(); $t->timestamp('submitted_at'); $t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('reviewed_at')->nullable(); $t->text('reviewer_note')->nullable(); $t->timestamps(); });
        Schema::create('student_leave_request_transitions', function (Blueprint $t): void { $t->id(); $t->foreignId('student_leave_request_id')->constrained(indexName: 'leave_request_transition_request_fk')->cascadeOnDelete(); $t->string('from_status',20); $t->string('to_status',20); $t->foreignId('actor_id')->constrained('users')->restrictOnDelete(); $t->text('note')->nullable(); $t->timestamp('transitioned_at'); });
        Schema::create('fee_types', function (Blueprint $t): void { $t->id(); $t->string('code',30)->unique(); $t->string('name'); $t->boolean('active')->default(true); $t->timestamps(); });
        Schema::create('student_invoices', function (Blueprint $t): void { $t->id(); $t->foreignId('student_id')->constrained()->restrictOnDelete(); $t->foreignId('academic_year_id')->constrained()->restrictOnDelete(); $t->foreignId('semester_id')->nullable()->constrained()->nullOnDelete(); $t->string('invoice_number')->unique(); $t->date('billing_month')->nullable(); $t->date('issue_date'); $t->date('due_date'); foreach(['subtotal','discount','penalty','total','paid_amount','outstanding_amount'] as $c) $t->decimal($c,15,2)->default(0); $t->string('status',20)->default('draft')->index(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('cancelled_at')->nullable(); $t->timestamps(); $t->unique(['student_id','academic_year_id','billing_month'], 'student_monthly_invoice_unique'); });
        Schema::create('student_invoice_items', function (Blueprint $t): void { $t->id(); $t->foreignId('invoice_id')->constrained('student_invoices')->cascadeOnDelete(); $t->foreignId('fee_type_id')->constrained()->restrictOnDelete(); $t->string('description'); $t->unsignedInteger('qty'); $t->decimal('unit_amount',15,2); $t->decimal('amount',15,2); $t->timestamps(); });
        Schema::create('student_payments', function (Blueprint $t): void { $t->id(); $t->foreignId('student_id')->constrained()->restrictOnDelete(); $t->foreignId('invoice_id')->nullable()->constrained('student_invoices')->restrictOnDelete(); $t->string('payment_number')->unique(); $t->string('payment_method',30); $t->string('bank_provider',30)->nullable(); $t->string('bank_reference')->nullable()->unique(); $t->decimal('amount',15,2); $t->timestamp('paid_at'); $t->string('status',20)->index(); $t->string('source',30); $t->json('metadata')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
        Schema::create('student_virtual_accounts', function (Blueprint $t): void { $t->id(); $t->foreignId('student_id')->constrained()->restrictOnDelete(); $t->foreignId('invoice_id')->nullable()->constrained('student_invoices')->cascadeOnDelete(); $t->string('provider',30); $t->string('mode',20); $t->string('virtual_account_number'); $t->string('customer_number'); $t->string('external_id')->unique(); $t->string('status',20); $t->timestamp('expires_at')->nullable(); $t->timestamp('last_synced_at')->nullable(); $t->text('metadata')->nullable(); $t->timestamps(); $t->unique(['provider','virtual_account_number']); });
        Schema::create('bank_transactions', function (Blueprint $t): void { $t->id(); $t->string('provider',30); $t->string('external_id'); $t->string('provider_reference')->nullable(); $t->string('transaction_type',30); $t->decimal('amount',15,2); $t->string('status',30); $t->timestamp('occurred_at')->nullable(); $t->string('request_reference')->nullable(); $t->text('raw_payload')->nullable(); $t->timestamp('reconciled_at')->nullable(); $t->timestamps(); $t->unique(['provider','external_id']); $t->unique(['provider','provider_reference']); });
        Schema::create('personnel_bank_accounts', function (Blueprint $t): void { $t->id(); $t->foreignId('personnel_id')->constrained('personnel')->cascadeOnDelete(); $t->string('bank_code',20); $t->string('bank_name'); $t->text('account_number'); $t->string('account_holder_name'); $t->boolean('is_primary')->default(false); $t->timestamp('verified_at')->nullable(); $t->timestamps(); });
        Schema::create('payroll_payment_batches', function (Blueprint $t): void { $t->id(); $t->string('batch_number')->unique(); $t->string('payroll_period'); $t->unsignedInteger('total_records'); $t->decimal('total_amount',15,2); $t->string('status',30)->index(); $t->foreignId('created_by')->constrained('users')->restrictOnDelete(); $t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('approved_at')->nullable(); $t->foreignId('executed_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('executed_at')->nullable(); $t->string('external_id')->unique(); $t->timestamps(); });
        Schema::create('payroll_disbursements', function (Blueprint $t): void { $t->id(); $t->foreignId('payroll_payment_batch_id')->constrained()->cascadeOnDelete(); $t->foreignId('personnel_payroll_id')->constrained()->restrictOnDelete(); $t->foreignId('personnel_id')->constrained('personnel')->restrictOnDelete(); $t->text('bank_account_snapshot'); $t->decimal('amount',15,2); $t->string('provider',30); $t->string('external_id')->unique(); $t->string('provider_reference')->nullable()->unique(); $t->string('status',30)->index(); $t->string('failure_code')->nullable(); $t->text('failure_message')->nullable(); $t->timestamp('submitted_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->unique('personnel_payroll_id'); });
    }
    public function down(): void { foreach (['payroll_disbursements','payroll_payment_batches','personnel_bank_accounts','bank_transactions','student_virtual_accounts','student_payments','student_invoice_items','student_invoices','fee_types','student_leave_request_transitions','student_leave_requests','lesson_schedules','student_guardians','guardian_profiles'] as $table) Schema::dropIfExists($table); }
};
