<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('finance_categories', function (Blueprint $table): void {
            $table->id(); $table->foreignId('parent_id')->nullable()->constrained('finance_categories')->nullOnDelete(); $table->string('code')->unique(); $table->string('name'); $table->string('transaction_type')->index(); $table->text('description')->nullable(); $table->boolean('is_budgetable')->default(true); $table->boolean('requires_approval')->default(false); $table->decimal('approval_threshold', 15, 2)->nullable(); $table->boolean('is_active')->default(true)->index(); $table->unsignedInteger('sort_order')->default(0); $table->text('notes')->nullable(); $table->timestamps();
        });
        Schema::create('operational_transactions', function (Blueprint $table): void {
            $table->id(); $table->string('transaction_number')->unique(); $table->date('transaction_date')->index(); $table->string('transaction_type')->index(); $table->foreignId('cash_account_id')->constrained('cash_accounts')->restrictOnDelete(); $table->foreignId('finance_category_id')->nullable()->constrained('finance_categories')->nullOnDelete(); $table->decimal('amount', 15, 2); $table->text('description'); $table->string('reference_number')->nullable(); $table->string('source_type')->nullable(); $table->unsignedBigInteger('source_id')->nullable(); $table->unsignedBigInteger('budget_allocation_id')->nullable()->index(); $table->string('status')->index(); $table->foreignId('submitted_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('submitted_at')->nullable(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('approved_at')->nullable(); $table->text('approval_notes')->nullable(); $table->foreignId('rejected_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('rejected_at')->nullable(); $table->text('rejection_reason')->nullable(); $table->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('cancelled_at')->nullable(); $table->text('cancellation_reason')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('posted_at')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); $table->unique(['source_type','source_id'], 'operational_source_unique');
        });
        Schema::create('cash_transfers', function (Blueprint $table): void {
            $table->id(); $table->string('transfer_number')->unique(); $table->date('transfer_date')->index(); $table->foreignId('source_cash_account_id')->constrained('cash_accounts')->restrictOnDelete(); $table->foreignId('destination_cash_account_id')->constrained('cash_accounts')->restrictOnDelete(); $table->decimal('amount', 15, 2); $table->text('description'); $table->string('reference_number')->nullable(); $table->string('status')->index(); $table->foreignId('submitted_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('posted_at')->nullable(); $table->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete(); $table->text('cancellation_reason')->nullable(); $table->foreignId('out_transaction_id')->nullable()->constrained('operational_transactions')->nullOnDelete(); $table->foreignId('in_transaction_id')->nullable()->constrained('operational_transactions')->nullOnDelete(); $table->timestamps();
        });
        Schema::create('transaction_approvals', function (Blueprint $table): void {$table->id(); $table->foreignId('operational_transaction_id')->constrained()->cascadeOnDelete(); $table->foreignId('actor_id')->constrained('users')->cascadeOnDelete(); $table->string('action'); $table->text('notes')->nullable(); $table->timestamps();});
        Schema::create('transaction_attachments', function (Blueprint $table): void {$table->id(); $table->foreignId('operational_transaction_id')->constrained()->cascadeOnDelete(); $table->string('disk')->default('local'); $table->string('path'); $table->string('original_name'); $table->string('mime_type'); $table->unsignedBigInteger('size'); $table->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps();});
        Schema::create('budget_periods', function (Blueprint $table): void {$table->id(); $table->string('name'); $table->foreignId('academic_year_id')->nullable()->constrained()->nullOnDelete(); $table->unsignedSmallInteger('fiscal_year')->index(); $table->date('start_date'); $table->date('end_date'); $table->string('status')->index(); $table->decimal('total_budget', 15, 2)->default(0); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('approved_at')->nullable(); $table->timestamp('locked_at')->nullable(); $table->text('notes')->nullable(); $table->timestamps();});
        Schema::create('budget_allocations', function (Blueprint $table): void {$table->id(); $table->foreignId('budget_period_id')->constrained()->cascadeOnDelete(); $table->foreignId('finance_category_id')->constrained()->restrictOnDelete(); $table->decimal('allocated_amount', 15, 2); $table->decimal('revised_amount', 15, 2)->default(0); $table->text('revision_reason')->nullable(); $table->decimal('realized_amount', 15, 2)->default(0); $table->text('notes')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->unique(['budget_period_id','finance_category_id']);});
        Schema::create('cash_closings', function (Blueprint $table): void {$table->id(); $table->foreignId('cash_account_id')->constrained('cash_accounts')->restrictOnDelete(); $table->date('closing_date'); $table->decimal('opening_balance',15,2); $table->decimal('total_income',15,2)->default(0); $table->decimal('total_expense',15,2)->default(0); $table->decimal('total_transfer_in',15,2)->default(0); $table->decimal('total_transfer_out',15,2)->default(0); $table->decimal('expected_balance',15,2); $table->decimal('actual_balance',15,2); $table->decimal('difference',15,2); $table->text('notes')->nullable(); $table->string('status')->index(); $table->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('closed_at')->nullable(); $table->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('verified_at')->nullable(); $table->timestamps(); $table->unique(['cash_account_id','closing_date']);});
        Schema::create('cash_reconciliations', function (Blueprint $table): void {$table->id(); $table->foreignId('cash_account_id')->constrained('cash_accounts')->restrictOnDelete(); $table->date('reconciliation_date'); $table->decimal('system_balance',15,2); $table->decimal('actual_balance',15,2); $table->decimal('difference',15,2); $table->text('notes'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps();});
        Schema::create('finance_document_sequences', function (Blueprint $table): void {$table->id(); $table->string('document_type'); $table->unsignedSmallInteger('year'); $table->unsignedTinyInteger('month')->default(0); $table->unsignedBigInteger('last_number')->default(0); $table->timestamps(); $table->unique(['document_type','year','month'], 'op_fin_seq_unique');});
    }
    public function down(): void { foreach (['finance_document_sequences','cash_reconciliations','cash_closings','budget_allocations','budget_periods','transaction_attachments','transaction_approvals','cash_transfers','operational_transactions','finance_categories'] as $table) { Schema::dropIfExists($table); } }
};
