<?php declare(strict_types=1);
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('employee_attendances',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->date('attendance_date');$t->dateTime('checked_in_at')->nullable();$t->dateTime('checked_out_at')->nullable();$t->string('status')->index();$t->string('work_schedule_type')->default('regular');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->unsignedInteger('accuracy')->nullable();$t->string('location_text')->nullable();$t->string('selfie_path')->nullable();$t->text('notes')->nullable();$t->boolean('is_verified')->default(false);$t->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('verified_at')->nullable();$t->text('correction_reason')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['employee_id','attendance_date']);$t->index(['attendance_date','status']);});
Schema::create('employee_leave_requests',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->date('starts_at');$t->date('ends_at');$t->string('type')->index();$t->text('reason');$t->string('attachment_path')->nullable();$t->string('status')->default('pending')->index();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('approved_at')->nullable();$t->text('rejection_reason')->nullable();$t->timestamps();$t->index(['employee_id','starts_at','ends_at']);});
Schema::create('student_attendances',function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('classroom_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->date('attendance_date');$t->string('status')->index();$t->text('notes')->nullable();$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['student_id','attendance_date']);$t->index(['classroom_id','attendance_date','status']);});
Schema::create('teaching_journals',function(Blueprint $t){$t->id();$t->foreignId('teaching_assignment_id')->constrained()->cascadeOnDelete();$t->foreignId('lesson_schedule_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->foreignId('subject_id')->constrained()->restrictOnDelete();$t->foreignId('classroom_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('semester_id')->constrained()->cascadeOnDelete();$t->date('journal_date');$t->time('starts_at');$t->time('ends_at');$t->unsignedTinyInteger('lesson_hours');$t->text('material');$t->text('learning_objectives')->nullable();$t->string('method')->nullable();$t->string('media')->nullable();$t->text('assignment')->nullable();$t->text('assessment')->nullable();$t->text('teacher_notes')->nullable();$t->string('status')->default('draft')->index();$t->timestamp('submitted_at')->nullable();$t->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('verified_at')->nullable();$t->text('rejection_reason')->nullable();$t->timestamps();$t->index(['employee_id','journal_date','status']);});
Schema::create('teaching_journal_student',function(Blueprint $t){$t->id();$t->foreignId('teaching_journal_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->string('status');$t->text('notes')->nullable();$t->timestamps();$t->unique(['teaching_journal_id','student_id']);});}
public function down():void{Schema::dropIfExists('teaching_journal_student');Schema::dropIfExists('teaching_journals');Schema::dropIfExists('student_attendances');Schema::dropIfExists('employee_leave_requests');Schema::dropIfExists('employee_attendances');}};
