<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('payroll_components', function (Blueprint $table): void { $table->id(); $table->string('name'); $table->string('code')->unique(); $table->string('component_type'); $table->string('calculation_type'); $table->bigInteger('default_amount')->default(0); $table->decimal('percentage', 8, 4)->nullable(); $table->string('formula_key')->nullable(); $table->boolean('is_tax_related')->default(false); $table->boolean('is_attendance_related')->default(false); $table->boolean('is_fixed')->default(true); $table->boolean('is_prorated')->default(false); $table->boolean('is_active')->default(true); $table->boolean('show_on_payslip')->default(true); $table->unsignedInteger('sort_order')->default(0); $table->text('notes')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->softDeletes(); $table->timestamps(); });
        Schema::create('employee_salary_profiles', function (Blueprint $table): void { $table->id(); $table->foreignId('employee_id')->constrained()->cascadeOnDelete(); $table->date('effective_start_date'); $table->date('effective_end_date')->nullable(); $table->string('payroll_frequency')->default('monthly'); $table->bigInteger('base_salary')->default(0); $table->foreignId('default_cash_account_id')->nullable()->constrained('cash_accounts')->nullOnDelete(); $table->string('payment_method')->default('cash'); $table->text('bank_name')->nullable(); $table->text('bank_account_number')->nullable(); $table->text('bank_account_holder')->nullable(); $table->boolean('is_active')->default(true); $table->text('notes')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('approved_at')->nullable(); $table->timestamps(); $table->index(['employee_id','effective_start_date','effective_end_date'], 'salary_profiles_effective_idx'); });
        Schema::create('employee_salary_profile_components', function (Blueprint $table): void { $table->id(); $table->foreignId('employee_salary_profile_id')->constrained()->cascadeOnDelete(); $table->foreignId('payroll_component_id')->constrained()->restrictOnDelete(); $table->bigInteger('amount')->default(0); $table->decimal('percentage', 8, 4)->nullable(); $table->string('calculation_basis')->nullable(); $table->boolean('is_active')->default(true); $table->date('effective_start_date'); $table->date('effective_end_date')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); $table->unique(['employee_salary_profile_id','payroll_component_id','effective_start_date'], 'salary_component_version_unique'); });
        Schema::create('payroll_periods_v2', function (Blueprint $table): void { $table->id(); $table->string('name'); $table->string('period_code')->unique(); $table->date('period_start_date'); $table->date('period_end_date'); $table->date('attendance_cutoff_start'); $table->date('attendance_cutoff_end'); $table->date('payment_due_date')->nullable(); $table->string('status')->default('draft'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('submitted_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('finalized_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('locked_at')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('payroll_runs', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_period_id')->constrained('payroll_periods_v2')->cascadeOnDelete(); $table->string('run_number')->unique(); $table->timestamp('generated_at')->nullable(); $table->foreignId('generated_by')->nullable()->constrained('users')->nullOnDelete(); $table->unsignedInteger('employee_count')->default(0); $table->bigInteger('total_gross')->default(0); $table->bigInteger('total_deductions')->default(0); $table->bigInteger('total_net')->default(0); $table->string('status')->default('calculated'); $table->foreignId('submitted_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('submitted_at')->nullable(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('approved_at')->nullable(); $table->foreignId('rejected_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('rejected_at')->nullable(); $table->text('rejection_reason')->nullable(); $table->foreignId('finalized_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('finalized_at')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); $table->unique(['payroll_period_id','status'], 'one_active_payroll_run_per_period'); });
        Schema::create('payroll_items', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_run_id')->constrained()->cascadeOnDelete(); $table->foreignId('employee_id')->constrained()->restrictOnDelete(); $table->foreignId('employee_salary_profile_id')->constrained()->restrictOnDelete(); $table->string('employee_name_snapshot'); $table->string('employee_number_snapshot')->nullable(); $table->string('employment_type_snapshot')->nullable(); $table->string('position_snapshot')->nullable(); $table->bigInteger('base_salary')->default(0); $table->bigInteger('gross_salary')->default(0); $table->bigInteger('total_deductions')->default(0); $table->bigInteger('net_salary')->default(0); $table->json('attendance_snapshot')->nullable(); $table->string('status')->default('calculated'); $table->string('payment_status')->default('unpaid'); $table->string('payslip_number')->nullable()->unique(); $table->text('notes')->nullable(); $table->timestamps(); $table->unique(['payroll_run_id','employee_id']); });
        Schema::create('payroll_item_components', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_item_id')->constrained()->cascadeOnDelete(); $table->foreignId('payroll_component_id')->nullable()->constrained()->nullOnDelete(); $table->string('component_name_snapshot'); $table->string('component_code_snapshot')->nullable(); $table->string('component_type'); $table->string('calculation_type_snapshot'); $table->string('calculation_basis_snapshot')->nullable(); $table->bigInteger('amount')->default(0); $table->decimal('quantity', 10, 2)->nullable(); $table->bigInteger('rate')->nullable(); $table->string('source_type')->nullable(); $table->unsignedBigInteger('source_id')->nullable(); $table->boolean('is_manual_adjustment')->default(false); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('payroll_adjustments', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_item_id')->constrained()->cascadeOnDelete(); $table->foreignId('payroll_component_id')->nullable()->constrained()->nullOnDelete(); $table->string('adjustment_type'); $table->bigInteger('amount'); $table->text('reason'); $table->string('attachment_path')->nullable(); $table->string('status')->default('approved'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('approved_at')->nullable(); $table->timestamps(); });
        Schema::create('payroll_approvals', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_run_id')->constrained()->cascadeOnDelete(); $table->foreignId('actor_id')->constrained('users')->cascadeOnDelete(); $table->string('action'); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('payroll_payments', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_run_id')->constrained()->cascadeOnDelete(); $table->foreignId('payroll_item_id')->nullable()->constrained()->cascadeOnDelete(); $table->string('payment_number')->unique(); $table->date('payment_date'); $table->foreignId('cash_account_id')->constrained('cash_accounts')->restrictOnDelete(); $table->string('payment_method')->default('cash'); $table->bigInteger('amount'); $table->string('reference_number')->nullable(); $table->string('payment_status')->default('paid'); $table->foreignId('paid_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('cancelled_at')->nullable(); $table->text('cancellation_reason')->nullable(); $table->foreignId('operational_transaction_id')->nullable()->constrained('operational_transactions')->nullOnDelete(); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('payslip_sequences', function (Blueprint $table): void { $table->id(); $table->unsignedInteger('year'); $table->unsignedInteger('month'); $table->unsignedInteger('last_number')->default(0); $table->timestamps(); $table->unique(['year','month']); });
        Schema::create('payroll_attendance_snapshots', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_item_id')->constrained()->cascadeOnDelete(); $table->json('snapshot'); $table->timestamps(); });
        Schema::create('payroll_attendance_rules', function (Blueprint $table): void { $table->id(); $table->foreignId('payroll_component_id')->constrained()->cascadeOnDelete(); $table->string('attendance_event_type'); $table->string('calculation_method'); $table->bigInteger('amount_per_unit')->default(0); $table->decimal('percentage_per_unit', 8, 4)->nullable(); $table->unsignedInteger('tolerance')->default(0); $table->bigInteger('maximum_deduction')->nullable(); $table->date('effective_start_date'); $table->date('effective_end_date')->nullable(); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::table('operational_transactions', function (Blueprint $table): void { if (! Schema::hasColumn('operational_transactions','source_type')) { $table->string('source_type')->nullable()->after('notes'); $table->unsignedBigInteger('source_id')->nullable()->after('source_type'); $table->unique(['source_type','source_id']); } });
    }
    public function down(): void
    {
        Schema::table('operational_transactions', function (Blueprint $table): void { if (Schema::hasColumn('operational_transactions','source_type')) { $table->dropUnique(['source_type','source_id']); $table->dropColumn(['source_type','source_id']); } });
        foreach (['payroll_attendance_rules','payroll_attendance_snapshots','payslip_sequences','payroll_payments','payroll_approvals','payroll_adjustments','payroll_item_components','payroll_items','payroll_runs','payroll_periods_v2','employee_salary_profile_components','employee_salary_profiles','payroll_components'] as $table) { Schema::dropIfExists($table); }
    }
};
