<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
 Schema::create('landing_page_settings',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->text('value')->nullable();$t->string('type')->default('text');$t->string('group')->index();$t->timestamps();});
 Schema::create('landing_statistics',function(Blueprint $t){$t->id();$t->string('label');$t->string('source')->default('manual');$t->unsignedInteger('manual_value')->nullable();$t->string('suffix',20)->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('landing_highlights',function(Blueprint $t){$t->id();$t->string('icon',50)->nullable();$t->string('title');$t->text('description')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('landing_programs',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->string('icon',50)->nullable();$t->string('image')->nullable();$t->text('summary')->nullable();$t->longText('description')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->boolean('featured')->default(false);$t->timestamps();});
 Schema::create('landing_facilities',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('image')->nullable();$t->text('description')->nullable();$t->string('icon',50)->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('landing_achievements',function(Blueprint $t){$t->id();$t->string('title');$t->string('category')->nullable();$t->string('level')->nullable();$t->string('rank')->nullable();$t->unsignedSmallInteger('year')->nullable();$t->string('participant')->nullable();$t->text('description')->nullable();$t->string('image')->nullable();$t->string('badge',50)->nullable();$t->date('date')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->boolean('featured')->default(false);$t->timestamps();});
 Schema::create('landing_news',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->string('category')->index();$t->text('excerpt')->nullable();$t->longText('content');$t->string('featured_image')->nullable();$t->timestamp('published_at')->nullable()->index();$t->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete();$t->string('status')->default('draft')->index();$t->boolean('featured')->default(false);$t->unsignedBigInteger('views')->default(0);$t->timestamps();});
 Schema::create('landing_testimonials',function(Blueprint $t){$t->id();$t->string('name');$t->string('relation')->nullable();$t->string('photo')->nullable();$t->text('content');$t->unsignedTinyInteger('rating')->default(5);$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
 } public function down():void {foreach(['landing_testimonials','landing_news','landing_achievements','landing_facilities','landing_programs','landing_highlights','landing_statistics','landing_page_settings'] as $x)Schema::dropIfExists($x);} };
