<?php
declare(strict_types=1);
namespace App\Services\Classrooms;
use App\Models\{Classroom,Personnel,Student,User};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class ClassroomService {
 public function create(User $actor,array $data):Classroom{return DB::transaction(function()use($actor,$data){$this->validateHomeroom($data['homeroom_personnel_id']??null,(int)$data['academic_year_id']);$data['created_by']=$data['updated_by']=$actor->id;$c=Classroom::create($data);activity('kelas-rombel')->causedBy($actor)->performedOn($c)->log("Menambahkan rombel {$c->display_name}.");return $c;});}
 public function update(User $actor,Classroom $c,array $data):Classroom{return DB::transaction(function()use($actor,$c,$data){if(array_key_exists('homeroom_personnel_id',$data))$this->validateHomeroom($data['homeroom_personnel_id'],(int)($data['academic_year_id']??$c->academic_year_id),$c->id);$c->update([...$data,'updated_by'=>$actor->id]);activity('kelas-rombel')->causedBy($actor)->performedOn($c)->log("Memperbarui rombel {$c->display_name}.");return $c;});}
 public function setActive(User $actor,Classroom $c,bool $active):void{if(!$active&&$c->activeMemberships()->exists())throw ValidationException::withMessages(['classroom'=>'Rombel belum dapat dinonaktifkan karena masih memiliki siswa aktif.']);$c->update(['is_active'=>$active,'updated_by'=>$actor->id]);activity('kelas-rombel')->causedBy($actor)->performedOn($c)->log(($active?'Mengaktifkan':'Menonaktifkan')." rombel {$c->display_name}.");}
 public function assignHomeroom(User $actor,Classroom $c,?int $id):void{$this->validateHomeroom($id,$c->academic_year_id,$c->id);$old=$c->homeroom_name;$c->update(['homeroom_personnel_id'=>$id,'updated_by'=>$actor->id]);$c->refresh();activity('kelas-rombel')->causedBy($actor)->performedOn($c)->withProperties(['wali_kelas_lama'=>$old])->log("Menetapkan {$c->homeroom_name} sebagai wali kelas {$c->display_name}.");}
 public function validateHomeroom(?int $id,int $year,?int $except=null):void{if(!$id)return;$p=Personnel::find($id);if(!$p||!$p->is_active)throw ValidationException::withMessages(['homeroom_personnel_id'=>'Personalia yang dipilih sedang nonaktif.']);if(!str($p->position)->lower()->contains(['guru','kepala madrasah']))throw ValidationException::withMessages(['homeroom_personnel_id'=>'Wali kelas harus merupakan Guru atau Kepala Madrasah.']);$exists=Classroom::where('academic_year_id',$year)->where('homeroom_personnel_id',$id)->where('is_active',true)->when($except,fn($q)=>$q->whereKeyNot($except))->exists();if($exists)throw ValidationException::withMessages(['homeroom_personnel_id'=>'Guru tersebut sudah menjadi wali kelas pada rombel lain di tahun ajaran yang sama.']);}
 public function statistics(?int $year):array{if(!$year)return ['total'=>0,'placed'=>0,'unplaced'=>Student::where('status','active')->count(),'without_homeroom'=>0,'over_capacity'=>0];$rooms=Classroom::where('academic_year_id',$year)->withCount('activeMemberships')->get();$placed=\App\Models\ClassroomMembership::where('academic_year_id',$year)->where('status','active')->distinct('student_id')->count('student_id');return ['total'=>$rooms->count(),'placed'=>$placed,'unplaced'=>max(0,Student::where('status','active')->count()-$placed),'without_homeroom'=>$rooms->whereNull('homeroom_personnel_id')->count(),'over_capacity'=>$rooms->filter->is_over_capacity->count()];}
}
