<?php
declare(strict_types=1);
namespace App\Services\Classrooms;
use App\Models\{Classroom,ClassroomMembership,ClassroomPromotionBatch,ClassroomPromotionRow,User}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class ClassroomPromotionService {
 public function copy(User $actor,int $source,int $target,array $ids,bool $homeroom=false):array{if($source===$target)throw ValidationException::withMessages(['target_academic_year_id'=>'Tahun ajaran tujuan harus berbeda.']);$made=0;$skipped=0;DB::transaction(function()use($actor,$source,$target,$ids,$homeroom,&$made,&$skipped){foreach(Classroom::where('academic_year_id',$source)->whereKey($ids)->get() as $c){$exists=Classroom::where('academic_year_id',$target)->where('grade_level_id',$c->grade_level_id)->where('code',$c->code)->exists();if($exists){$skipped++;continue;}Classroom::create(['academic_year_id'=>$target,'grade_level_id'=>$c->grade_level_id,'code'=>$c->code,'name'=>$c->name,'capacity'=>$c->capacity,'room_name'=>$c->room_name,'homeroom_personnel_id'=>$homeroom?$c->homeroom_personnel_id:null,'notes'=>$c->notes,'is_active'=>true,'created_by'=>$actor->id,'updated_by'=>$actor->id]);$made++;}activity('kelas-rombel')->causedBy($actor)->withProperties(compact('made','skipped'))->log("Menyalin {$made} struktur rombel ke tahun ajaran tujuan.");});return compact('made','skipped');}
 public function preview(User $actor,int $source,int $target,array $plans=[]):ClassroomPromotionBatch{if($source===$target)throw ValidationException::withMessages(['target_academic_year_id'=>'Tahun ajaran tujuan harus berbeda.']);return DB::transaction(function()use($actor,$source,$target,$plans){$members=ClassroomMembership::with(['student','classroom.gradeLevel'])->where('academic_year_id',$source)->where('status','active')->get();$b=ClassroomPromotionBatch::create(['source_academic_year_id'=>$source,'target_academic_year_id'=>$target,'created_by'=>$actor->id,'status'=>'previewed','total_rows'=>$members->count()]);foreach($members as $m){$plan=$plans[$m->student_id]??[];$action=$plan['action']??($m->classroom->gradeLevel->number===6?'graduate':($m->student->status==='active'?'promote':'skip'));$targetId=$plan['target_classroom_id']??null;$warning=in_array($action,['promote','repeat'])&&!$targetId;ClassroomPromotionRow::create(['batch_id'=>$b->id,'student_id'=>$m->student_id,'source_classroom_id'=>$m->classroom_id,'target_classroom_id'=>$targetId,'action'=>$action,'status'=>$warning?'warning':'ready','messages'=>$warning?['Rombel tujuan belum dipilih.']:null]);}$b->update(['ready_rows'=>$b->rows()->where('status','ready')->count(),'excluded_rows'=>$b->rows()->where('status','warning')->count()]);return $b;});}
 public function process(User $actor,ClassroomPromotionBatch $batch):void{if($batch->status!=='previewed'||$batch->rows()->where('status','warning')->exists())throw ValidationException::withMessages(['batch'=>'Pratinjau belum siap diproses atau sudah pernah diproses.']);$batch->update(['status'=>'processing','started_at'=>now()]);$batch->rows()->with('student')->chunkById(100,function($rows)use($actor,$batch){DB::transaction(function()use($rows,$actor,$batch){foreach($rows as $row){if($row->status==='processed')continue;$source=ClassroomMembership::where('student_id',$row->student_id)->where('academic_year_id',$batch->source_academic_year_id)->where('status','active')->lockForUpdate()->first();if($row->action==='skip'){$row->update(['status'=>'processed']);continue;}if(!$source){$row->update(['status'=>'failed','messages'=>['Penempatan asal tidak ditemukan.']]);continue;}$source->update(['status'=>'completed','left_at'=>today(),'updated_by'=>$actor->id]);if(in_array($row->action,['promote','repeat']))ClassroomMembership::firstOrCreate(['student_id'=>$row->student_id,'academic_year_id'=>$batch->target_academic_year_id,'status'=>'active'],['classroom_id'=>$row->target_classroom_id,'joined_at'=>today(),'created_by'=>$actor->id,'updated_by'=>$actor->id]);if($row->action==='graduate'&&$row->student->status!=='graduated')$row->student->update(['status'=>'graduated','updated_by'=>$actor->id]);$row->update(['status'=>'processed']);}});});$batch->refresh()->update(['status'=>'completed','processed_rows'=>$batch->rows()->where('status','processed')->count(),'failed_rows'=>$batch->rows()->where('status','failed')->count(),'completed_at'=>now()]);activity('kelas-rombel')->causedBy($actor)->performedOn($batch)->log('Memproses kenaikan kelas tahun ajaran.');}
}
