<?php
declare(strict_types=1);
namespace App\Services\Classrooms;
use App\Models\{Classroom,ClassroomMembership,Student,User}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class ClassroomMembershipService {
 public function addMany(User $actor,Classroom $room,array $ids):array{if(!$room->is_active)throw ValidationException::withMessages(['classroom'=>'Rombel sedang nonaktif.']);return DB::transaction(function()use($actor,$room,$ids){$students=Student::whereKey(array_unique($ids))->lockForUpdate()->get();$errors=[];$added=0;foreach($students as $s){if($s->status!=='active'){$errors[]="{$s->full_name} tidak berstatus aktif.";continue;}if(ClassroomMembership::where('student_id',$s->id)->where('academic_year_id',$room->academic_year_id)->where('status','active')->lockForUpdate()->exists()){$errors[]="{$s->full_name} sudah ditempatkan pada rombel lain di tahun ajaran yang sama.";continue;}ClassroomMembership::create(['student_id'=>$s->id,'classroom_id'=>$room->id,'academic_year_id'=>$room->academic_year_id,'status'=>'active','joined_at'=>today(),'created_by'=>$actor->id,'updated_by'=>$actor->id]);$added++;}activity('kelas-rombel')->causedBy($actor)->performedOn($room)->withProperties(['jumlah'=>$added])->log("Memasukkan {$added} siswa ke {$room->display_name}.");return compact('added','errors');});}
 public function move(User $actor,ClassroomMembership $m,Classroom $target,string $date,?string $notes):ClassroomMembership{if($m->status!=='active'||$target->academic_year_id!==$m->academic_year_id||$target->id===$m->classroom_id||!$target->is_active)throw ValidationException::withMessages(['target_classroom_id'=>'Rombel tujuan tidak valid.']);return DB::transaction(function()use($actor,$m,$target,$date,$notes){$m=ClassroomMembership::lockForUpdate()->findOrFail($m->id);$source=$m->classroom;$m->update(['status'=>'moved','left_at'=>$date,'notes'=>$notes,'updated_by'=>$actor->id]);$new=ClassroomMembership::create(['student_id'=>$m->student_id,'classroom_id'=>$target->id,'academic_year_id'=>$m->academic_year_id,'status'=>'active','joined_at'=>$date,'notes'=>$notes,'created_by'=>$actor->id,'updated_by'=>$actor->id]);activity('kelas-rombel')->causedBy($actor)->performedOn($target)->log("Memindahkan {$m->student->full_name} dari {$source->code} ke {$target->code}.");return $new;});}
 public function remove(User $actor,ClassroomMembership $m,?string $notes):void{DB::transaction(function()use($actor,$m,$notes){$m=ClassroomMembership::lockForUpdate()->findOrFail($m->id);if($m->status!=='active')throw ValidationException::withMessages(['membership'=>'Siswa tidak lagi aktif pada rombel ini.']);$m->update(['status'=>'removed','left_at'=>today(),'notes'=>$notes,'updated_by'=>$actor->id]);activity('kelas-rombel')->causedBy($actor)->performedOn($m->classroom)->log("Mengeluarkan {$m->student->full_name} dari {$m->classroom->display_name}.");});}
}
