<x-app-layout :title="($model->exists ? 'Edit ' : 'Tambah ').$title">
<form method="post" action="{{ $model->exists ? route($key.'.update', $model) : route($key.'.store') }}" enctype="multipart/form-data" class="max-w-4xl space-y-5 rounded-xl border bg-white p-6">
@csrf @if($model->exists) @method('PUT') @endif
<div class="grid gap-4 md:grid-cols-2">
@if($key==='grade-levels')
<label>Nama<input name="name" value="{{ old('name',$model->name) }}" class="w-full rounded-lg border-slate-300"></label><label>Kode<input name="code" value="{{ old('code',$model->code) }}" class="w-full rounded-lg border-slate-300"></label><label>Level<input type="number" min="1" max="6" name="level" value="{{ old('level',$model->level) }}" class="w-full rounded-lg border-slate-300"></label><label class="md:col-span-2">Deskripsi<textarea name="description" class="w-full rounded-lg border-slate-300">{{ old('description',$model->description) }}</textarea></label>
@elseif($key==='subjects')
<label>Kode<input name="code" value="{{ old('code',$model->code) }}" class="w-full rounded-lg border-slate-300"></label><label>Nama<input name="name" value="{{ old('name',$model->name) }}" class="w-full rounded-lg border-slate-300"></label><label>Kategori<select name="category" class="w-full rounded-lg border-slate-300">@foreach($categories as $category)<option value="{{ $category->value }}" @selected(old('category',$model->category?->value)===$category->value)>{{ $category->label() }}</option>@endforeach</select></label><label>KKM<input type="number" min="0" max="100" name="minimum_passing_grade" value="{{ old('minimum_passing_grade',$model->minimum_passing_grade) }}" class="w-full rounded-lg border-slate-300"></label><label class="md:col-span-2">Deskripsi<textarea name="description" class="w-full rounded-lg border-slate-300">{{ old('description',$model->description) }}</textarea></label>
@elseif($key==='employees')
<label>Akun Login<select name="user_id" class="w-full rounded-lg border-slate-300"><option value="">Tanpa akun</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('user_id',$model->user_id)==$user->id)>{{ $user->name }} - {{ $user->email }}</option>@endforeach @if($model->user)<option value="{{ $model->user_id }}" selected>{{ $model->user->name }} - {{ $model->user->email }}</option>@endif</select></label><label>Nama<input name="name" value="{{ old('name',$model->name) }}" class="w-full rounded-lg border-slate-300"></label><label>Nomor Pegawai<input name="employee_number" value="{{ old('employee_number',$model->employee_number) }}" class="w-full rounded-lg border-slate-300"></label><label>NIK<input name="national_identity_number" value="{{ old('national_identity_number',$model->national_identity_number) }}" class="w-full rounded-lg border-slate-300"></label><label>Gender<select name="gender" class="w-full rounded-lg border-slate-300">@foreach($genders as $g)<option value="{{ $g->value }}" @selected(old('gender',$model->gender?->value)===$g->value)>{{ $g->label() }}</option>@endforeach</select></label><label>Jenis Pegawai<select name="employment_type" class="w-full rounded-lg border-slate-300">@foreach($employmentTypes as $t)<option value="{{ $t->value }}" @selected(old('employment_type',$model->employment_type?->value)===$t->value)>{{ $t->label() }}</option>@endforeach</select></label><label>Status<select name="employee_status" class="w-full rounded-lg border-slate-300">@foreach($employeeStatuses as $s)<option value="{{ $s->value }}" @selected(old('employee_status',$model->employee_status?->value)===$s->value)>{{ $s->label() }}</option>@endforeach</select></label><label>Foto<input type="file" name="photo" class="w-full rounded-lg border-slate-300"></label><label>Email<input name="email" value="{{ old('email',$model->email) }}" class="w-full rounded-lg border-slate-300"></label><label>Telepon<input name="phone" value="{{ old('phone',$model->phone) }}" class="w-full rounded-lg border-slate-300"></label><label class="md:col-span-2">Alamat<textarea name="address" class="w-full rounded-lg border-slate-300">{{ old('address',$model->address) }}</textarea></label>
@else
<label>Tahun Ajaran<select name="academic_year_id" class="w-full rounded-lg border-slate-300">@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected(old('academic_year_id',$model->academic_year_id)==$year->id)>{{ $year->name }}</option>@endforeach</select></label>
@if($key==='classrooms')<label>Tingkat<select name="grade_level_id" class="w-full rounded-lg border-slate-300">@foreach($gradeLevels as $g)<option value="{{ $g->id }}" @selected(old('grade_level_id',$model->grade_level_id)==$g->id)>{{ $g->name }}</option>@endforeach</select></label><label>Nama<input name="name" value="{{ old('name',$model->name) }}" class="w-full rounded-lg border-slate-300"></label><label>Kode<input name="code" value="{{ old('code',$model->code) }}" class="w-full rounded-lg border-slate-300"></label><label>Kapasitas<input type="number" name="capacity" value="{{ old('capacity',$model->capacity) }}" class="w-full rounded-lg border-slate-300"></label><label>Wali Kelas<select name="homeroom_teacher_id" class="w-full rounded-lg border-slate-300"><option value="">-</option>@foreach($employees as $e)<option value="{{ $e->id }}" @selected(old('homeroom_teacher_id',$model->homeroom_teacher_id)==$e->id)>{{ $e->name }}</option>@endforeach</select></label><label>Ruang<input name="room" value="{{ old('room',$model->room) }}" class="w-full rounded-lg border-slate-300"></label>
@else
<label>Semester<select name="semester_id" class="w-full rounded-lg border-slate-300">@foreach($semesters as $s)<option value="{{ $s->id }}" @selected(old('semester_id',$model->semester_id)==$s->id)>{{ $s->name }}</option>@endforeach</select></label><label>Guru<select name="employee_id" class="w-full rounded-lg border-slate-300">@foreach($employees as $e)<option value="{{ $e->id }}" @selected(old('employee_id',$model->employee_id)==$e->id)>{{ $e->name }}</option>@endforeach</select></label><label>Kelas<select name="classroom_id" class="w-full rounded-lg border-slate-300">@foreach($classrooms as $c)<option value="{{ $c->id }}" @selected(old('classroom_id',$model->classroom_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></label><label>Mata Pelajaran<select name="subject_id" class="w-full rounded-lg border-slate-300">@foreach($subjects as $s)<option value="{{ $s->id }}" @selected(old('subject_id',$model->subject_id)==$s->id)>{{ $s->name }}</option>@endforeach</select></label>@if($key==='teaching-assignments')<label>Jam/Minggu<input type="number" name="weekly_hours" value="{{ old('weekly_hours',$model->weekly_hours) }}" class="w-full rounded-lg border-slate-300"></label>@else<label>Hari<select name="day_of_week" class="w-full rounded-lg border-slate-300">@foreach($days as $d)<option value="{{ $d->value }}" @selected(old('day_of_week',$model->day_of_week?->value)===$d->value)>{{ $d->label() }}</option>@endforeach</select></label><label>Mulai<input type="time" name="starts_at" value="{{ old('starts_at',$model->starts_at) }}" class="w-full rounded-lg border-slate-300"></label><label>Selesai<input type="time" name="ends_at" value="{{ old('ends_at',$model->ends_at) }}" class="w-full rounded-lg border-slate-300"></label><label>Ruang<input name="room" value="{{ old('room',$model->room) }}" class="w-full rounded-lg border-slate-300"></label>@endif
@endif @endif
@endif
<label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$model->is_active ?? true))> Aktif</label>
</div>
@if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="flex gap-3"><button class="rounded-lg bg-emerald-950 px-4 py-2 font-semibold text-white">Simpan</button><a href="{{ route($key.'.index') }}" class="rounded-lg border px-4 py-2">Batal</a></div>
</form>
</x-app-layout>
