<x-app-layout :title="$title">
@php
$columns = [
 'grade-levels'=>['Level','Kode','Nama','Status'], 'classrooms'=>['Nama','Kode','Tingkat','Tahun Ajaran','Wali Kelas','Ruang','Kapasitas','Jumlah Siswa','Status'],
 'subjects'=>['Kode','Nama','Kategori','KKM','Status'], 'employees'=>['Pegawai','Nomor','Gender','Jenis','Status Kepegawaian','Kontak','Status'],
 'teaching-assignments'=>['Guru','Mata Pelajaran','Kelas','Tahun Ajaran','Semester','Status'], 'schedules'=>['Hari','Jam','Kelas','Mata Pelajaran','Guru','Ruang'],
][$key];
@endphp
<div class="space-y-6">
  <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-2xl font-black text-emerald-950">{{ $title }}</h2><p class="text-sm text-slate-500">Kelola data {{ strtolower($title) }} madrasah dengan filter, status, dan aksi terkontrol.</p></div>@can($key.'.create')<a href="{{ route($key.'.create') }}" class="btn btn-primary">Tambah {{ $title }}</a>@endcan</div>
  <form class="card card-body grid gap-3 md:grid-cols-4" method="get"><input name="q" value="{{ request('q') }}" placeholder="Cari {{ strtolower($title) }}"><select name="status"><option value="">Semua status</option><option value="active" @selected(request('status')==='active')>Aktif</option><option value="inactive" @selected(request('status')==='inactive')>Nonaktif</option></select><select name="academic_year_id"><option value="">Semua tahun ajaran</option>@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected(request('academic_year_id')==$year->id)>{{ $year->name }}</option>@endforeach</select><button class="btn btn-primary">Terapkan Filter</button></form>
  @if($items->isEmpty())<div class="empty-state">Belum ada data {{ strtolower($title) }}. Gunakan tombol tambah untuk mulai mengisi.</div>@else
  <div class="table-wrap"><table class="data-table"><thead><tr>@foreach($columns as $c)<th>{{ $c }}</th>@endforeach<th>Aksi</th></tr></thead><tbody>
  @foreach($items as $item)<tr>
    @if($key==='grade-levels')<td>{{ $item->level }}</td><td>{{ $item->code }}</td><td class="font-semibold">{{ $item->name }}</td><td><span @class(['badge',$item->is_active?'badge-success':'badge-muted'])>{{ $item->is_active?'Aktif':'Nonaktif' }}</span></td>
    @elseif($key==='classrooms')<td class="font-semibold">{{ $item->name }}</td><td>{{ $item->code }}</td><td>{{ $item->gradeLevel?->name }}</td><td>{{ $item->academicYear?->name }}</td><td>{{ $item->homeroomTeacher?->name ?? '-' }}</td><td>{{ $item->room ?? '-' }}</td><td>{{ $item->capacity }}</td><td>{{ $item->studentEnrollments()->where('enrollment_status','active')->count() }}</td><td><span @class(['badge',$item->is_active?'badge-success':'badge-muted'])>{{ $item->is_active?'Aktif':'Nonaktif' }}</span></td>
    @elseif($key==='subjects')<td>{{ $item->code }}</td><td class="font-semibold">{{ $item->name }}</td><td>{{ $item->category?->label() ?? $item->category }}</td><td>{{ $item->minimum_passing_grade }}</td><td><span @class(['badge',$item->is_active?'badge-success':'badge-muted'])>{{ $item->is_active?'Aktif':'Nonaktif' }}</span></td>
    @elseif($key==='employees')<td><div class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-full bg-emerald-100 font-bold text-emerald-800">{{ str($item->name)->substr(0,2)->upper() }}</div><b>{{ $item->name }}</b></div></td><td>{{ $item->employee_number }}</td><td>{{ $item->gender?->label() }}</td><td>{{ $item->employment_type?->label() }}</td><td>{{ $item->employee_status?->label() }}</td><td>{{ $item->phone ?? $item->email ?? '-' }}</td><td><span @class(['badge',$item->is_active?'badge-success':'badge-muted'])>{{ $item->is_active?'Aktif':'Nonaktif' }}</span></td>
    @elseif($key==='teaching-assignments')<td>{{ $item->employee?->name }}</td><td>{{ $item->subject?->name }}</td><td>{{ $item->classroom?->name }}</td><td>{{ $item->academicYear?->name }}</td><td>{{ $item->semester?->name }}</td><td><span @class(['badge',$item->is_active?'badge-success':'badge-muted'])>{{ $item->is_active?'Aktif':'Nonaktif' }}</span></td>
    @else<td>{{ $item->day_of_week?->label() }}</td><td>{{ $item->starts_at }}–{{ $item->ends_at }}</td><td>{{ $item->classroom?->name }}</td><td>{{ $item->subject?->name }}</td><td>{{ $item->employee?->name }}</td><td>{{ $item->room ?? '-' }}</td>@endif
    <td><div class="flex gap-2">@can($key.'.update')<a class="btn btn-secondary px-3 py-1.5" href="{{ route($key.'.edit', $item) }}">Edit</a>@endcan @can($key.'.delete')<form method="post" action="{{ route($key.'.destroy', $item) }}" onsubmit="return confirm('Nonaktifkan atau hapus data ini?')">@csrf @method('DELETE')<button class="btn btn-danger px-3 py-1.5">Hapus</button></form>@endcan</div></td>
  </tr>@endforeach</tbody></table></div><div>{{ $items->links() }}</div>@endif
</div>
</x-app-layout>
