<?php

declare(strict_types=1);
namespace App\Services\TeachingAssignments;
use App\Models\{Classroom,TeachingAssignmentSet};use Illuminate\Support\Collection;
class TeachingAssignmentReadinessService
{
 public function classrooms(TeachingAssignmentSet $set):Collection{$conflicts=app(TeachingAssignmentConflictService::class)->conflicts($set)->keyBy(fn($g)=>$g->first()->classroom_id.'_'.$g->first()->subject_id);return Classroom::with(['gradeLevel.subjectGradeLoads.subject','homeroomPersonnel'])->where('academic_year_id',$set->academic_year_id)->where('is_active',true)->get()->map(function($room)use($set,$conflicts){$loads=$room->gradeLevel->subjectGradeLoads->where('program_type',$room->program_type);$assignments=$set->assignments()->where('classroom_id',$room->id)->get()->groupBy('subject_id');$exceptions=$set->exceptions()->where('classroom_id',$room->id)->pluck('subject_id');$missing=$loads->filter(function($load)use($assignments,$exceptions){$assigned=(int)($assignments->get($load->subject_id)?->sum('weekly_periods')??0);return $assigned<(int)$load->weekly_hours&&!$exceptions->contains($load->subject_id);});$target=(int)$loads->sum('weekly_hours');$assigned=(int)$assignments->flatten()->sum('weekly_periods');$conflictCount=$conflicts->filter(fn($group)=>$group->first()->classroom_id===$room->id)->count();$excess=max(0,$assigned-$target);$status=$conflictCount?'Konflik':($excess?'JP Berlebih':($missing->isNotEmpty()?'Belum Lengkap':'Lengkap'));return ['classroom'=>$room,'target'=>$target,'assigned'=>$assigned,'remaining'=>max(0,$target-$assigned),'excess'=>$excess,'conflicts'=>$conflictCount,'missing'=>$missing->values(),'status'=>$status];});}
 public function inspect(TeachingAssignmentSet $set):array{$rooms=$this->classrooms($set);$batch=$set->teachingImportBatch;$personnelUnmatched=$batch?->rows()->where('sheet_name','LEGGER')->whereNull('matched_personnel_id')->where('status','unmatched')->count()??0;$classroomUnmatched=$batch?->rows()->where('sheet_name','LEGGER')->whereNull('matched_classroom_id')->where('status','unmatched')->count()??0;$subjectUnmatched=$batch?->rows()->where('sheet_name','LEGGER')->whereNull('matched_subject_id')->where('status','unmatched')->count()??0;$conflicts=(int)$rooms->sum('conflicts');$excess=$rooms->where('excess','>',0)->count();$incomplete=$rooms->where('status','!=','Lengkap')->count();$issues=[];if($personnelUnmatched)$issues[]=['type'=>'personnel','message'=>"{$personnelUnmatched} personalia belum cocok."];if($classroomUnmatched)$issues[]=['type'=>'classrooms','message'=>"{$classroomUnmatched} rombel belum cocok."];if($subjectUnmatched)$issues[]=['type'=>'subjects','message'=>"{$subjectUnmatched} mata pelajaran bermasalah."];if($conflicts)$issues[]=['type'=>'conflicts','message'=>"{$conflicts} konflik pengampu belum selesai."];if($excess)$issues[]=['type'=>'excess','message'=>"{$excess} kelas mempunyai JP berlebih."];if($rooms->where('missing')->filter(fn($r)=>$r['missing']->isNotEmpty())->count())$issues[]=['type'=>'missing','message'=>'Masih ada mata pelajaran wajib tanpa pengampu atau alasan pengecualian.'];$subjectsAvailable=\App\Models\Subject::where('is_active',true)->exists();$loadsAvailable=\App\Models\SubjectGradeLoad::exists();return compact('rooms','issues','personnelUnmatched','classroomUnmatched','subjectUnmatched','conflicts','excess','incomplete')+['subjectsAvailable'=>$subjectsAvailable,'loadsAvailable'=>$loadsAvailable,'ready'=>$issues===[]&&$subjectsAvailable&&$loadsAvailable&&$set->status==='draft'];}
}
