<?php

declare(strict_types=1);
namespace App\Services\TeachingAssignments;
use App\Models\{TeachingAssignmentSet,TeachingImportBatch,User};
use Illuminate\Support\Facades\DB;
class TeachingAssignmentSetService
{
 public function fromImport(TeachingImportBatch $batch,User $actor):TeachingAssignmentSet{return DB::transaction(function()use($batch,$actor){abort_unless($batch->status==='previewed',422);$set=TeachingAssignmentSet::create(['academic_year_id'=>$batch->academic_year_id,'teaching_import_batch_id'=>$batch->id,'name'=>'Draft '.$batch->original_filename,'status'=>'draft','source'=>'xlsx_import','source_filename'=>$batch->original_filename,'created_by'=>$actor->id]);$assignments=app(TeachingAssignmentService::class);$duties=app(TeachingAssignmentDutyService::class);foreach($batch->rows()->where('sheet_name','LEGGER')->get() as $row){if($row->matched_personnel_id&&$row->matched_subject_id&&$row->matched_classroom_id){$personnelIds=$row->normalized_data['personnel_ids']??[$row->matched_personnel_id];$subjectIds=$row->normalized_data['subject_ids']??[$row->matched_subject_id];$classroomIds=$row->normalized_data['classroom_ids']??[$row->matched_classroom_id];foreach($personnelIds as $personnelId)foreach($subjectIds as $subjectId)foreach($classroomIds as $classroomId){try{$existing=$set->assignments()->where(['personnel_id'=>$personnelId,'subject_id'=>$subjectId,'classroom_id'=>$classroomId])->first();$assignments->save($actor,$set,['personnel_id'=>$personnelId,'subject_id'=>$subjectId,'classroom_id'=>$classroomId,'teacher_role'=>'primary','notes'=>'Hasil import '.$batch->original_filename],$existing);}catch(\Illuminate\Validation\ValidationException){}}}$text=mb_strtolower(collect($row->raw_data)->implode(' '));$type=match(true){str_contains($text,'kepala madrasah')=>'headmaster',str_contains($text,'wali kelas')=>'homeroom_teacher',str_contains($text,'operator')=>'operator',str_contains($text,'staff tu'),str_contains($text,'staf tu')=>'administration_staff',default=>null};if($type&&$row->matched_personnel_id){try{$duties->save($actor,$set,['personnel_id'=>$row->matched_personnel_id,'classroom_id'=>$type==='homeroom_teacher'?$row->matched_classroom_id:null,'duty_type'=>$type,'duty_name'=>ucwords(str_replace('_',' ',$type)),'notes'=>'Hasil import LEGGER']);}catch(\Illuminate\Validation\ValidationException){}}}$batch->update(['status'=>'saved_as_draft']);activity('teaching-assignments')->causedBy($actor)->performedOn($set)->log('Menyimpan draft hasil import pembagian tugas.');return $set->loadCount(['assignments','additionalDuties']);});}
}
