<!doctype html><html lang="id"><head><meta charset="utf-8"><style>
@page{size:A4 portrait;margin:16mm}body{font-family:DejaVu Sans,Arial,sans-serif;color:#183b2b;font-size:10pt}.header{text-align:center;border-bottom:2px solid #183b2b;padding-bottom:10px}.header img{max-height:58px}.gold{border-bottom:1px solid #b08d2f}.title{text-align:center;font-size:16pt;margin:14px}.grid{width:100%;border-collapse:collapse}.grid th,.grid td{border:1px solid #bbb;padding:6px}.grid th{background:#f2f4f3}.section{font-weight:bold;color:#183b2b;border-bottom:1px solid #b08d2f;margin-top:13px;padding-bottom:3px}.meta td{padding:3px}.money{width:55%;margin-left:auto}.money td{padding:3px}.status{border:2px solid #183b2b;padding:7px;text-align:center;font-weight:bold;margin:10px 0}.verify{margin-top:16px;width:100%}.code{font-family:monospace;letter-spacing:2px}.footer{position:fixed;bottom:0;width:100%;text-align:center;border-top:1px solid #aaa;padding-top:5px;font-size:8pt;color:#555}
</style></head><body>
<div class="header">@if(data_get($snapshot,'school.logo_path'))<img src="{{ public_path('storage/'.data_get($snapshot,'school.logo_path')) }}" alt="Logo">@endif<h2>{{ data_get($snapshot,'school.name') }}</h2><div>{{ data_get($snapshot,'school.address') }}</div><div>{{ collect([data_get($snapshot,'school.phone'),data_get($snapshot,'school.email'),data_get($snapshot,'school.website')])->filter()->join(' | ') }}</div></div>
<div class="title">TANDA TERIMA PEMBAYARAN SPP</div><table class="meta"><tr><td>Nomor</td><td>: {{ $snapshot['payment_number'] }}</td></tr><tr><td>Tanggal</td><td>: {{ \Carbon\Carbon::parse($snapshot['paid_at'])->locale('id')->translatedFormat('d F Y H:i') }}</td></tr><tr><td>Status</td><td>: <b>{{ $snapshot['status'] }}</b></td></tr></table>
<div class="section">DATA SISWA</div><table class="meta"><tr><td>Nama</td><td>: {{ data_get($snapshot,'student.name') }}</td><td>NIS / NISN</td><td>: {{ data_get($snapshot,'student.nis','—') }} / {{ data_get($snapshot,'student.nisn','—') }}</td></tr><tr><td>Kelas</td><td>: {{ data_get($snapshot,'student.class','—') }}</td><td>Tahun Ajaran / Semester</td><td>: {{ data_get($snapshot,'invoice.academic_year','—') }} / {{ data_get($snapshot,'invoice.semester','—') }}</td></tr></table>
<div class="section">RINCIAN PEMBAYARAN</div><table class="grid"><thead><tr><th>No</th><th>Keterangan</th><th>Periode</th><th>Nominal</th></tr></thead><tbody>@forelse(data_get($snapshot,'invoice.items',[]) as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item['description'] }}</td><td>{{ data_get($snapshot,'invoice.period') }}</td><td>Rp {{ number_format($item['amount'],0,',','.') }}</td></tr>@empty<tr><td>1</td><td>{{ data_get($snapshot,'invoice.number','Pembayaran') }}</td><td>{{ data_get($snapshot,'invoice.period') }}</td><td>Rp {{ number_format($snapshot['amount'],0,',','.') }}</td></tr>@endforelse</tbody></table>
<table class="money"><tr><td>Total Tagihan</td><td>Rp {{ number_format(data_get($snapshot,'invoice.total'),0,',','.') }}</td></tr><tr><td>Pembayaran Sebelumnya</td><td>Rp {{ number_format(data_get($snapshot,'invoice.previous'),0,',','.') }}</td></tr><tr><td>Pembayaran Ini</td><td>Rp {{ number_format($snapshot['amount'],0,',','.') }}</td></tr><tr><td>Total Dibayar</td><td>Rp {{ number_format(data_get($snapshot,'invoice.paid'),0,',','.') }}</td></tr><tr><td>Sisa Tagihan</td><td>Rp {{ number_format(data_get($snapshot,'invoice.remaining'),0,',','.') }}</td></tr></table><div class="status">{{ $snapshot['status'] }}</div>
<div class="section">METODE PEMBAYARAN</div><table class="meta"><tr><td>Metode</td><td>: {{ ['cash'=>'Tunai','bank_transfer'=>'Transfer Bank','bri_briva'=>'BRI BRIVA'][$snapshot['method']] ?? $snapshot['method'] }}</td><td>Petugas</td><td>: {{ $snapshot['officer'] }}</td></tr>@if($snapshot['method']!=='cash')<tr><td>Referensi Bank</td><td>: {{ $snapshot['bank_reference'] ?: '—' }}</td></tr>@endif</table>
<p><b>CATATAN</b><br>Dokumen ini merupakan bukti pembayaran sah yang diterbitkan secara elektronik oleh {{ data_get($snapshot,'school.name') }}. Tidak memerlukan tanda tangan basah apabila validasi elektronik berhasil.</p>
<table class="verify"><tr><td><b>QR VERIFIKASI</b><br><span class="code">{{ $verificationCode }}</span><br>{{ $verificationUrl }}</td><td style="text-align:center"><b>BENDAHARA</b><br><br><br>({{ $snapshot['officer'] }})</td></tr></table>
<div class="footer">Dicetak dari Sistem Informasi {{ data_get($snapshot,'school.name') }} · Tanggal generate PDF: {{ now()->locale('id')->translatedFormat('d F Y H:i') }}</div></body></html>
