<?php

declare(strict_types=1);
namespace App\Http\Controllers\TeachingAssignments;
use App\Http\Controllers\Controller;use App\Models\{Personnel,TeachingAssignmentSet};use App\Services\Foundation\SchoolProfileService;use App\Services\TeachingAssignments\{TeachingAssignmentConflictService,TeachingAssignmentReadinessService,TeachingAssignmentReportService};use Illuminate\Http\Request;use Illuminate\View\View;
class TeachingAssignmentReportController extends Controller
{
 public function __invoke(Request $request,TeachingAssignmentReportService $service,TeachingAssignmentReadinessService $readiness,TeachingAssignmentConflictService $conflictService):View{$this->authorizeView($request);$sets=TeachingAssignmentSet::with(['academicYear','createdBy','activatedBy','additionalDuties.personnel','additionalDuties.classroom'])->withCount(['assignments','additionalDuties'])->latest()->get();$set=$sets->firstWhere('id',$request->integer('set'))??$sets->first();return view('teaching-assignments.index',['sets'=>$sets,'set'=>$set,'tab'=>(string)($request->input('tab')??$request->route('tab')??'summary'),'teachers'=>$set?$service->teachers($set,$request->string('search')->toString()):collect(),'classrooms'=>$set?$service->classrooms($set):collect(),'inspection'=>$set?$readiness->inspect($set):null,'conflicts'=>$set?$conflictService->conflicts($set):collect(),'hasActiveSet'=>$sets->contains('status','active')]);}
 public function print(Request $request,Personnel $personnel,TeachingAssignmentReportService $service,SchoolProfileService $profiles):View{$own=$request->user()->personnel?->is($personnel)&&$request->user()->can('teaching-assignments.print-own');abort_unless($request->user()->can('teaching-assignments.print')||$own,403);$set=TeachingAssignmentSet::with('academicYear')->find($request->integer('set'))??TeachingAssignmentSet::with('academicYear')->where('status','active')->latest('activated_at')->firstOrFail();abort_if($own&&$set->status!=='active',403);activity('teaching-assignments')->causedBy($request->user())->performedOn($set)->log($own?'Mencetak pembagian tugas sendiri.':'Mencetak pembagian tugas.');return view('teaching-assignments.print',['set'=>$set,'personnel'=>$personnel,'report'=>$service->personnel($set,$personnel),'profile'=>$profiles->current()]);}
 private function authorizeView(Request $request):void{abort_unless($request->user()->can('teaching-assignments.view'),403);}
}
