<x-layouts.app :title="$title" :breadcrumbs="['HRD','Absensi Saya']">
<x-ui.card class="mx-auto max-w-xl">
 <div class="text-center"><p class="text-lg font-bold text-emerald-950">{{ $personnel->full_name }}</p><p class="text-sm text-slate-500">{{ now()->translatedFormat('l, d F Y') }} · Shift {{ $personnel->default_shift_number }}</p></div>
 <div class="my-5 rounded-2xl bg-slate-50 p-5 text-center" data-result>@if(!$attendance)<p>Belum check-in</p>@else<p>Masuk <b>{{ $attendance->check_in_time?->format('H:i') }}</b></p><p>Pulang <b>{{ $attendance->check_out_time?->format('H:i')??'Belum' }}</b></p>@endif</div>
 <div class="mb-5 space-y-2 text-sm" data-steps><p class="font-bold text-emerald-950">{{ !$attendance?'ABSENSI MASUK':'ABSENSI PULANG' }}</p><p>✓ Akun Personalia</p><p data-device>○ Perangkat dikenali</p>@if($security['hrd_attendance_face_enabled'])<p data-face>○ Verifikasi wajah</p>@endif<p data-location>○ Mendapatkan lokasi</p><p data-submit>○ Mengirim absensi</p></div>
 @if($security['hrd_attendance_face_enabled'])<div class="mb-4"><label for="face_snapshot">Foto wajah terbaru</label><input id="face_snapshot" type="file" accept="image/*" capture="user" class="mt-1"><p class="mt-1 text-xs text-slate-500">Foto diproses sementara oleh provider dan tidak disimpan sebagai arsip absensi.</p></div>@endif
 <p class="mb-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900 hidden" data-error></p>
 <button type="button" class="btn btn-primary w-full" data-attendance @disabled($attendance?->check_out_time)>{{ !$attendance?'CHECK-IN':'CHECK-OUT' }}</button>
 <p class="mt-3 text-center text-xs text-slate-500">Lokasi dan waktu resmi diverifikasi oleh server. Kamera/lokasi memerlukan HTTPS pada production.</p>
</x-ui.card>
<script>
(()=>{const button=document.querySelector('[data-attendance]');if(!button)return;const csrf=document.querySelector('meta[name="csrf-token"]')?.content;const action=@js(!$attendance?'check_in':'check_out');const endpoint=@js(!$attendance?route('hrd.attendance.check-in',[],false):route('hrd.attendance.check-out',[],false));const challengeUrl=@js(route('hrd.attendance.challenge',[],false));const faceUrl=@js(route('hrd.attendance.face',[],false));const faceRequired=@js((bool)$security['hrd_attendance_face_enabled']);const maxAccuracy=@js((int)$security['hrd_attendance_max_accuracy_meter']);
 const set=(name,text)=>{const el=document.querySelector(`[data-${name}]`);if(el)el.textContent=text};const error=document.querySelector('[data-error]');let currentDevice=null;
 function uuid(){let id=localStorage.getItem('attendance_device_uuid');if(!id){id=crypto.randomUUID();localStorage.setItem('attendance_device_uuid',id)}return id}function device(){return{device_uuid:uuid(),device_name:navigator.platform||'Perangkat pribadi',browser:navigator.userAgentData?.brands?.[0]?.brand||'Browser',platform:navigator.userAgentData?.platform||navigator.platform}}
 async function post(url,body,isForm=false){let response;try{response=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json',...(isForm?{}:{'Content-Type':'application/json'})},body:isForm?body:JSON.stringify(body)})}catch(e){throw new Error('Tidak dapat terhubung ke server. Periksa koneksi internet Anda, lalu coba lagi.')}let json;try{json=await response.json()}catch(e){throw new Error(response.status===419?'Sesi Anda telah berakhir. Muat ulang halaman lalu coba lagi.':'Server mengirim respons yang tidak dapat diproses. Muat ulang halaman lalu coba lagi.')}if(!response.ok)throw new Error(json.error?.message||Object.values(json.errors||{}).flat()[0]||json.message||'Permintaan gagal.');return json.data}
 function locate(){return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve(p),reject,{enableHighAccuracy:true,maximumAge:0,timeout:15000}))}
 button.addEventListener('click',async()=>{button.disabled=true;error.classList.add('hidden');try{if(!window.isSecureContext&&!['localhost','127.0.0.1'].includes(location.hostname))throw new Error('Absensi memerlukan HTTPS agar lokasi dan kamera dapat digunakan.');set('device','… Memeriksa perangkat');const d=device();currentDevice=d;const challenge=await post(challengeUrl,{action,...d});set('device','✓ Perangkat dikenali');if(faceRequired){const file=document.querySelector('#face_snapshot')?.files?.[0];if(!file)throw new Error('Ambil foto wajah terlebih dahulu.');set('face','… Memverifikasi wajah');const form=new FormData();Object.entries({...d,challenge_id:challenge.id,nonce:challenge.nonce,snapshot:file}).forEach(([k,v])=>form.append(k,v));await post(faceUrl,form,true);set('face','✓ Wajah terverifikasi')}set('location','… Mencari lokasi akurat');let position;for(let attempt=0;attempt<3;attempt++){position=await locate();if(position.coords.accuracy<=maxAccuracy)break}if(position.coords.accuracy>maxAccuracy)throw new Error('Akurasi GPS masih rendah. Pindah ke area terbuka atau aktifkan mode lokasi akurat lalu coba lagi.');set('location',`✓ Lokasi ditemukan · Akurasi ${Math.round(position.coords.accuracy)} m`);set('submit','… Mengirim absensi');const c=position.coords;const result=await post(endpoint,{...d,challenge_id:challenge.id,nonce:challenge.nonce,latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy,location_captured_at:new Date(position.timestamp).toISOString(),altitude:c.altitude,altitude_accuracy:c.altitudeAccuracy,heading:c.heading,speed:c.speed});set('submit','✓ Absensi berhasil');document.querySelector('[data-result]').innerHTML=`<p class="font-bold text-emerald-800">✓ ${result.message}</p><p class="mt-2 text-2xl font-bold">${result.time}</p><p class="text-sm text-slate-500">Lokasi Valid${result.distance===null?'':` · ${Math.round(result.distance)} meter dari madrasah`}</p>`;setTimeout(()=>location.reload(),1500)}catch(e){error.textContent=e.message+(e.message.includes('Perangkat belum disetujui')&&currentDevice?` UUID perangkat: ${currentDevice.device_uuid}. Daftarkan perangkat ini melalui menu Perangkat Saya, lalu tunggu validasi Operator atau Super Admin.`:'');error.classList.remove('hidden');button.disabled=false}})})();
</script>
</x-layouts.app>
