<?php
declare(strict_types=1); namespace App\Http\Controllers\Students;
use App\Http\Controllers\Controller; use App\Http\Requests\Students\{StoreStudentRequest,UpdateStudentRequest}; use App\Models\Student; use App\Services\Students\{StudentExportService,StudentService}; use App\Services\Rfid\RfidWriterService; use App\Services\Settings\ApplicationSettingService; use Illuminate\Database\Eloquent\Builder; use Illuminate\Http\{RedirectResponse,Request}; use Illuminate\View\View;
class StudentController extends Controller
{
 public function __construct(private StudentService $service){}
 public static function filtered(Request $request):Builder{$query=Student::query();if($search=$request->string('search')->trim()->toString())$query->where(fn($q)=>$q->where('full_name','like',"%$search%")->orWhere('nisn','like',"%$search%")->orWhere('nik','like',"%$search%")->orWhere('classroom_label','like',"%$search%")->orWhere('phone','like',"%$search%")->orWhere('father_name','like',"%$search%")->orWhere('mother_name','like',"%$search%")->orWhere('guardian_name','like',"%$search%"));foreach(['gender','status','classroom_label'] as $field)if($request->filled($field))$query->where($field,$request->input($field));if($request->input('special_needs')==='yes')$query->whereNotNull('special_needs');if($request->input('special_needs')==='no')$query->whereNull('special_needs');if($request->input('kip_pip')==='yes')$query->whereNotNull('kip_pip_number');if($request->input('kip_pip')==='no')$query->whereNull('kip_pip_number');return $query->orderBy('full_name');}
 public function index(Request $request):View{$q=Student::query();return view('students.index',['title'=>'Data Siswa','students'=>self::filtered($request)->paginate(15)->withQueryString(),'classrooms'=>Student::whereNotNull('classroom_label')->distinct()->orderBy('classroom_label')->pluck('classroom_label'),'stats'=>['total'=>(clone$q)->count(),'active'=>(clone$q)->where('status','active')->count(),'male'=>(clone$q)->where('gender','male')->count(),'female'=>(clone$q)->where('gender','female')->count(),'incomplete_parents'=>(clone$q)->where(fn($x)=>$x->whereNull('father_name')->orWhereNull('mother_name'))->count()]]);}
 public function create():View{return view('students.form',['title'=>'Tambah Siswa','student'=>new Student,'editing'=>false]);}
 public function store(StoreStudentRequest $request):RedirectResponse{$student=$this->service->create($request->validated(),$request->user());return redirect()->route('students.show',$student)->with('status','Data siswa berhasil ditambahkan.');}
 public function show(Request $request,Student $student,StudentExportService $export,RfidWriterService $writer,ApplicationSettingService $settings):View{$student->load(['createdBy','updatedBy','activeRfidCard']);$display=$student->toArray();if(!$request->user()->can('students.view-sensitive')){$display['nik']=$export->mask($student->nik);$display['phone']=$export->mask($student->phone);$display['kip_pip_number']=$export->mask($student->kip_pip_number);$display['address']='Data disembunyikan';}return view('students.show',['title'=>$student->full_name,'student'=>$student,'display'=>$display,'writerOnline'=>(bool)$writer->onlineWriter(),'writerEnabled'=>$settings->get('rfid_writer_enabled',false)]);}
 public function edit(Student $student):View{return view('students.form',['title'=>'Edit Siswa','student'=>$student,'editing'=>true]);}
 public function update(UpdateStudentRequest $request,Student $student):RedirectResponse{$this->service->update($student,$request->validated(),$request->user());return redirect()->route('students.show',$student)->with('status','Data siswa berhasil diperbarui.');}
}
