<x-app-layout title="Form Jurnal Mengajar">
<form class="space-y-6" method="post" action="{{ $journal ? route('teaching-journals.update',$journal) : route('teaching-journals.store') }}">@csrf @if($journal) @method('put') @endif
<input type="hidden" name="lesson_schedule_id" value="{{ old('lesson_schedule_id',$schedule->id) }}"><input type="hidden" name="journal_date" value="{{ old('journal_date',$date) }}">
<x-ui.card><h2 class="font-bold text-emerald-950">Informasi Mengajar</h2><div class="mt-4 grid gap-3 md:grid-cols-3 text-sm"><div>Tanggal<br><b>{{ \Carbon\Carbon::parse($date)->format('d/m/Y') }}</b></div><div>Jadwal<br><b>{{ substr($schedule->starts_at,0,5) }}-{{ substr($schedule->ends_at,0,5) }}</b></div><div>Guru<br><b>{{ $schedule->employee->name }}</b></div><div>Kelas<br><b>{{ $schedule->classroom->name }}</b></div><div>Mata Pelajaran<br><b>{{ $schedule->subject->name }}</b></div><div>Pertemuan Ke<br><b>{{ $meetingNumber }}</b></div></div></x-ui.card>
@php($fields=['learning_topic'=>'Topik','learning_objectives'=>'Tujuan pembelajaran','learning_material'=>'Materi','learning_method'=>'Metode','learning_media'=>'Media','learning_activity'=>'Kegiatan pembelajaran','assessment_activity'=>'Kegiatan penilaian','homework'=>'Tugas/PR','obstacles'=>'Kendala','teacher_notes'=>'Catatan guru','follow_up'=>'Tindak lanjut'])
<x-ui.card><h2 class="font-bold text-emerald-950">Isi Jurnal</h2><div class="mt-4 grid gap-4">@foreach($fields as $name=>$label)<label class="block"><span class="text-sm font-medium">{{ $label }}</span>@if(in_array($name,['learning_topic','learning_method','learning_media']))<input name="{{ $name }}" value="{{ old($name,$journal?->{$name}) }}" class="mt-1 w-full rounded-lg border-slate-300">@else<textarea name="{{ $name }}" class="mt-1 w-full rounded-lg border-slate-300" rows="3">{{ old($name,$journal?->{$name}) }}</textarea>@endif @error($name)<span class="text-sm text-red-600">{{ $message }}</span>@enderror</label>@endforeach</div></x-ui.card>
<div class="flex flex-wrap gap-3"><button name="status" value="draft" class="rounded-lg border px-4 py-2">Simpan Draft</button><button name="status" value="submitted" class="rounded-lg bg-emerald-900 px-4 py-2 text-white">Simpan dan Kirim</button><a class="rounded-lg border px-4 py-2" href="{{ route('teaching-journals.index') }}">Kembali</a></div>
</form>
</x-app-layout>
