<x-app-layout title="Form Jurnal Mengajar">
    <div class="mb-6"><p class="text-sm text-slate-500">Absensi / Jurnal Mengajar</p><h1 class="text-2xl font-semibold text-emerald-950">Form Jurnal Mengajar</h1></div>
    <x-ui.card>
        <form class="space-y-6" method="post" action="{{ $journal ? route('teaching-journals.update', $journal) : route('teaching-journals.store') }}">
            @csrf
            @if ($journal) @method('put') @endif
            <section class="space-y-4"><h2 class="font-semibold text-emerald-950">Penugasan dan Jadwal</h2><label class="block text-sm font-medium text-slate-700">Penugasan<select class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="teaching_assignment_id">@foreach ($assignments as $assignment)<option value="{{ $assignment->id }}" @selected((int) old('teaching_assignment_id', $journal?->teaching_assignment_id) === $assignment->id)>{{ $assignment->classroom->name }} - {{ $assignment->subject->name }}</option>@endforeach</select>@error('teaching_assignment_id')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><div class="grid gap-4 md:grid-cols-3"><label class="block text-sm font-medium text-slate-700">Tanggal<input class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" type="date" name="journal_date" value="{{ old('journal_date', $journal?->journal_date?->toDateString()) }}" required></label><label class="block text-sm font-medium text-slate-700">Mulai<input class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" type="time" name="starts_at" value="{{ old('starts_at', $journal?->starts_at) }}" required></label><label class="block text-sm font-medium text-slate-700">Selesai<input class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" type="time" name="ends_at" value="{{ old('ends_at', $journal?->ends_at) }}" required></label></div><label class="block text-sm font-medium text-slate-700">Jumlah JP<input class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" type="number" name="lesson_hours" value="{{ old('lesson_hours', $journal?->lesson_hours ?? 1) }}" min="1"></label></section>
            <section class="space-y-4"><h2 class="font-semibold text-emerald-950">Materi dan Tujuan</h2><label class="block text-sm font-medium text-slate-700">Materi<textarea class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="material" required>{{ old('material', $journal?->material) }}</textarea>@error('material')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label class="block text-sm font-medium text-slate-700">Tujuan Pembelajaran<textarea class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="learning_objectives">{{ old('learning_objectives', $journal?->learning_objectives) }}</textarea></label></section>
            <section class="grid gap-4 md:grid-cols-2"><label class="block text-sm font-medium text-slate-700">Metode<input class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="method" value="{{ old('method', $journal?->method) }}"></label><label class="block text-sm font-medium text-slate-700">Media<input class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="media" value="{{ old('media', $journal?->media) }}"></label></section>
            <section class="space-y-4"><h2 class="font-semibold text-emerald-950">Tugas dan Evaluasi</h2><label class="block text-sm font-medium text-slate-700">Tugas<textarea class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="assignment">{{ old('assignment', $journal?->assignment) }}</textarea></label><label class="block text-sm font-medium text-slate-700">Evaluasi<textarea class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="assessment">{{ old('assessment', $journal?->assessment) }}</textarea></label><label class="block text-sm font-medium text-slate-700">Catatan Guru<textarea class="mt-1 w-full rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="teacher_notes">{{ old('teacher_notes', $journal?->teacher_notes) }}</textarea></label></section>
            <label class="block text-sm font-medium text-slate-700">Status Workflow<select class="mt-1 rounded-lg border-slate-300 focus:border-emerald-800 focus:ring-emerald-800" name="status"><option value="draft" @selected(old('status', $journal?->status->value ?? 'draft') === 'draft')>Simpan Draft</option><option value="submitted" @selected(old('status', $journal?->status->value) === 'submitted')>Kirim</option></select></label>
            <button class="rounded-lg bg-emerald-900 px-4 py-2 font-medium text-white hover:bg-emerald-800 focus:outline-none focus:ring-2 focus:ring-emerald-700">Simpan Jurnal</button>
        </form>
    </x-ui.card>
</x-app-layout>
