<x-app-layout title="Detail Jurnal Mengajar">
    <div class="mb-6 print:hidden"><p class="text-sm text-slate-500">Absensi / Jurnal Mengajar</p><h1 class="text-2xl font-semibold text-emerald-950">Detail Jurnal Mengajar</h1></div>
    @if (session('status'))<div class="mb-4 rounded-lg bg-emerald-50 p-4 text-emerald-900 print:hidden">{{ session('status') }}</div>@endif
    <x-ui.card>
        <div class="space-y-3 print:space-y-2"><p><strong>Guru:</strong> {{ $journal->employee->name }}</p><p><strong>Kelas / Mapel:</strong> {{ $journal->classroom->name }} / {{ $journal->subject->name }}</p><p><strong>Waktu:</strong> {{ $journal->journal_date->format('d/m/Y') }} {{ $journal->starts_at }} - {{ $journal->ends_at }}</p><p><strong>Status:</strong> {{ $journal->status->value }}</p><p><strong>Materi:</strong> {{ $journal->material }}</p><p><strong>Tujuan:</strong> {{ $journal->learning_objectives ?? '-' }}</p><p><strong>Metode / Media:</strong> {{ $journal->method ?? '-' }} / {{ $journal->media ?? '-' }}</p><p><strong>Tugas / Evaluasi:</strong> {{ $journal->assignment ?? '-' }} / {{ $journal->assessment ?? '-' }}</p></div>
        <h2 class="mt-6 font-semibold text-emerald-950">Kehadiran Siswa</h2>
        <div class="mt-3 overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead><tr><th class="px-3 py-2 text-left">Siswa</th><th class="px-3 py-2 text-left">Status</th><th class="px-3 py-2 text-left">Catatan</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($journal->students as $student)<tr><td class="px-3 py-2">{{ $student->name }}</td><td class="px-3 py-2">{{ $student->pivot->status }}</td><td class="px-3 py-2">{{ $student->pivot->notes ?? '-' }}</td></tr>@empty<tr><td class="px-3 py-8 text-center text-slate-500" colspan="3">Belum ada data kehadiran siswa pada jurnal ini.</td></tr>@endforelse</tbody></table></div>
        <div class="mt-6 flex flex-wrap gap-3 print:hidden"><a class="rounded-lg border px-4 py-2 hover:bg-slate-50" href="{{ route('teaching-journals.print', $journal) }}">Cetak</a><a class="rounded-lg border px-4 py-2 hover:bg-slate-50" href="{{ route('teaching-journals.edit', $journal) }}">Edit</a><form method="post" action="{{ route('teaching-journals.submit', $journal) }}">@csrf @method('patch')<button class="rounded-lg bg-emerald-900 px-4 py-2 text-white hover:bg-emerald-800">Kirim</button></form><form method="post" action="{{ route('teaching-journals.verify', $journal) }}">@csrf @method('patch')<button class="rounded-lg bg-emerald-900 px-4 py-2 text-white hover:bg-emerald-800">Verifikasi</button></form><form class="flex gap-2" method="post" action="{{ route('teaching-journals.reject', $journal) }}">@csrf @method('patch')<input class="rounded-lg border-slate-300" name="rejection_reason" placeholder="Alasan penolakan" required><button class="rounded-lg bg-red-700 px-4 py-2 text-white hover:bg-red-600">Tolak</button></form></div>
    </x-ui.card>
</x-app-layout>
