<x-app-layout :title="$title">
<form class="space-y-6" method="post" enctype="multipart/form-data" action="{{ $mode === 'create' ? route('employees.store') : route('employees.update',$employee) }}">
@csrf @if($mode==='edit') @method('put') @endif
@php($sections=[['Identitas',['front_title'=>'Gelar depan','name'=>'Nama lengkap','back_title'=>'Gelar belakang','employee_number'=>'NIY/nomor pegawai yayasan','nip'=>'NIP','nuptk'=>'NUPTK','national_identity_number'=>'NIK','birth_place'=>'Tempat lahir','birth_date'=>'Tanggal lahir','religion'=>'Agama']],['Kontak dan Alamat',['phone'=>'Nomor telepon','whatsapp'=>'Nomor WhatsApp','email'=>'Email','address'=>'Alamat lengkap','village'=>'Desa/Kelurahan','district'=>'Kecamatan','city'=>'Kabupaten/Kota','province'=>'Provinsi','postal_code'=>'Kode pos']],['Data Kepegawaian',['position'=>'Jabatan di Madrasah','joined_at'=>'Tanggal mulai bekerja','left_at'=>'Tanggal selesai bekerja','notes'=>'Keterangan']],['Pendidikan',['last_education'=>'Pendidikan terakhir','major'=>'Program studi/jurusan','education_institution'=>'Nama institusi','graduation_year'=>'Tahun lulus']]])
@foreach($sections as [$heading,$fields])
<section class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="mb-4 text-lg font-bold text-emerald-950">{{ $loop->iteration }}. {{ $heading }}</h2><div class="grid gap-4 md:grid-cols-2">
@foreach($fields as $name=>$label)<label class="block"><span class="text-sm font-semibold text-slate-700">{{ $label }}</span>@if(in_array($name,['address','notes']))<textarea name="{{ $name }}" class="mt-1 w-full rounded-xl border-slate-300">{{ old($name,$employee->{$name}) }}</textarea>@else<input name="{{ $name }}" @if(str_contains($name,'date')) type="date" @elseif($name==='graduation_year') type="number" @else type="text" @endif value="{{ old($name, optional($employee->{$name})->format('Y-m-d') ?? $employee->{$name}) }}" class="mt-1 w-full rounded-xl border-slate-300">@endif @error($name)<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</label>@endforeach
</div></section>
@endforeach
<section class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="mb-4 text-lg font-bold text-emerald-950">5. Pilihan Utama, Foto dan Akun Pengguna</h2><div class="grid gap-4 md:grid-cols-2">
<label><span class="text-sm font-semibold">Jenis kelamin</span><select name="gender" class="mt-1 w-full rounded-xl border-slate-300"><option value="">Pilih</option>@foreach($genders as $gender)<option value="{{ $gender->value }}" @selected(old('gender',$employee->gender?->value)===$gender->value)>{{ $gender->label() }}</option>@endforeach</select>@error('gender')<p class="text-sm text-rose-600">{{ $message }}</p>@enderror</label>
<label><span class="text-sm font-semibold">Kategori pegawai</span><select name="employment_type" class="mt-1 w-full rounded-xl border-slate-300"><option value="">Pilih</option>@foreach($types as $type)<option value="{{ $type->value }}" @selected(old('employment_type',$employee->employment_type?->value)===$type->value)>{{ $type->label() }}</option>@endforeach</select>@error('employment_type')<p class="text-sm text-rose-600">{{ $message }}</p>@enderror</label>
<label><span class="text-sm font-semibold">Status Kepegawaian</span><select name="employee_status" class="mt-1 w-full rounded-xl border-slate-300"><option value="">Pilih</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('employee_status',$employee->employee_status?->value)===$status->value)>{{ $status->label() }}</option>@endforeach</select>@error('employee_status')<p class="text-sm text-rose-600">{{ $message }}</p>@enderror</label>
<label><span class="text-sm font-semibold">Foto pegawai</span><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" class="mt-1 w-full rounded-xl border border-slate-300 p-2">@error('photo')<p class="text-sm text-rose-600">{{ $message }}</p>@enderror</label>
<label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$employee->exists ? $employee->is_active : true))> <span>Aktif</span></label>
</div></section>
<div class="flex justify-end gap-3"><a class="rounded-xl border px-4 py-2 font-semibold" href="{{ $employee->exists ? route('employees.show',$employee) : route('employees.index') }}">Batal</a><button class="rounded-xl bg-emerald-800 px-5 py-2 font-semibold text-white">Simpan Data</button></div>
</form>
</x-app-layout>
