<x-app-layout :title="$title">
    <div class="space-y-6">
        <div class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
            <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div><h2 class="text-2xl font-bold text-emerald-950">Guru & Pegawai</h2><p class="mt-1 text-sm text-slate-600">Kelola data identitas, kontak, kepegawaian, dokumen, dan akun pengguna pegawai madrasah.</p></div>
                <div class="flex gap-2">@can('employees.export')<a class="rounded-xl border px-4 py-2 text-sm font-semibold" href="{{ route('employees.export', request()->query()) }}">Export CSV</a>@endcan @can('employees.create')<a class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-800" href="{{ route('employees.import.form') }}">Upload XLSX</a><a class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white" href="{{ route('employees.create') }}">Tambah Guru/Pegawai</a>@endcan</div>
            </div>
            <form class="mt-6 grid gap-3 md:grid-cols-5" method="get">
                <input class="rounded-xl border-slate-300 md:col-span-2" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Cari nama, NIP, NUPTK, NIY, WhatsApp">
                <select class="rounded-xl border-slate-300" name="employment_type"><option value="">Semua kategori</option>@foreach($types as $type)<option value="{{ $type->value }}" @selected(($filters['employment_type'] ?? '')===$type->value)>{{ $type->label() }}</option>@endforeach</select>
                <select class="rounded-xl border-slate-300" name="employee_status"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(($filters['employee_status'] ?? '')===$status->value)>{{ $status->label() }}</option>@endforeach</select>
                <select class="rounded-xl border-slate-300" name="is_active"><option value="">Aktif & Tidak Aktif</option><option value="1" @selected(($filters['is_active'] ?? '')==='1')>Aktif</option><option value="0" @selected(($filters['is_active'] ?? '')==='0')>Tidak Aktif</option></select>
                <input class="rounded-xl border-slate-300" name="position" value="{{ $filters['position'] ?? '' }}" placeholder="Jabatan di Madrasah">
                <div class="flex gap-2 md:col-span-4"><button class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">Terapkan Filter</button><a href="{{ route('employees.index') }}" class="rounded-xl border px-4 py-2 text-sm font-semibold">Reset Filter</a></div>
            </form>
        </div>
        <div class="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200">
            <div class="border-b p-4 text-sm text-slate-600">Menampilkan {{ $employees->total() }} hasil.</div>
            @if(session('import_errors'))<div class="border-b bg-amber-50 p-4 text-sm text-amber-900"><p class="font-semibold">Catatan import:</p><ul class="mt-1 list-disc pl-5">@foreach(session('import_errors') as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            @if($employees->isEmpty())<div class="p-10 text-center text-slate-600">Belum ada data guru dan pegawai sesuai filter.</div>@else
            <div class="hidden overflow-x-auto lg:block"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Foto</th><th>Nama</th><th>NIY/NIP/Peg.ID</th><th>Pendidikan/Jabatan</th><th>Sertifikasi/JPL</th><th>Rekening</th><th>WhatsApp</th><th>Akun</th><th>Status</th><th>Tindakan</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($employees as $employee)<tr><td class="p-4"><div class="grid h-12 w-12 place-items-center overflow-hidden rounded-full bg-emerald-100 font-bold text-emerald-800">{{ str($employee->name)->substr(0,2)->upper() }}</div></td><td class="font-semibold text-emerald-950">{{ $employee->fullName() }}</td><td>{{ $employee->employee_number ?: '-' }}<br><span class="text-slate-500">{{ $employee->nip ?: $employee->peg_id ?: '-' }}</span></td><td>{{ $employee->last_education ?: '-' }}<br><span class="text-slate-500">{{ $employee->position }}</span></td><td>{{ $employee->certification_status ?: '-' }}<br><span class="text-slate-500">{{ $employee->weekly_teaching_hours ? $employee->weekly_teaching_hours . ' JPL' : '-' }}</span></td><td>{{ $employee->bank_name ?: '-' }}<br><span class="text-slate-500">{{ $employee->bank_account_number ?: '-' }}</span></td><td>{{ $employee->whatsapp ?? '-' }}</td><td>{{ $employee->user?->email ?? 'Belum terhubung' }}</td><td><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $employee->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $employee->is_active ? 'Aktif' : 'Tidak Aktif' }}</span></td><td><a class="font-semibold text-emerald-700" href="{{ route('employees.show',$employee) }}">Detail</a></td></tr>@endforeach</tbody></table></div>
            <div class="divide-y lg:hidden">@foreach($employees as $employee)<a class="block p-4" href="{{ route('employees.show',$employee) }}"><p class="font-bold text-emerald-950">{{ $employee->fullName() }}</p><p class="text-sm text-slate-600">{{ $employee->employment_type?->label() }} · {{ $employee->mainNumber() }}</p></a>@endforeach</div>
            <div class="p-4">{{ $employees->links() }}</div>@endif
        </div>
    </div>
</x-app-layout>
