<?php

declare(strict_types=1);
namespace Tests\Feature\TeachingAssignments;
use App\Enums\ClassroomProgramType;use App\Models\{AcademicYear,AdditionalDuty,Classroom,GradeLevel,Personnel,Subject,SubjectGradeLoad,TeachingAssignmentSet,User};use App\Services\TeachingAssignments\{TeachingAssignmentDutyService,TeachingAssignmentService};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use Tests\TestCase;
class TeachingAssignmentDraftTest extends TestCase
{
 use RefreshDatabase;
 private function data(string $program='regular'):array{$year=AcademicYear::create(['name'=>'2026/2027','starts_at'=>'2026-07-01','ends_at'=>'2027-06-30']);$grade=GradeLevel::create(['number'=>$program==='full_day'?2:1,'name'=>'Kelas I','roman_label'=>$program==='full_day'?'II':'I','sort_order'=>$program==='full_day'?2:1]);$room=Classroom::create(['academic_year_id'=>$year->id,'grade_level_id'=>$grade->id,'program_type'=>$program,'code'=>'I A']);$subject=Subject::create(['code'=>$program==='full_day'?'BIN-FD':'BIN','name'=>'Bahasa Indonesia','is_active'=>true]);SubjectGradeLoad::create(['academic_year_id'=>$year->id,'subject_id'=>$subject->id,'grade_level_id'=>$grade->id,'program_type'=>$program,'weekly_hours'=>$program==='full_day'?8:6]);$person=Personnel::create(['full_name'=>'Guru Uji','gender'=>'male','employment_status'=>'GTY','position'=>'Guru','is_active'=>true]);$actor=User::factory()->create();$set=TeachingAssignmentSet::create(['academic_year_id'=>$year->id,'name'=>'Draft Uji','status'=>'draft','source'=>'manual','created_by'=>$actor->id]);return compact('year','grade','room','subject','person','actor','set');}
 public function test_assignment_uses_regular_and_full_day_curriculum_load():void{foreach(['regular'=>6,'full_day'=>8] as $program=>$expected){$d=$this->data($program);$a=app(TeachingAssignmentService::class)->save($d['actor'],$d['set'],['classroom_id'=>$d['room']->id,'subject_id'=>$d['subject']->id,'personnel_id'=>$d['person']->id,'teacher_role'=>'primary']);$this->assertSame($expected,$a->weekly_periods);}}
 public function test_inactive_and_unavailable_entities_are_rejected():void{$d=$this->data();$d['subject']->update(['is_active'=>false]);$this->expectException(ValidationException::class);app(TeachingAssignmentService::class)->save($d['actor'],$d['set'],['classroom_id'=>$d['room']->id,'subject_id'=>$d['subject']->id,'personnel_id'=>$d['person']->id,'teacher_role'=>'primary']);}
 public function test_duty_periods_and_teacher_total_are_official():void{$d=$this->data();$assignment=app(TeachingAssignmentService::class)->save($d['actor'],$d['set'],['classroom_id'=>$d['room']->id,'subject_id'=>$d['subject']->id,'personnel_id'=>$d['person']->id,'teacher_role'=>'primary']);$duties=app(TeachingAssignmentDutyService::class);$head=$duties->save($d['actor'],$d['set'],['personnel_id'=>$d['person']->id,'duty_type'=>'headmaster','duty_name'=>'Kepala Madrasah']);$this->assertSame(24,$head->equivalent_periods);$this->assertSame($assignment->weekly_periods+24,$d['person']->totalEquivalentPeriods($d['set']));foreach(['operator','administration_staff'] as $type)$this->assertSame(0,$duties->save($d['actor'],$d['set'],['personnel_id'=>$d['person']->id,'duty_type'=>$type,'duty_name'=>$type])->equivalent_periods);}
 public function test_homeroom_duty_is_six_and_not_duplicated():void{$d=$this->data();$service=app(TeachingAssignmentDutyService::class);$payload=['personnel_id'=>$d['person']->id,'classroom_id'=>$d['room']->id,'duty_type'=>'homeroom_teacher','duty_name'=>'Wali Kelas'];$this->assertSame(6,$service->save($d['actor'],$d['set'],$payload)->equivalent_periods);$service->save($d['actor'],$d['set'],$payload);$this->assertSame(1,AdditionalDuty::count());}
 public function test_draft_is_not_active_and_guest_is_forbidden():void{$d=$this->data();$this->assertFalse(TeachingAssignmentSet::where('status','active')->exists());$this->actingAs(User::factory()->create(['is_active'=>true,'must_change_password'=>false]))->get(route('teaching-assignments.index'))->assertForbidden();}
}
