<?php

declare(strict_types=1);
namespace Tests\Feature\TeachingAssignments;
use App\Models\{AcademicYear,Classroom,GradeLevel,Personnel,Subject,SubjectGradeLoad,TeachingAssignment,TeachingAssignmentSet,User};use App\Services\TeachingAssignments\{TeachingAssignmentActivationService,TeachingAssignmentConflictService,TeachingAssignmentReadinessService};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use Tests\TestCase;
class TeachingAssignmentConflictActivationTest extends TestCase
{
 use RefreshDatabase;
 private function fixture(string $suffix=''):array{$year=AcademicYear::create(['name'=>'2026/2027'.$suffix,'starts_at'=>'2026-07-01','ends_at'=>'2027-06-30']);$grade=GradeLevel::create(['number'=>$suffix===''?1:2,'name'=>'Kelas I','roman_label'=>$suffix===''?'I':'II','sort_order'=>$suffix===''?1:2]);$room=Classroom::create(['academic_year_id'=>$year->id,'grade_level_id'=>$grade->id,'program_type'=>'full_day','code'=>'I','name'=>'As-Salam']);$quran=Subject::create(['code'=>'QH'.$suffix,'name'=>"Al Qur'an Hadis",'is_active'=>true]);$other=Subject::create(['code'=>'LAIN'.$suffix,'name'=>'Struktur Lain','is_active'=>true]);SubjectGradeLoad::create(['subject_id'=>$quran->id,'grade_level_id'=>$grade->id,'program_type'=>'full_day','weekly_hours'=>2]);SubjectGradeLoad::create(['subject_id'=>$other->id,'grade_level_id'=>$grade->id,'program_type'=>'full_day','weekly_hours'=>60]);$farisa=Personnel::create(['full_name'=>'Farisa Aufi Saputri, S.Pd.','gender'=>'female','employment_status'=>'GTY','position'=>'Guru','is_active'=>true]);$qonita=Personnel::create(['full_name'=>'Qonita Nasyiatul Wahdah, S.Ag.','gender'=>'female','employment_status'=>'GTY','position'=>'Guru','is_active'=>true]);$actor=User::factory()->create();$set=TeachingAssignmentSet::create(['academic_year_id'=>$year->id,'name'=>'Draft 2026/2027','status'=>'draft','source'=>'xlsx_import','created_by'=>$actor->id]);TeachingAssignment::create(['assignment_set_id'=>$set->id,'academic_year_id'=>$year->id,'classroom_id'=>$room->id,'subject_id'=>$quran->id,'personnel_id'=>$farisa->id,'weekly_periods'=>2,'teacher_role'=>'primary','is_primary'=>true]);TeachingAssignment::create(['assignment_set_id'=>$set->id,'academic_year_id'=>$year->id,'classroom_id'=>$room->id,'subject_id'=>$quran->id,'personnel_id'=>$qonita->id,'weekly_periods'=>2,'teacher_role'=>'primary','is_primary'=>true]);TeachingAssignment::create(['assignment_set_id'=>$set->id,'academic_year_id'=>$year->id,'classroom_id'=>$room->id,'subject_id'=>$other->id,'personnel_id'=>$farisa->id,'weekly_periods'=>60,'teacher_role'=>'primary','is_primary'=>true]);return compact('year','grade','room','quran','other','farisa','qonita','actor','set');}
 public function test_farisa_and_qonita_conflict_blocks_activation_and_class_is_64_of_62():void{$d=$this->fixture();$this->assertCount(1,app(TeachingAssignmentConflictService::class)->conflicts($d['set']));$check=app(TeachingAssignmentReadinessService::class)->inspect($d['set']);$this->assertSame(62,$check['rooms'][0]['target']);$this->assertSame(64,$check['rooms'][0]['assigned']);$this->assertSame('Konflik',$check['rooms'][0]['status']);$this->expectException(ValidationException::class);app(TeachingAssignmentActivationService::class)->activate($d['actor'],$d['set']);}
 public function test_selecting_either_teacher_resolves_conflict_and_makes_class_complete():void{foreach(['farisa','qonita'] as $index=>$selected){$d=$this->fixture($index?'B':'');app(TeachingAssignmentConflictService::class)->resolve($d['actor'],$d['set'],$d['room']->id,$d['quran']->id,'single',[],$d[$selected]->id);$check=app(TeachingAssignmentReadinessService::class)->inspect($d['set']);$this->assertSame(62,$check['rooms'][0]['assigned']);$this->assertSame('Lengkap',$check['rooms'][0]['status']);}}
 public function test_shared_teachers_must_total_exactly_two_periods_and_keep_one_primary():void{$d=$this->fixture();$service=app(TeachingAssignmentConflictService::class);try{$service->resolve($d['actor'],$d['set'],$d['room']->id,$d['quran']->id,'shared',[$d['farisa']->id=>2,$d['qonita']->id=>2],$d['farisa']->id);$this->fail('Total empat JP seharusnya ditolak.');}catch(ValidationException){$this->assertTrue(true);}$service->resolve($d['actor'],$d['set'],$d['room']->id,$d['quran']->id,'shared',[$d['farisa']->id=>1,$d['qonita']->id=>1],$d['farisa']->id);$this->assertSame(2,TeachingAssignment::where('subject_id',$d['quran']->id)->sum('weekly_periods'));$this->assertSame(1,TeachingAssignment::where('subject_id',$d['quran']->id)->where('is_primary',true)->count());}
 public function test_activation_archives_old_set_and_leaves_only_one_active():void{$d=$this->fixture();app(TeachingAssignmentConflictService::class)->resolve($d['actor'],$d['set'],$d['room']->id,$d['quran']->id,'single',[],$d['farisa']->id);$old=TeachingAssignmentSet::create(['academic_year_id'=>$d['year']->id,'name'=>'Set Lama','status'=>'active','source'=>'manual']);app(TeachingAssignmentActivationService::class)->activate($d['actor'],$d['set']);$this->assertSame('archived',$old->fresh()->status);$this->assertSame('active',$d['set']->fresh()->status);$this->assertSame(1,TeachingAssignmentSet::where('academic_year_id',$d['year']->id)->where('status','active')->count());}
 public function test_user_without_activate_permission_gets_403():void{$d=$this->fixture();$user=User::factory()->create(['is_active'=>true,'must_change_password'=>false]);$this->actingAs($user)->post(route('teaching-assignments.sets.activate',$d['set']))->assertForbidden();}
}
