<?php

declare(strict_types=1);namespace Tests\Feature\TeachingAssignments;use App\Models\{AcademicYear,AdditionalDuty,Classroom,GradeLevel,Personnel,SchoolProfile,Subject,SubjectGradeLoad,TeachingAssignment,TeachingAssignmentSet,User};use Database\Seeders\AccessControlSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class TeachingAssignmentExperienceTest extends TestCase
{
 use RefreshDatabase;
 private function fixture():array{$this->seed(AccessControlSeeder::class);$year=AcademicYear::create(['name'=>'2026/2027','starts_at'=>'2026-07-01','ends_at'=>'2027-06-30','is_active'=>true]);$grade=GradeLevel::create(['number'=>1,'name'=>'Kelas I','roman_label'=>'I','sort_order'=>1]);$room=Classroom::create(['academic_year_id'=>$year->id,'grade_level_id'=>$grade->id,'code'=>'I A']);$subject=Subject::create(['code'=>'MAT','name'=>'Matematika','is_active'=>true]);SubjectGradeLoad::create(['academic_year_id'=>$year->id,'subject_id'=>$subject->id,'grade_level_id'=>$grade->id,'program_type'=>'regular','weekly_hours'=>6]);$person=Personnel::create(['full_name'=>'Guru Cetak','gender'=>'male','employment_status'=>'GTY','position'=>'Guru','is_active'=>true]);$set=TeachingAssignmentSet::create(['academic_year_id'=>$year->id,'name'=>'Set Aktif','status'=>'active','source'=>'manual','activated_at'=>now()]);TeachingAssignment::create(['assignment_set_id'=>$set->id,'academic_year_id'=>$year->id,'classroom_id'=>$room->id,'subject_id'=>$subject->id,'personnel_id'=>$person->id,'weekly_periods'=>6,'teacher_role'=>'primary','is_primary'=>true]);AdditionalDuty::create(['assignment_set_id'=>$set->id,'academic_year_id'=>$year->id,'personnel_id'=>$person->id,'duty_type'=>'homeroom_teacher','duty_name'=>'Wali Kelas','classroom_id'=>$room->id,'equivalent_periods'=>6]);SchoolProfile::create(['name'=>'MI Pengujian','head_name'=>'Kepala Dari Profil','city'=>'Jepara']);return compact('year','room','subject','person','set');}
 public function test_print_uses_teacher_subject_duty_totals_and_school_profile():void{$d=$this->fixture();$admin=User::where('email','admin@example.test')->firstOrFail();$this->actingAs($admin)->get(route('teaching-assignments.personnel.print',[$d['person'],'set'=>$d['set']->id]))->assertOk()->assertSee('Guru Cetak')->assertSee('Matematika')->assertSee('Wali Kelas')->assertSee('Kepala Dari Profil')->assertSee('12');}
 public function test_exports_are_xlsx_and_static_routes_are_not_model_binding():void{$d=$this->fixture();$admin=User::where('email','admin@example.test')->firstOrFail();$this->actingAs($admin)->get(route('subjects.export'))->assertOk()->assertDownload();$this->actingAs($admin)->get(route('teaching-assignments.export',['set'=>$d['set']->id]))->assertOk()->assertDownload();}
 public function test_teacher_only_sees_and_prints_own_assignment():void{$d=$this->fixture();$teacher=User::factory()->create(['is_active'=>true,'must_change_password'=>false]);$d['person']->update(['user_id'=>$teacher->id]);$teacher->assignRole('guru');$this->actingAs($teacher)->get(route('teaching-assignments.my'))->assertOk()->assertSee('Guru Cetak')->assertSee('Matematika');$this->actingAs($teacher)->get(route('teaching-assignments.personnel.print',$d['person']))->assertOk();$other=Personnel::create(['full_name'=>'Guru Lain','gender'=>'male','employment_status'=>'GTY','position'=>'Guru','is_active'=>true]);$this->actingAs($teacher)->get(route('teaching-assignments.personnel.print',$other))->assertForbidden();}
 public function test_required_static_routes_have_expected_paths_and_responsive_markup():void{$this->assertSame('/subjects/create',route('subjects.create',[],false));$this->assertSame('/subjects/loads',route('subjects.loads',[],false));$this->assertSame('/subjects/export',route('subjects.export',[],false));$this->assertSame('/teaching-assignments/import',route('teaching-assignments.import.form',[],false));$this->assertSame('/teaching-assignments/guide',route('teaching-assignments.guide',[],false));$this->assertSame('/teaching-assignments/drafts',route('teaching-assignments.drafts',[],false));$this->assertSame('/teaching-assignments/export',route('teaching-assignments.export',[],false));$this->assertSame('/my-teaching-assignments',route('teaching-assignments.my',[],false));$this->assertStringContainsString('overflow-x-auto',file_get_contents(resource_path('views/subjects/loads.blade.php')));$this->assertStringContainsString('@page{size:A4',file_get_contents(resource_path('views/teaching-assignments/print.blade.php')));}
 public function test_unlinked_teacher_gets_friendly_message_and_guide_opens():void{$this->fixture();$teacher=User::factory()->create(['is_active'=>true,'must_change_password'=>false]);$teacher->assignRole('guru');$this->actingAs($teacher)->get(route('teaching-assignments.my'))->assertOk()->assertSee('Akun Anda belum terhubung dengan Data Personalia');$this->actingAs($teacher)->get(route('teaching-assignments.guide'))->assertOk()->assertSee('Panduan Mata Pelajaran & Pembagian Tugas');}
}
