<x-app-layout><x-slot name="header"><h1 class="text-xl font-semibold text-emerald-950">Jadwal Pelajaran</h1><p class="text-sm text-slate-600">Jadwal Per Kelas, Jadwal Per Guru, Daftar Jadwal, dan Susun Jadwal.</p></x-slot><div class="space-y-4"><div class="flex gap-2">@can('schedules.import')<a class="rounded border border-emerald-800 px-4 py-2 text-emerald-900" href="{{ route('schedules.import') }}">Import Jadwal</a>@endcan @can('schedules.create')<a class="rounded bg-emerald-900 px-4 py-2 text-white" href="{{ route('schedules.create') }}">Tambah Jadwal</a>@endcan @can('schedules.print')<a class="rounded border px-4 py-2" href="{{ route('schedules.print', request()->query()) }}">Cetak Jadwal</a>@endcan @can('schedules.export')<a class="rounded border px-4 py-2" href="{{ route('schedules.export') }}">Export CSV</a>@endcan</div>@can('schedules.print')
<div class="grid gap-4 rounded-xl bg-white p-5 shadow lg:grid-cols-2">
 <section><h2 class="font-semibold text-emerald-950">Template Word Jadwal Pelajaran</h2><p class="mt-1 text-sm text-slate-600">Template ini digunakan sebagai dasar Export Word Resmi dan disimpan secara privat.</p>
 <p class="mt-3 text-sm"><strong>Status:</strong> {{ $scheduleTemplatePath ? 'Tersedia' : 'Belum tersedia' }}@if($scheduleTemplatePath) · {{ basename($scheduleTemplatePath) }} · diperbarui {{ $scheduleTemplateSetting->updated_at?->translatedFormat('d F Y H:i') }}@endif</p>
 <form class="mt-3 flex items-center gap-2" method="POST" action="{{ route('schedules.templates.store') }}" enctype="multipart/form-data">@csrf<input required type="file" name="template" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document"><button class="rounded bg-emerald-900 px-4 py-2 text-white">{{ $scheduleTemplatePath ? 'Ganti Template' : 'Unggah Template' }}</button></form>
 @if($scheduleTemplatePath)<a class="mt-3 inline-block rounded border border-emerald-800 px-4 py-2 text-emerald-900" href="{{ route('schedules.templates.download') }}">Unduh Template</a>@endif</section>
 <section><h2 class="font-semibold text-emerald-950">Export Word Resmi</h2><form class="mt-3 grid gap-3 sm:grid-cols-2" method="GET" action="{{ route('schedules.export-word') }}">
 <select required name="tahun_ajaran_id"><option value="">Tahun Ajaran</option>@foreach($academicYears as $year)<option value="{{ $year->id }}">{{ $year->name }}</option>@endforeach</select>
 <select required name="semester_id"><option value="">Semester</option>@foreach($semesters as $semester)<option value="{{ $semester->id }}">{{ $semester->name }}</option>@endforeach</select>
 <input required type="date" name="tanggal_dokumen" value="{{ now()->toDateString() }}">
 <select name="kelas"><option value="">Semua Kelas</option>@foreach($classrooms->whereIn('code', \App\Services\Academic\LessonScheduleTemplateService::CLASS_CODES) as $class)<option value="{{ $class->code }}">{{ $class->name }}</option>@endforeach</select>
 <button class="rounded bg-emerald-900 px-4 py-2 text-white sm:col-span-2">Export Word Resmi</button></form>
 <p class="mt-3 text-xs text-slate-500">Ringkasan pemetaan (kelas, pelajaran, kegiatan, istirahat, kelas kosong, dan sel tidak terpetakan) divalidasi dari data terbaru saat ekspor.</p></section>
</div>
@endcan
<form class="grid gap-3 rounded-xl bg-white p-4 shadow md:grid-cols-6"><select name="semester_id"><option value="">Semester</option>@foreach($semesters as $s)<option value="{{ $s->id }}" @selected(request('semester_id')==$s->id)>{{ $s->name }}</option>@endforeach</select><select name="classroom_id"><option value="">Jadwal Kelas</option>@foreach($classrooms as $c)<option value="{{ $c->id }}" @selected(request('classroom_id')==$c->id)>{{ $c->name }}</option>@endforeach</select><select name="employee_id"><option value="">Jadwal Guru</option>@foreach($employees as $e)<option value="{{ $e->id }}" @selected(request('employee_id')==$e->id)>{{ $e->name }}</option>@endforeach</select><select name="day_of_week"><option value="">Hari</option>@foreach($days as $d)<option value="{{ $d->value }}" @selected(request('day_of_week')===$d->value)>{{ $d->label() }}</option>@endforeach</select><select name="entry_type"><option value="">Jenis slot</option><option value="lesson">Pelajaran</option><option value="activity">Kegiatan</option><option value="break">Istirahat/Pulang</option></select><button class="rounded bg-emerald-900 px-4 py-2 text-white">Terapkan</button></form><div class="rounded-xl bg-white p-4 shadow"><h2 class="font-semibold">Tampilan Mingguan</h2>@foreach($days as $d)<h3 class="mt-3 font-medium">{{ $d->label() }}</h3>@forelse($weekly[$d->value]??[] as $s)<p>{{ substr($s->starts_at,0,5) }}–{{ substr($s->ends_at,0,5) }} · {{ $s->classroom?->name }} · {{ $s->entry_type?->value === 'lesson' ? $s->subject?->name : $s->activity_name }} @if($s->entry_type?->value === 'lesson') · {{ $s->employee?->name }} @endif · {{ $s->room ?: '-' }}</p>@empty<p class="text-slate-500">Tidak ada jadwal.</p>@endforelse @endforeach</div><div class="rounded-xl bg-white p-4 shadow"><table class="min-w-full text-sm"><thead><tr><th>Hari</th><th>Jam</th><th>Kelas</th><th>Mata Pelajaran</th><th>Guru</th><th>Ruangan</th><th>Tindakan</th></tr></thead><tbody>@forelse($schedules as $s)<tr class="border-t"><td>{{ $s->day_of_week?->label() }}</td><td>{{ substr($s->starts_at,0,5) }}–{{ substr($s->ends_at,0,5) }}</td><td>{{ $s->classroom?->name }}</td><td>{{ $s->entry_type?->value === 'lesson' ? $s->subject?->name : $s->activity_name }}</td><td>{{ $s->entry_type?->value === 'lesson' ? $s->employee?->name : '-' }}</td><td>{{ $s->room }}</td><td><a href="{{ route('schedules.show',$s) }}">Detail</a> @can('schedules.update')<a href="{{ route('schedules.edit',$s) }}">Edit</a>@endcan</td></tr>@empty<tr><td colspan="7" class="py-8 text-center text-slate-500">Belum ada Jadwal Pelajaran.</td></tr>@endforelse</tbody></table>{{ $schedules->links() }}</div></div></x-app-layout>
