<div class="grid gap-4 lg:grid-cols-3">
<x-ui.card id="fitting"><h2 class="font-bold">Fitting Seragam</h2>
@if($applicant->fitting)<p class="mt-2 text-sm">{{ $applicant->fitting->scheduled_at?->translatedFormat('d M Y H:i') }} · {{ $applicant->fitting->attendance_status }}</p>@endif
@can('pmbm.fitting.manage')
@if($applicant->status === \App\Enums\Pmbm\ApplicantStatus::Verified)<form class="mt-3 grid gap-2" method="post" action="{{ route('pmbm.applicants.fitting.schedule',$applicant) }}">@csrf<input class="input" type="datetime-local" name="scheduled_at" required><input class="input" name="location" placeholder="Lokasi"><button class="btn btn-secondary">Jadwalkan fitting</button></form>
@elseif($applicant->status === \App\Enums\Pmbm\ApplicantStatus::FittingScheduled)<form class="mt-3 grid gap-2" method="post" action="{{ route('pmbm.applicants.fitting.complete',$applicant) }}">@csrf<p class="text-xs text-slate-500">{{ $applicant->gender === 'male' ? 'Ukuran laki-laki: baju, celana, peci, kaus kaki.' : 'Ukuran perempuan: baju, rok, jilbab, kaus kaki.' }}</p><input class="input" name="shirt_size" placeholder="Ukuran baju"><input class="input" name="{{ $applicant->gender === 'male' ? 'pants_size' : 'skirt_size' }}" placeholder="{{ $applicant->gender === 'male' ? 'Ukuran celana' : 'Ukuran rok' }}"><input class="input" name="{{ $applicant->gender === 'male' ? 'cap_size' : 'hijab_size' }}" placeholder="{{ $applicant->gender === 'male' ? 'Ukuran peci' : 'Ukuran jilbab' }}"><input class="input" name="socks_size" placeholder="Ukuran kaus kaki"><textarea class="input" name="notes" placeholder="Catatan"></textarea><button class="btn btn-primary">Tandai fitting selesai</button></form>@endif
@endcan</x-ui.card>
<x-ui.card id="wawancara"><h2 class="font-bold">Wawancara Orang Tua</h2>@if($applicant->interview)<p class="mt-2 text-sm">{{ $applicant->interview->scheduled_at?->translatedFormat('d M Y H:i') }}@if($applicant->interview->completed_at) · selesai@endif</p>@endif
@can('pmbm.interview.manage')
@if(in_array($applicant->status,[\App\Enums\Pmbm\ApplicantStatus::Verified,\App\Enums\Pmbm\ApplicantStatus::FittingCompleted],true))<form class="mt-3 grid gap-2" method="post" action="{{ route('pmbm.applicants.interview.schedule',$applicant) }}">@csrf<input class="input" type="datetime-local" name="scheduled_at" required><button class="btn btn-secondary">Jadwalkan wawancara</button></form>
@elseif($applicant->status === \App\Enums\Pmbm\ApplicantStatus::InterviewScheduled)<form class="mt-3 grid gap-2" method="post" action="{{ route('pmbm.applicants.interview.complete',$applicant) }}">@csrf @foreach($questions as $question)<label class="text-sm">{{ $question->question }} @if($question->required)*@endif <textarea class="input mt-1" name="answers[{{ $question->id }}]">{{ data_get($applicant->interview?->answers->firstWhere('question_id',$question->id),'answer.0') }}</textarea></label>@endforeach<textarea class="input" name="summary" placeholder="Ringkasan wawancara"></textarea><button class="btn btn-primary">Selesaikan wawancara</button></form>@endif
@endcan</x-ui.card>
<x-ui.card id="observasi"><h2 class="font-bold">Observasi Anak</h2>@if($applicant->observation)<p class="mt-2 text-sm">{{ $applicant->observation->result }} · {{ $applicant->observation->completed_at?->translatedFormat('d M Y H:i') }}</p>@endif
@can('pmbm.observation.manage')@if($applicant->status === \App\Enums\Pmbm\ApplicantStatus::Interviewed)<form class="mt-3 grid gap-2" method="post" action="{{ route('pmbm.applicants.observation.complete',$applicant) }}">@csrf<select class="input" name="result"><option value="READY">Siap</option><option value="NEEDS_SUPPORT">Memerlukan pendampingan</option><option value="FOLLOW_UP_REQUIRED">Perlu tindak lanjut</option></select><textarea class="input" name="summary" placeholder="Ringkasan observasi"></textarea><textarea class="input" name="internal_note" placeholder="Catatan internal"></textarea><button class="btn btn-primary">Selesaikan observasi</button></form>@endif@endcan</x-ui.card>
</div>
<div class="grid gap-4 lg:grid-cols-2">
@can('pmbm.decision.manage')<x-ui.card id="keputusan-operasional"><h2 class="font-bold">Penetapan Hasil</h2>@if($applicant->decision)<p class="mt-2 text-sm">Rekomendasi: {{ $applicant->decision->decision }} @if($applicant->decision->approved_at) · disetujui@endif</p>@endif
@if($applicant->status === \App\Enums\Pmbm\ApplicantStatus::DecisionPending)<form class="mt-3 grid gap-2" method="post" action="{{ route('pmbm.applicants.decision',$applicant) }}">@csrf<select class="input" name="decision"><option value="accepted">Diterima</option><option value="waitlisted">Daftar cadangan</option><option value="rejected">Belum diterima</option></select><textarea class="input" name="public_note" placeholder="Keterangan untuk orang tua"></textarea><textarea class="input" name="internal_note" placeholder="Catatan internal"></textarea><button class="btn btn-primary">Simpan rekomendasi</button></form>@endif
@if($applicant->status === \App\Enums\Pmbm\ApplicantStatus::Waitlisted)<form class="mt-3 flex gap-2" method="post" action="{{ route('pmbm.applicants.waitlist.promote',$applicant) }}">@csrf<input class="input" name="promotion_reason" placeholder="Alasan promosi" required><button class="btn btn-secondary">Promosikan</button></form>@endif</x-ui.card>@endcan
@can('pmbm.decision.approve')@if($applicant->status === \App\Enums\Pmbm\ApplicantStatus::DecisionPending && $applicant->decision)<x-ui.card><h2 class="font-bold">Persetujuan Kepala Madrasah</h2><form class="mt-3" method="post" action="{{ route('pmbm.applicants.decision.approve',$applicant) }}">@csrf<button class="btn btn-primary">Setujui keputusan</button></form></x-ui.card>@endif@endcan
</div>
