<?php
declare(strict_types=1);
namespace App\Http\Controllers\Academic;
use App\Http\Controllers\Controller;use App\Http\Requests\Academic\ClassroomJournalRequest;use App\Models\{AcademicYear,Classroom,ClassroomJournal,Semester,StudentAttendance,TeachingJournal};use App\Services\Academic\ClassroomJournalService;use Illuminate\Http\{RedirectResponse,Request};use Illuminate\View\View;
class ClassroomJournalController extends Controller
{
 public function index(Request $r):View{$year=$r->integer('academic_year_id')?:AcademicYear::where('is_active',true)->value('id');$semester=$r->integer('semester_id')?:Semester::where('academic_year_id',$year)->where('is_active',true)->value('id');$date=$r->input('journal_date',today()->toDateString());$q=ClassroomJournal::with(['classroom.gradeLevel','classroom.homeroomPersonnel'])->where(['academic_year_id'=>$year,'semester_id'=>$semester])->whereDate('journal_date',$date);if($r->filled('classroom_id'))$q->where('classroom_id',$r->integer('classroom_id'));if(!$r->user()->can('classroom-journals.view-all'))$q->whereHas('classroom',fn($x)=>$x->where('homeroom_personnel_id',$r->user()->personnel?->id??0));return view('academic.classroom-journals.index',$this->options($year)+['journals'=>$q->paginate(20)->withQueryString(),'year'=>$year,'semester'=>$semester,'date'=>$date]);}
 public function create(Request $r):View{$year=AcademicYear::where('is_active',true)->value('id');return view('academic.classroom-journals.form',$this->options($year)+['journal'=>new ClassroomJournal(['academic_year_id'=>$year,'semester_id'=>Semester::where('academic_year_id',$year)->where('is_active',true)->value('id'),'journal_date'=>today()])]);}
 public function store(ClassroomJournalRequest $r,ClassroomJournalService $s):RedirectResponse{$j=$s->save($r->validated(),$r->user());return redirect()->route('academic.classroom-journals.show',$j)->with('success','Jurnal kelas berhasil disimpan.');}
 public function show(Request $r,ClassroomJournal $classroomJournal):View{$this->ensureView($r,$classroomJournal);$classroomJournal->load(['classroom.gradeLevel','classroom.homeroomPersonnel']);$attendance=StudentAttendance::where('classroom_id',$classroomJournal->classroom_id)->whereDate('attendance_date',$classroomJournal->journal_date)->selectRaw('status,count(*) total')->groupBy('status')->pluck('total','status');$teachingCount=TeachingJournal::where('classroom_id',$classroomJournal->classroom_id)->whereDate('journal_date',$classroomJournal->journal_date)->count();return view('academic.classroom-journals.show',['journal'=>$classroomJournal,'attendance'=>$attendance,'teachingCount'=>$teachingCount]);}
 public function edit(Request $r,ClassroomJournal $classroomJournal,ClassroomJournalService $s):View{$s->ensureManage($r->user(),$classroomJournal->classroom);return view('academic.classroom-journals.form',$this->options($classroomJournal->academic_year_id)+['journal'=>$classroomJournal]);}
 public function update(ClassroomJournalRequest $r,ClassroomJournal $classroomJournal,ClassroomJournalService $s):RedirectResponse{$data=$r->validated();$data['classroom_id']=$classroomJournal->classroom_id;$data['journal_date']=$classroomJournal->journal_date->toDateString();$j=$s->save($data,$r->user());return redirect()->route('academic.classroom-journals.show',$j)->with('success','Jurnal kelas berhasil diperbarui.');}
 private function options($year):array{return ['years'=>AcademicYear::latest('starts_at')->get(),'semesters'=>Semester::where('academic_year_id',$year)->get(),'rooms'=>Classroom::with(['gradeLevel','homeroomPersonnel'])->where('academic_year_id',$year)->where('is_active',true)->get()];}
 private function ensureView(Request $r,ClassroomJournal $j):void{abort_if(!$r->user()->can('classroom-journals.view-all')&&$j->classroom->homeroom_personnel_id!==$r->user()->personnel?->id,403);}
}
