<?php

declare(strict_types=1);
namespace App\Http\Controllers\Academic;
use App\Http\Controllers\Controller; use App\Http\Requests\Academic\TeachingAssignmentRequest; use App\Models\{AcademicYear,Classroom,Employee,Semester,Subject,TeachingAssignment}; use App\Services\Academic\{TeacherWorkloadService,TeachingAssignmentService}; use Illuminate\Http\{RedirectResponse,Request,StreamedResponse}; use Illuminate\View\View;
class TeachingAssignmentController extends Controller { public function index(Request $r, TeacherWorkloadService $w):View{$q=TeachingAssignment::with(['academicYear','semester','employee','classroom','subject','schedules'])->when($r->academic_year_id,fn($q,$v)=>$q->where('academic_year_id',$v))->when($r->semester_id,fn($q,$v)=>$q->where('semester_id',$v))->when($r->classroom_id,fn($q,$v)=>$q->where('classroom_id',$v))->when($r->employee_id,fn($q,$v)=>$q->where('employee_id',$v))->when($r->subject_id,fn($q,$v)=>$q->where('subject_id',$v))->when($r->filled('status'),fn($q)=>$q->where('is_active',$r->boolean('status'))); return view('teaching-assignments.index',$this->refs()+['assignments'=>$q->paginate(15)->withQueryString(),'workloads'=>$w->summarize(),'filters'=>$r->all()]);}
 public function create():View{return view('teaching-assignments.form',$this->refs()+['assignment'=>new TeachingAssignment]);} public function store(TeachingAssignmentRequest $r,TeachingAssignmentService $s):RedirectResponse{$a=$s->save($r->validated()+['is_active'=>$r->boolean('is_active',true)]);return redirect()->route('teaching-assignments.show',$a)->with('status','Penugasan Mengajar berhasil disimpan.');} public function show(TeachingAssignment $teachingAssignment):View{return view('teaching-assignments.show',['assignment'=>$teachingAssignment->load(['academicYear','semester','employee','classroom','subject','schedules'])]);} public function edit(TeachingAssignment $teachingAssignment):View{return view('teaching-assignments.form',$this->refs()+['assignment'=>$teachingAssignment]);} public function update(TeachingAssignmentRequest $r,TeachingAssignment $teachingAssignment,TeachingAssignmentService $s):RedirectResponse{$s->save($r->validated()+['is_active'=>$r->boolean('is_active')],$teachingAssignment);return redirect()->route('teaching-assignments.show',$teachingAssignment)->with('status','Penugasan Mengajar diperbarui.');} public function toggle(TeachingAssignment $teachingAssignment,TeachingAssignmentService $s):RedirectResponse{$s->toggle($teachingAssignment,!$teachingAssignment->is_active);return back()->with('status','Status penugasan diperbarui.');} public function destroy(TeachingAssignment $teachingAssignment):RedirectResponse{if($teachingAssignment->schedules()->exists()){app(TeachingAssignmentService::class)->toggle($teachingAssignment,false);return back()->with('status','Penugasan memiliki jadwal sehingga dinonaktifkan.');}$teachingAssignment->delete();return redirect()->route('teaching-assignments.index')->with('status','Penugasan dihapus.');}
 public function export():StreamedResponse{$rows=TeachingAssignment::with(['employee','classroom','subject','academicYear','semester'])->get();return response()->streamDownload(function()use($rows){$f=fopen('php://output','w');fputcsv($f,['Guru','Kelas','Mata Pelajaran','Tahun Ajaran','Semester','Jam per Minggu','Status']);foreach($rows as $a)fputcsv($f,[$a->employee?->name,$a->classroom?->name,$a->subject?->name,$a->academicYear?->name,$a->semester?->name,$a->weekly_hours,$a->is_active?'Aktif':'Nonaktif']);},'penugasan-mengajar.csv',['Content-Type'=>'text/csv']);}
 private function refs():array{return ['academicYears'=>AcademicYear::all(),'semesters'=>Semester::all(),'employees'=>Employee::where('is_active',true)->get(),'classrooms'=>Classroom::where('is_active',true)->get(),'subjects'=>Subject::where('is_active',true)->get()];}}
