<?php
declare(strict_types=1);
namespace App\Http\Controllers\Academic;
use App\Http\Controllers\Controller;use App\Http\Requests\Academic\TeachingJournalRequest;use App\Models\{AcademicSubject,AcademicYear,Classroom,Personnel,Semester,StudentAttendance,TeachingJournal};use App\Services\Academic\TeachingJournalService;use Illuminate\Http\{RedirectResponse,Request};use Illuminate\View\View;
class TeachingJournalController extends Controller
{
 public function index(Request $r):View{$year=$r->integer('academic_year_id')?:AcademicYear::where('is_active',true)->value('id');$semester=$r->integer('semester_id')?:Semester::where('academic_year_id',$year)->where('is_active',true)->value('id');$date=$r->input('journal_date',today()->toDateString());$q=TeachingJournal::with(['personnel','classroom.gradeLevel','subject'])->where(['academic_year_id'=>$year,'semester_id'=>$semester])->whereDate('journal_date',$date);if(!$r->user()->can('teaching-journals.view-all'))$q->where('personnel_id',$r->user()->personnel?->id??0);foreach(['classroom_id','academic_subject_id','personnel_id'] as $f)if($r->filled($f))$q->where($f,$r->integer($f));return view('academic.teaching-journals.index',$this->options($year)+['journals'=>$q->latest('journal_date')->paginate(20)->withQueryString(),'year'=>$year,'semester'=>$semester,'date'=>$date]);}
 public function create(Request $r):View{$this->personnelOrAbort($r);$year=AcademicYear::where('is_active',true)->value('id');return view('academic.teaching-journals.form',$this->options($year)+['journal'=>new TeachingJournal(['academic_year_id'=>$year,'semester_id'=>Semester::where('academic_year_id',$year)->where('is_active',true)->value('id'),'journal_date'=>today()])]);}
 public function store(TeachingJournalRequest $r,TeachingJournalService $s):RedirectResponse{$j=$s->save($r->validated(),$r->user());return redirect()->route('academic.teaching-journals.show',$j)->with('success','Jurnal mengajar berhasil disimpan.');}
 public function show(Request $r,TeachingJournal $teachingJournal):View{$this->ensureView($r,$teachingJournal);$teachingJournal->load(['personnel','classroom.gradeLevel','subject']);$summary=StudentAttendance::where('classroom_id',$teachingJournal->classroom_id)->whereDate('attendance_date',$teachingJournal->journal_date)->selectRaw('status, count(*) total')->groupBy('status')->pluck('total','status');return view('academic.teaching-journals.show',['journal'=>$teachingJournal,'attendance'=>$summary]);}
 public function edit(Request $r,TeachingJournal $teachingJournal):View{$this->ensureManage($r,$teachingJournal);return view('academic.teaching-journals.form',$this->options($teachingJournal->academic_year_id)+['journal'=>$teachingJournal]);}
 public function update(TeachingJournalRequest $r,TeachingJournal $teachingJournal,TeachingJournalService $s):RedirectResponse{$j=$s->save($r->validated(),$r->user(),$teachingJournal);return redirect()->route('academic.teaching-journals.show',$j)->with('success','Jurnal mengajar berhasil diperbarui.');}
 public function destroy(Request $r,TeachingJournal $teachingJournal,TeachingJournalService $s):RedirectResponse{$s->delete($teachingJournal,$r->user());return redirect()->route('academic.teaching-journals.index')->with('success','Jurnal mengajar berhasil dihapus.');}
 private function options($year):array{return ['years'=>AcademicYear::latest('starts_at')->get(),'semesters'=>Semester::where('academic_year_id',$year)->get(),'rooms'=>Classroom::with('gradeLevel')->where('academic_year_id',$year)->where('is_active',true)->get(),'subjects'=>AcademicSubject::where('is_active',true)->orderBy('sort_order')->get(),'teachers'=>Personnel::where('is_active',true)->orderBy('full_name')->get()];}
 private function personnelOrAbort(Request $r):void{abort_unless($r->user()->personnel?->is_active,403,TeachingJournalService::NO_PERSONNEL);}
 private function ensureView(Request $r,TeachingJournal $j):void{abort_if(!$r->user()->can('teaching-journals.view-all')&&$j->personnel_id!==$r->user()->personnel?->id,403);}
 private function ensureManage(Request $r,TeachingJournal $j):void{abort_unless($r->user()->can('teaching-journals.manage'),403);$this->ensureView($r,$j);}
}
