<?php
declare(strict_types=1);
namespace App\Services\Hrd;
use App\Enums\Hrd\AttendanceStatus;use App\Exceptions\AttendanceSecurityException;use App\Models\{Personnel,PersonnelAttendance,PersonnelAttendanceAudit,User};use App\Services\Settings\ApplicationSettingService;use Carbon\CarbonImmutable;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class AttendanceService
{
 public function __construct(private ApplicationSettingService $settings){}
 public function shiftWindow(int $shift,CarbonImmutable $date):array{$start=CarbonImmutable::parse($date->toDateString().' '.$this->settings->get("hrd_shift_{$shift}_start",'07:00'));$end=CarbonImmutable::parse($date->toDateString().' '.$this->settings->get("hrd_shift_{$shift}_end",'15:00'));if($end->lessThanOrEqualTo($start))$end=$end->addDay();return[$start,$end];}
 public function distanceMeters(float $a,float $b,float $c,float $d):float{$earth=6371000;$x=deg2rad($c-$a);$y=deg2rad($d-$b);$v=sin($x/2)**2+cos(deg2rad($a))*cos(deg2rad($c))*sin($y/2)**2;return 2*$earth*asin(min(1,sqrt($v)));}
 /** @return array{distance:float|null} */public function validateLocation(array $data,?CarbonImmutable $now=null):array
 {if(!$this->settings->get('hrd_attendance_location_enabled',true))return['distance'=>null];foreach(['latitude','longitude','accuracy','location_captured_at']as$key)if(!array_key_exists($key,$data)||$data[$key]===null)throw new AttendanceSecurityException('LOCATION_REQUIRED','Data lokasi terbaru wajib dikirim.');$now??=CarbonImmutable::now();$captured=CarbonImmutable::parse($data['location_captured_at']);$maxAge=(int)$this->settings->get('hrd_attendance_location_max_age_seconds',30);if($captured->lt($now->subSeconds($maxAge))||$captured->gt($now->addSeconds(10)))throw new AttendanceSecurityException('LOCATION_EXPIRED','Lokasi telah kedaluwarsa. Silakan ambil lokasi kembali.');if((float)$data['accuracy']>(float)$this->settings->get('hrd_attendance_max_accuracy_meter',50))throw new AttendanceSecurityException('LOCATION_ACCURACY_TOO_LOW','Akurasi lokasi belum memadai. Tunggu GPS mendapatkan lokasi yang lebih akurat lalu coba kembali.');$targetLat=$this->settings->get('hrd_attendance_latitude');$targetLng=$this->settings->get('hrd_attendance_longitude');if($targetLat===null||$targetLng===null)throw new AttendanceSecurityException('LOCATION_REQUIRED','Titik lokasi madrasah belum dikonfigurasi.',503);$distance=$this->distanceMeters((float)$data['latitude'],(float)$data['longitude'],(float)$targetLat,(float)$targetLng);if($distance>(float)$this->settings->get('hrd_attendance_radius_meter',20))throw new AttendanceSecurityException('LOCATION_OUTSIDE_RADIUS','Anda berada di luar radius absensi madrasah.');return['distance'=>$distance];}
 public function submit(Personnel $p,User $actor,string $action,array $data,Request $request,?CarbonImmutable $now=null):PersonnelAttendance
 {$now??=CarbonImmutable::now();return DB::transaction(function()use($p,$actor,$action,$data,$request,$now){[$challenge,$device,$face]=app(AttendanceSecurityService::class)->consume($data['challenge_id'],$data['nonce'],$actor,$p,$action,$request);$geo=$this->validateLocation($data,$now);$row=$action==='check_in'?$this->persistCheckIn($p,$actor,$data,$now,$device?->id,$geo['distance']):$this->persistCheckOut($p,$actor,$data,$now,$device?->id,$geo['distance']);PersonnelAttendanceAudit::create(['personnel_id'=>$p->id,'attendance_id'=>$row->id,'challenge_id'=>$challenge->id,'device_id'=>$device?->id,'event'=>$action,'result'=>'accepted','ip'=>$request->ip(),'latitude'=>$data['latitude']??null,'longitude'=>$data['longitude']??null,'accuracy'=>$data['accuracy']??null,'distance'=>$geo['distance'],'face_verified'=>$face!==null,'face_confidence'=>$face?->confidence,'risk_flags'=>$row->risk_flags,'occurred_at'=>$now]);return$row;},3);}
 private function persistCheckIn(Personnel $p,User $actor,array $d,CarbonImmutable $now,?int $deviceId,?float $distance):PersonnelAttendance{$shift=(int)($p->default_shift_number?:1);[$start]=$this->shiftWindow($shift,$now);$earliest=$start->subMinutes((int)$this->settings->get('hrd_early_checkin_minutes',60));$latest=$start->addHours((int)$this->settings->get('hrd_max_late_checkin_hours',4));if($now->lessThan($earliest)||$now->greaterThan($latest))throw ValidationException::withMessages(['time'=>'Waktu check-in berada di luar rentang yang diizinkan.']);if(PersonnelAttendance::where(['personnel_id'=>$p->id,'attendance_date'=>$now->toDateString(),'shift_number'=>$shift])->lockForUpdate()->exists())throw new AttendanceSecurityException('ATTENDANCE_ALREADY_CHECKED_IN','Check-in untuk shift ini sudah tercatat.',409);$late=max(0,$start->diffInMinutes($now,false));return PersonnelAttendance::create(['personnel_id'=>$p->id,'attendance_date'=>$now->toDateString(),'shift_number'=>$shift,'check_in_time'=>$now,'check_in_latitude'=>$d['latitude']??null,'check_in_longitude'=>$d['longitude']??null,'check_in_accuracy'=>$d['accuracy']??null,'check_in_distance'=>$distance,'check_in_ip'=>request()->ip(),'check_in_device_id'=>$deviceId,'status'=>$late>0?AttendanceStatus::Late:AttendanceStatus::Present,'method'=>'self','late_minutes'=>$late,'created_by'=>$actor->id,'updated_by'=>$actor->id]);}
 private function persistCheckOut(Personnel $p,User $actor,array $d,CarbonImmutable $now,?int $deviceId,?float $distance):PersonnelAttendance{$row=PersonnelAttendance::where('personnel_id',$p->id)->whereNotNull('check_in_time')->whereNull('check_out_time')->latest('attendance_date')->lockForUpdate()->first();if(!$row)throw new AttendanceSecurityException('ATTENDANCE_NOT_CHECKED_IN','Check-out tidak dapat dilakukan sebelum check-in.',409);[, $end]=$this->shiftWindow($row->shift_number,CarbonImmutable::parse($row->attendance_date));$row->update(['check_out_time'=>$now,'check_out_latitude'=>$d['latitude']??null,'check_out_longitude'=>$d['longitude']??null,'check_out_accuracy'=>$d['accuracy']??null,'check_out_distance'=>$distance,'check_out_ip'=>request()->ip(),'check_out_device_id'=>$deviceId,'early_leave_minutes'=>max(0,$now->diffInMinutes($end,false)),'overtime_minutes'=>max(0,$end->diffInMinutes($now,false)),'updated_by'=>$actor->id]);return$row->refresh();}
}
