<?php
declare(strict_types=1);
namespace App\Services\Hrd;
use App\Enums\Hrd\AttendanceStatus;use App\Models\{Personnel,PersonnelAttendance,User};use App\Services\Settings\ApplicationSettingService;use Carbon\CarbonImmutable;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class AttendanceService{public function __construct(private ApplicationSettingService $settings){}
 public function shiftWindow(int $shift, CarbonImmutable $date):array{$start=CarbonImmutable::parse($date->toDateString().' '.$this->settings->get("hrd_shift_{$shift}_start",'07:00'));$end=CarbonImmutable::parse($date->toDateString().' '.$this->settings->get("hrd_shift_{$shift}_end",'15:00'));if($end->lessThanOrEqualTo($start))$end=$end->addDay();return[$start,$end];}
 public function distanceMeters(float $a,float $b,float $c,float $d):float{$earth=6371000;$x=deg2rad($c-$a);$y=deg2rad($d-$b);$v=sin($x/2)**2+cos(deg2rad($a))*cos(deg2rad($c))*sin($y/2)**2;return 2*$earth*asin(min(1,sqrt($v)));}
 private function validateLocation(float $lat,float $lng):void{$targetLat=$this->settings->get('hrd_attendance_latitude');$targetLng=$this->settings->get('hrd_attendance_longitude');if($targetLat===null||$targetLng===null)return;$distance=$this->distanceMeters($lat,$lng,(float)$targetLat,(float)$targetLng);if($distance>(int)$this->settings->get('hrd_attendance_radius_meter',20))throw ValidationException::withMessages(['location'=>'Lokasi berada di luar radius absensi.']);}
 public function checkIn(Personnel $personnel,float $lat,float $lng,User $actor,string $method='self',?CarbonImmutable $now=null):PersonnelAttendance{$this->validateLocation($lat,$lng);$now??=CarbonImmutable::now();$shift=(int)($personnel->default_shift_number?:1);[$start]=$this->shiftWindow($shift,$now);$earliest=$start->subMinutes((int)$this->settings->get('hrd_early_checkin_minutes',60));$latest=$start->addHours((int)$this->settings->get('hrd_max_late_checkin_hours',4));if($now->lessThan($earliest)||$now->greaterThan($latest))throw ValidationException::withMessages(['time'=>'Waktu check-in berada di luar rentang yang diizinkan.']);$late=max(0,$start->diffInMinutes($now,false));return DB::transaction(function()use($personnel,$lat,$lng,$actor,$method,$now,$shift,$late){if(PersonnelAttendance::query()->where(['personnel_id'=>$personnel->id,'attendance_date'=>$now->toDateString(),'shift_number'=>$shift])->lockForUpdate()->exists())throw ValidationException::withMessages(['attendance'=>'Check-in untuk shift ini sudah tercatat.']);$row=PersonnelAttendance::create(['personnel_id'=>$personnel->id,'attendance_date'=>$now->toDateString(),'shift_number'=>$shift,'check_in_time'=>$now,'check_in_latitude'=>$lat,'check_in_longitude'=>$lng,'status'=>$late>0?AttendanceStatus::Late:AttendanceStatus::Present,'method'=>$method,'late_minutes'=>$late,'created_by'=>$actor->id,'updated_by'=>$actor->id]);activity('hrd')->causedBy($actor)->performedOn($row)->log('Pegawai melakukan check-in.');return$row;});}
 public function checkOut(Personnel $personnel,float $lat,float $lng,User $actor,?CarbonImmutable $now=null):PersonnelAttendance{$this->validateLocation($lat,$lng);$now??=CarbonImmutable::now();return DB::transaction(function()use($personnel,$lat,$lng,$actor,$now){$row=PersonnelAttendance::query()->where('personnel_id',$personnel->id)->whereNotNull('check_in_time')->whereNull('check_out_time')->latest('attendance_date')->lockForUpdate()->first();if(!$row)throw ValidationException::withMessages(['attendance'=>'Check-out tidak dapat dilakukan sebelum check-in.']);[, $end]=$this->shiftWindow($row->shift_number,CarbonImmutable::parse($row->attendance_date));$row->update(['check_out_time'=>$now,'check_out_latitude'=>$lat,'check_out_longitude'=>$lng,'early_leave_minutes'=>max(0,$now->diffInMinutes($end,false)),'overtime_minutes'=>max(0,$end->diffInMinutes($now,false)),'updated_by'=>$actor->id]);activity('hrd')->causedBy($actor)->performedOn($row)->log('Pegawai melakukan check-out.');return$row->refresh();});}}
