<?php
declare(strict_types=1);namespace App\Services\Hrd;use App\Contracts\FaceRecognitionService;use App\Exceptions\AttendanceSecurityException;use App\Models\Personnel;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Http;
class PythonFaceRecognitionService implements FaceRecognitionService{
 public function encode(UploadedFile $sample):array{$data=$this->post('/v1/faces/encode',['image'=>$sample]);return['embedding'=>$data['embedding'],'quality_score'=>(float)$data['quality_score'],'model'=>(string)$data['model'],'model_version'=>(string)($data['model_version']??'')];}
 public function verify(Personnel $expected,UploadedFile $snapshot,float $threshold):array{$profile=$expected->faceProfile()->with('samples')->first();if(!$profile)throw new AttendanceSecurityException('FACE_NOT_ENROLLED','Wajah Anda belum terdaftar untuk absensi. Silakan hubungi HRD.',422);$references=$profile->samples->pluck('embedding')->values()->all();$data=$this->post('/v1/faces/verify',['image'=>$snapshot,'fields'=>['reference_embeddings'=>json_encode($references,JSON_THROW_ON_ERROR),'threshold'=>(string)$threshold]]);$matched=($data['matched']??false)&&((float)($data['confidence']??0)>=$threshold);if($matched)$profile->update(['last_verified_at'=>now()]);return['matched_personnel_id'=>$matched?$expected->id:null,'confidence'=>(float)($data['confidence']??0),'faces'=>(int)($data['faces']??0),'liveness_passed'=>$data['liveness_passed']??null];}
 public function health():array{if(config('face-recognition.url')==='')return['status'=>'unavailable','model_loaded'=>false];try{return Http::timeout(config('face-recognition.timeout'))->get(config('face-recognition.url').'/health')->throw()->json();}catch(\Throwable){return['status'=>'offline','model_loaded'=>false];}}
 public function provider():string{return'python';}public function livenessSupported():bool{return false;}
 private function post(string$path,array$payload):array{try{$request=Http::timeout(config('face-recognition.timeout'))->withToken((string)config('face-recognition.token'));$file=$payload['image'];$request=$request->attach('image',file_get_contents($file->getRealPath()),$file->getClientOriginalName());foreach($payload['fields']??[]as$k=>$v)$request=$request->attach($k,$v);$response=$request->post(config('face-recognition.url').$path);$data=$response->json();if(!$response->successful()||!is_array($data)){throw new AttendanceSecurityException($data['error']['code']??'FACE_SERVICE_UNAVAILABLE',$data['error']['message']??'Layanan Face Recognition sedang tidak tersedia. Silakan hubungi HRD.',$response->status()>=500?503:422);}return$data;}catch(AttendanceSecurityException$e){throw$e;}catch(\Throwable){throw new AttendanceSecurityException('FACE_SERVICE_UNAVAILABLE','Layanan Face Recognition sedang tidak tersedia. Silakan hubungi HRD.',503);}}
}
